{
//=========Macro generated from canvas: c25/
//=========  (Mon Nov 12 14:16:15 2018) by ROOT version5.34/36
   TCanvas *c25 = new TCanvas("c25", "",65,52,1600,1028);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c25->Range(4.675,-0.007439125,7.925,4.046352);
   c25->SetFillColor(0);
   c25->SetBorderMode(0);
   c25->SetBorderSize(2);
   c25->SetLogy();
   c25->SetFrameBorderMode(0);
   c25->SetFrameBorderMode(0);
   
   TH1F *Npe_noElec_LPMT_numuCC = new TH1F("Npe_noElec_LPMT_numuCC","",20,5,7.6);
   Npe_noElec_LPMT_numuCC->SetBinContent(0,228);
   Npe_noElec_LPMT_numuCC->SetBinContent(1,319);
   Npe_noElec_LPMT_numuCC->SetBinContent(2,523);
   Npe_noElec_LPMT_numuCC->SetBinContent(3,751);
   Npe_noElec_LPMT_numuCC->SetBinContent(4,1135);
   Npe_noElec_LPMT_numuCC->SetBinContent(5,1489);
   Npe_noElec_LPMT_numuCC->SetBinContent(6,1794);
   Npe_noElec_LPMT_numuCC->SetBinContent(7,2042);
   Npe_noElec_LPMT_numuCC->SetBinContent(8,2304);
   Npe_noElec_LPMT_numuCC->SetBinContent(9,2309);
   Npe_noElec_LPMT_numuCC->SetBinContent(10,2268);
   Npe_noElec_LPMT_numuCC->SetBinContent(11,1969);
   Npe_noElec_LPMT_numuCC->SetBinContent(12,1698);
   Npe_noElec_LPMT_numuCC->SetBinContent(13,1358);
   Npe_noElec_LPMT_numuCC->SetBinContent(14,1012);
   Npe_noElec_LPMT_numuCC->SetBinContent(15,660);
   Npe_noElec_LPMT_numuCC->SetBinContent(16,374);
   Npe_noElec_LPMT_numuCC->SetBinContent(17,186);
   Npe_noElec_LPMT_numuCC->SetBinContent(18,68);
   Npe_noElec_LPMT_numuCC->SetBinContent(19,5);
   Npe_noElec_LPMT_numuCC->SetEntries(22492);
   Npe_noElec_LPMT_numuCC->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   Npe_noElec_LPMT_numuCC->SetLineColor(ci);
   Npe_noElec_LPMT_numuCC->SetLineWidth(3);
   Npe_noElec_LPMT_numuCC->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
   Npe_noElec_LPMT_numuCC->GetXaxis()->SetLabelFont(42);
   Npe_noElec_LPMT_numuCC->GetXaxis()->SetLabelSize(0.035);
   Npe_noElec_LPMT_numuCC->GetXaxis()->SetTitleSize(0.035);
   Npe_noElec_LPMT_numuCC->GetXaxis()->SetTitleFont(42);
   Npe_noElec_LPMT_numuCC->GetYaxis()->SetLabelFont(42);
   Npe_noElec_LPMT_numuCC->GetYaxis()->SetLabelSize(0.035);
   Npe_noElec_LPMT_numuCC->GetYaxis()->SetTitleSize(0.035);
   Npe_noElec_LPMT_numuCC->GetYaxis()->SetTitleFont(42);
   Npe_noElec_LPMT_numuCC->GetZaxis()->SetLabelFont(42);
   Npe_noElec_LPMT_numuCC->GetZaxis()->SetLabelSize(0.035);
   Npe_noElec_LPMT_numuCC->GetZaxis()->SetTitleSize(0.035);
   Npe_noElec_LPMT_numuCC->GetZaxis()->SetTitleFont(42);
   Npe_noElec_LPMT_numuCC->Draw("");
   
   TH1F *Npe_noElec_LPMT_nueCC = new TH1F("Npe_noElec_LPMT_nueCC","",20,5,7.6);
   Npe_noElec_LPMT_nueCC->SetBinContent(0,10);
   Npe_noElec_LPMT_nueCC->SetBinContent(1,8);
   Npe_noElec_LPMT_nueCC->SetBinContent(2,5);
   Npe_noElec_LPMT_nueCC->SetBinContent(3,15);
   Npe_noElec_LPMT_nueCC->SetBinContent(4,18);
   Npe_noElec_LPMT_nueCC->SetBinContent(5,49);
   Npe_noElec_LPMT_nueCC->SetBinContent(6,110);
   Npe_noElec_LPMT_nueCC->SetBinContent(7,172);
   Npe_noElec_LPMT_nueCC->SetBinContent(8,202);
   Npe_noElec_LPMT_nueCC->SetBinContent(9,208);
   Npe_noElec_LPMT_nueCC->SetBinContent(10,188);
   Npe_noElec_LPMT_nueCC->SetBinContent(11,135);
   Npe_noElec_LPMT_nueCC->SetBinContent(12,119);
   Npe_noElec_LPMT_nueCC->SetBinContent(13,83);
   Npe_noElec_LPMT_nueCC->SetBinContent(14,82);
   Npe_noElec_LPMT_nueCC->SetBinContent(15,56);
   Npe_noElec_LPMT_nueCC->SetBinContent(16,45);
   Npe_noElec_LPMT_nueCC->SetBinContent(17,33);
   Npe_noElec_LPMT_nueCC->SetBinContent(18,15);
   Npe_noElec_LPMT_nueCC->SetBinContent(19,2);
   Npe_noElec_LPMT_nueCC->SetEntries(1555);
   Npe_noElec_LPMT_nueCC->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Npe_noElec_LPMT_nueCC->SetLineColor(ci);
   Npe_noElec_LPMT_nueCC->SetLineWidth(3);
   Npe_noElec_LPMT_nueCC->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
   Npe_noElec_LPMT_nueCC->GetXaxis()->SetLabelFont(42);
   Npe_noElec_LPMT_nueCC->GetXaxis()->SetLabelSize(0.035);
   Npe_noElec_LPMT_nueCC->GetXaxis()->SetTitleSize(0.035);
   Npe_noElec_LPMT_nueCC->GetXaxis()->SetTitleFont(42);
   Npe_noElec_LPMT_nueCC->GetYaxis()->SetLabelFont(42);
   Npe_noElec_LPMT_nueCC->GetYaxis()->SetLabelSize(0.035);
   Npe_noElec_LPMT_nueCC->GetYaxis()->SetTitleSize(0.035);
   Npe_noElec_LPMT_nueCC->GetYaxis()->SetTitleFont(42);
   Npe_noElec_LPMT_nueCC->GetZaxis()->SetLabelFont(42);
   Npe_noElec_LPMT_nueCC->GetZaxis()->SetLabelSize(0.035);
   Npe_noElec_LPMT_nueCC->GetZaxis()->SetTitleSize(0.035);
   Npe_noElec_LPMT_nueCC->GetZaxis()->SetTitleFont(42);
   Npe_noElec_LPMT_nueCC->Draw("same");
   
   TH1F *Npe_noElec_LPMT_nuNC = new TH1F("Npe_noElec_LPMT_nuNC","",20,5,7.6);
   Npe_noElec_LPMT_nuNC->SetBinContent(0,5263);
   Npe_noElec_LPMT_nuNC->SetBinContent(1,789);
   Npe_noElec_LPMT_nuNC->SetBinContent(2,713);
   Npe_noElec_LPMT_nuNC->SetBinContent(3,662);
   Npe_noElec_LPMT_nuNC->SetBinContent(4,714);
   Npe_noElec_LPMT_nuNC->SetBinContent(5,633);
   Npe_noElec_LPMT_nuNC->SetBinContent(6,603);
   Npe_noElec_LPMT_nuNC->SetBinContent(7,492);
   Npe_noElec_LPMT_nuNC->SetBinContent(8,480);
   Npe_noElec_LPMT_nuNC->SetBinContent(9,376);
   Npe_noElec_LPMT_nuNC->SetBinContent(10,321);
   Npe_noElec_LPMT_nuNC->SetBinContent(11,221);
   Npe_noElec_LPMT_nuNC->SetBinContent(12,198);
   Npe_noElec_LPMT_nuNC->SetBinContent(13,111);
   Npe_noElec_LPMT_nuNC->SetBinContent(14,89);
   Npe_noElec_LPMT_nuNC->SetBinContent(15,53);
   Npe_noElec_LPMT_nuNC->SetBinContent(16,47);
   Npe_noElec_LPMT_nuNC->SetBinContent(17,19);
   Npe_noElec_LPMT_nuNC->SetBinContent(18,10);
   Npe_noElec_LPMT_nuNC->SetBinContent(19,3);
   Npe_noElec_LPMT_nuNC->SetEntries(11797);
   Npe_noElec_LPMT_nuNC->SetStats(0);

   ci = TColor::GetColor("#33cc00");
   Npe_noElec_LPMT_nuNC->SetLineColor(ci);
   Npe_noElec_LPMT_nuNC->SetLineWidth(3);
   Npe_noElec_LPMT_nuNC->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
   Npe_noElec_LPMT_nuNC->GetXaxis()->SetLabelFont(42);
   Npe_noElec_LPMT_nuNC->GetXaxis()->SetLabelSize(0.035);
   Npe_noElec_LPMT_nuNC->GetXaxis()->SetTitleSize(0.035);
   Npe_noElec_LPMT_nuNC->GetXaxis()->SetTitleFont(42);
   Npe_noElec_LPMT_nuNC->GetYaxis()->SetLabelFont(42);
   Npe_noElec_LPMT_nuNC->GetYaxis()->SetLabelSize(0.035);
   Npe_noElec_LPMT_nuNC->GetYaxis()->SetTitleSize(0.035);
   Npe_noElec_LPMT_nuNC->GetYaxis()->SetTitleFont(42);
   Npe_noElec_LPMT_nuNC->GetZaxis()->SetLabelFont(42);
   Npe_noElec_LPMT_nuNC->GetZaxis()->SetLabelSize(0.035);
   Npe_noElec_LPMT_nuNC->GetZaxis()->SetTitleSize(0.035);
   Npe_noElec_LPMT_nuNC->GetZaxis()->SetTitleFont(42);
   Npe_noElec_LPMT_nuNC->Draw("same");
   
   TLegend *leg = new TLegend(0.75,0.7,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Npe_noElec_LPMT_numuCC","#nu_{#mu} CC","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_noElec_LPMT_nueCC","#nu_{e} CC","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_noElec_LPMT_nuNC","#nu_{e}+#nu_{#mu} NC","l");

   ci = TColor::GetColor("#33cc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c25->Modified();
   c25->cd();
   c25->SetSelected(c25);
}
