{
//=========Macro generated from canvas: c16/
//=========  (Mon Nov 12 14:16:11 2018) by ROOT version5.34/36
   TCanvas *c16 = new TCanvas("c16", "",320,52,1600,1028);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c16->Range(2.6,0.202655,6.6,3.616785);
   c16->SetFillColor(0);
   c16->SetBorderMode(0);
   c16->SetBorderSize(2);
   c16->SetLogy();
   c16->SetFrameBorderMode(0);
   c16->SetFrameBorderMode(0);
   
   TH1F *Npe_Elec_SPMT_nueCC = new TH1F("Npe_Elec_SPMT_nueCC","",20,3,6.2);
   Npe_Elec_SPMT_nueCC->SetBinContent(0,6);
   Npe_Elec_SPMT_nueCC->SetBinContent(1,7);
   Npe_Elec_SPMT_nueCC->SetBinContent(2,23);
   Npe_Elec_SPMT_nueCC->SetBinContent(3,47);
   Npe_Elec_SPMT_nueCC->SetBinContent(4,86);
   Npe_Elec_SPMT_nueCC->SetBinContent(5,220);
   Npe_Elec_SPMT_nueCC->SetBinContent(6,433);
   Npe_Elec_SPMT_nueCC->SetBinContent(7,667);
   Npe_Elec_SPMT_nueCC->SetBinContent(8,815);
   Npe_Elec_SPMT_nueCC->SetBinContent(9,964);
   Npe_Elec_SPMT_nueCC->SetBinContent(10,967);
   Npe_Elec_SPMT_nueCC->SetBinContent(11,995);
   Npe_Elec_SPMT_nueCC->SetBinContent(12,841);
   Npe_Elec_SPMT_nueCC->SetBinContent(13,690);
   Npe_Elec_SPMT_nueCC->SetBinContent(14,568);
   Npe_Elec_SPMT_nueCC->SetBinContent(15,425);
   Npe_Elec_SPMT_nueCC->SetBinContent(16,262);
   Npe_Elec_SPMT_nueCC->SetBinContent(17,185);
   Npe_Elec_SPMT_nueCC->SetBinContent(18,117);
   Npe_Elec_SPMT_nueCC->SetBinContent(19,31);
   Npe_Elec_SPMT_nueCC->SetEntries(8349);
   Npe_Elec_SPMT_nueCC->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   Npe_Elec_SPMT_nueCC->SetLineColor(ci);
   Npe_Elec_SPMT_nueCC->SetLineWidth(3);
   Npe_Elec_SPMT_nueCC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
   Npe_Elec_SPMT_nueCC->GetXaxis()->SetLabelFont(42);
   Npe_Elec_SPMT_nueCC->GetXaxis()->SetLabelSize(0.035);
   Npe_Elec_SPMT_nueCC->GetXaxis()->SetTitleSize(0.035);
   Npe_Elec_SPMT_nueCC->GetXaxis()->SetTitleFont(42);
   Npe_Elec_SPMT_nueCC->GetYaxis()->SetLabelFont(42);
   Npe_Elec_SPMT_nueCC->GetYaxis()->SetLabelSize(0.035);
   Npe_Elec_SPMT_nueCC->GetYaxis()->SetTitleSize(0.035);
   Npe_Elec_SPMT_nueCC->GetYaxis()->SetTitleFont(42);
   Npe_Elec_SPMT_nueCC->GetZaxis()->SetLabelFont(42);
   Npe_Elec_SPMT_nueCC->GetZaxis()->SetLabelSize(0.035);
   Npe_Elec_SPMT_nueCC->GetZaxis()->SetTitleSize(0.035);
   Npe_Elec_SPMT_nueCC->GetZaxis()->SetTitleFont(42);
   Npe_Elec_SPMT_nueCC->Draw("");
   
   TH1F *Npe_Elec_SPMT_numuCC = new TH1F("Npe_Elec_SPMT_numuCC","",20,3,6.2);
   Npe_Elec_SPMT_numuCC->SetBinContent(0,1);
   Npe_Elec_SPMT_numuCC->SetBinContent(2,1);
   Npe_Elec_SPMT_numuCC->SetBinContent(3,2);
   Npe_Elec_SPMT_numuCC->SetBinContent(4,4);
   Npe_Elec_SPMT_numuCC->SetBinContent(7,2);
   Npe_Elec_SPMT_numuCC->SetBinContent(9,11);
   Npe_Elec_SPMT_numuCC->SetBinContent(10,19);
   Npe_Elec_SPMT_numuCC->SetBinContent(11,19);
   Npe_Elec_SPMT_numuCC->SetBinContent(12,17);
   Npe_Elec_SPMT_numuCC->SetBinContent(13,14);
   Npe_Elec_SPMT_numuCC->SetBinContent(14,20);
   Npe_Elec_SPMT_numuCC->SetBinContent(15,30);
   Npe_Elec_SPMT_numuCC->SetBinContent(16,28);
   Npe_Elec_SPMT_numuCC->SetBinContent(17,22);
   Npe_Elec_SPMT_numuCC->SetBinContent(18,27);
   Npe_Elec_SPMT_numuCC->SetBinContent(19,4);
   Npe_Elec_SPMT_numuCC->SetEntries(221);
   Npe_Elec_SPMT_numuCC->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   Npe_Elec_SPMT_numuCC->SetLineColor(ci);
   Npe_Elec_SPMT_numuCC->SetLineWidth(3);
   Npe_Elec_SPMT_numuCC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
   Npe_Elec_SPMT_numuCC->GetXaxis()->SetLabelFont(42);
   Npe_Elec_SPMT_numuCC->GetXaxis()->SetLabelSize(0.035);
   Npe_Elec_SPMT_numuCC->GetXaxis()->SetTitleSize(0.035);
   Npe_Elec_SPMT_numuCC->GetXaxis()->SetTitleFont(42);
   Npe_Elec_SPMT_numuCC->GetYaxis()->SetLabelFont(42);
   Npe_Elec_SPMT_numuCC->GetYaxis()->SetLabelSize(0.035);
   Npe_Elec_SPMT_numuCC->GetYaxis()->SetTitleSize(0.035);
   Npe_Elec_SPMT_numuCC->GetYaxis()->SetTitleFont(42);
   Npe_Elec_SPMT_numuCC->GetZaxis()->SetLabelFont(42);
   Npe_Elec_SPMT_numuCC->GetZaxis()->SetLabelSize(0.035);
   Npe_Elec_SPMT_numuCC->GetZaxis()->SetTitleSize(0.035);
   Npe_Elec_SPMT_numuCC->GetZaxis()->SetTitleFont(42);
   Npe_Elec_SPMT_numuCC->Draw("same");
   
   TH1F *Npe_Elec_SPMT_nuNC = new TH1F("Npe_Elec_SPMT_nuNC","",20,3,6.2);
   Npe_Elec_SPMT_nuNC->SetBinContent(0,1026);
   Npe_Elec_SPMT_nuNC->SetBinContent(1,108);
   Npe_Elec_SPMT_nuNC->SetBinContent(2,38);
   Npe_Elec_SPMT_nuNC->SetBinContent(3,12);
   Npe_Elec_SPMT_nuNC->SetBinContent(4,5);
   Npe_Elec_SPMT_nuNC->SetBinContent(5,2);
   Npe_Elec_SPMT_nuNC->SetBinContent(6,3);
   Npe_Elec_SPMT_nuNC->SetBinContent(7,57);
   Npe_Elec_SPMT_nuNC->SetBinContent(8,330);
   Npe_Elec_SPMT_nuNC->SetBinContent(9,412);
   Npe_Elec_SPMT_nuNC->SetBinContent(10,253);
   Npe_Elec_SPMT_nuNC->SetBinContent(11,209);
   Npe_Elec_SPMT_nuNC->SetBinContent(12,134);
   Npe_Elec_SPMT_nuNC->SetBinContent(13,78);
   Npe_Elec_SPMT_nuNC->SetBinContent(14,96);
   Npe_Elec_SPMT_nuNC->SetBinContent(15,55);
   Npe_Elec_SPMT_nuNC->SetBinContent(16,40);
   Npe_Elec_SPMT_nuNC->SetBinContent(17,20);
   Npe_Elec_SPMT_nuNC->SetBinContent(18,10);
   Npe_Elec_SPMT_nuNC->SetBinContent(19,14);
   Npe_Elec_SPMT_nuNC->SetEntries(2902);
   Npe_Elec_SPMT_nuNC->SetStats(0);

   ci = TColor::GetColor("#33cc00");
   Npe_Elec_SPMT_nuNC->SetLineColor(ci);
   Npe_Elec_SPMT_nuNC->SetLineWidth(3);
   Npe_Elec_SPMT_nuNC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
   Npe_Elec_SPMT_nuNC->GetXaxis()->SetLabelFont(42);
   Npe_Elec_SPMT_nuNC->GetXaxis()->SetLabelSize(0.035);
   Npe_Elec_SPMT_nuNC->GetXaxis()->SetTitleSize(0.035);
   Npe_Elec_SPMT_nuNC->GetXaxis()->SetTitleFont(42);
   Npe_Elec_SPMT_nuNC->GetYaxis()->SetLabelFont(42);
   Npe_Elec_SPMT_nuNC->GetYaxis()->SetLabelSize(0.035);
   Npe_Elec_SPMT_nuNC->GetYaxis()->SetTitleSize(0.035);
   Npe_Elec_SPMT_nuNC->GetYaxis()->SetTitleFont(42);
   Npe_Elec_SPMT_nuNC->GetZaxis()->SetLabelFont(42);
   Npe_Elec_SPMT_nuNC->GetZaxis()->SetLabelSize(0.035);
   Npe_Elec_SPMT_nuNC->GetZaxis()->SetTitleSize(0.035);
   Npe_Elec_SPMT_nuNC->GetZaxis()->SetTitleFont(42);
   Npe_Elec_SPMT_nuNC->Draw("same");
   
   TLegend *leg = new TLegend(0.75,0.7,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Npe_Elec_SPMT_nueCC","#nu_{e} CC","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_Elec_SPMT_numuCC","#nu_{#mu} CC","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_Elec_SPMT_nuNC","#nu_{e}+#nu_{#mu} NC","l");

   ci = TColor::GetColor("#33cc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c16->Modified();
   c16->cd();
   c16->SetSelected(c16);
}
