{
//=========Macro generated from canvas: c26/
//=========  (Mon Nov 12 14:16:20 2018) by ROOT version5.34/36
   TCanvas *c26 = new TCanvas("c26", "",320,52,1600,1028);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c26->Range(2.6,-0.01842686,6.6,4.145242);
   c26->SetFillColor(0);
   c26->SetBorderMode(0);
   c26->SetBorderSize(2);
   c26->SetLogy();
   c26->SetFrameBorderMode(0);
   c26->SetFrameBorderMode(0);
   
   TH1F *Npe_noElec_SPMT_numuCC = new TH1F("Npe_noElec_SPMT_numuCC","",20,3,6.2);
   Npe_noElec_SPMT_numuCC->SetBinContent(0,2);
   Npe_noElec_SPMT_numuCC->SetBinContent(1,5);
   Npe_noElec_SPMT_numuCC->SetBinContent(2,22);
   Npe_noElec_SPMT_numuCC->SetBinContent(3,65);
   Npe_noElec_SPMT_numuCC->SetBinContent(4,256);
   Npe_noElec_SPMT_numuCC->SetBinContent(5,536);
   Npe_noElec_SPMT_numuCC->SetBinContent(6,895);
   Npe_noElec_SPMT_numuCC->SetBinContent(7,1377);
   Npe_noElec_SPMT_numuCC->SetBinContent(8,1952);
   Npe_noElec_SPMT_numuCC->SetBinContent(9,2411);
   Npe_noElec_SPMT_numuCC->SetBinContent(10,2770);
   Npe_noElec_SPMT_numuCC->SetBinContent(11,2827);
   Npe_noElec_SPMT_numuCC->SetBinContent(12,2750);
   Npe_noElec_SPMT_numuCC->SetBinContent(13,2228);
   Npe_noElec_SPMT_numuCC->SetBinContent(14,1834);
   Npe_noElec_SPMT_numuCC->SetBinContent(15,1273);
   Npe_noElec_SPMT_numuCC->SetBinContent(16,769);
   Npe_noElec_SPMT_numuCC->SetBinContent(17,361);
   Npe_noElec_SPMT_numuCC->SetBinContent(18,143);
   Npe_noElec_SPMT_numuCC->SetBinContent(19,16);
   Npe_noElec_SPMT_numuCC->SetEntries(22492);
   Npe_noElec_SPMT_numuCC->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   Npe_noElec_SPMT_numuCC->SetLineColor(ci);
   Npe_noElec_SPMT_numuCC->SetLineWidth(3);
   Npe_noElec_SPMT_numuCC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
   Npe_noElec_SPMT_numuCC->GetXaxis()->SetLabelFont(42);
   Npe_noElec_SPMT_numuCC->GetXaxis()->SetLabelSize(0.035);
   Npe_noElec_SPMT_numuCC->GetXaxis()->SetTitleSize(0.035);
   Npe_noElec_SPMT_numuCC->GetXaxis()->SetTitleFont(42);
   Npe_noElec_SPMT_numuCC->GetYaxis()->SetLabelFont(42);
   Npe_noElec_SPMT_numuCC->GetYaxis()->SetLabelSize(0.035);
   Npe_noElec_SPMT_numuCC->GetYaxis()->SetTitleSize(0.035);
   Npe_noElec_SPMT_numuCC->GetYaxis()->SetTitleFont(42);
   Npe_noElec_SPMT_numuCC->GetZaxis()->SetLabelFont(42);
   Npe_noElec_SPMT_numuCC->GetZaxis()->SetLabelSize(0.035);
   Npe_noElec_SPMT_numuCC->GetZaxis()->SetTitleSize(0.035);
   Npe_noElec_SPMT_numuCC->GetZaxis()->SetTitleFont(42);
   Npe_noElec_SPMT_numuCC->Draw("");
   
   TH1F *Npe_noElec_SPMT_nueCC = new TH1F("Npe_noElec_SPMT_nueCC","",20,3,6.2);
   Npe_noElec_SPMT_nueCC->SetBinContent(1,3);
   Npe_noElec_SPMT_nueCC->SetBinContent(2,2);
   Npe_noElec_SPMT_nueCC->SetBinContent(3,4);
   Npe_noElec_SPMT_nueCC->SetBinContent(4,3);
   Npe_noElec_SPMT_nueCC->SetBinContent(5,9);
   Npe_noElec_SPMT_nueCC->SetBinContent(6,16);
   Npe_noElec_SPMT_nueCC->SetBinContent(7,31);
   Npe_noElec_SPMT_nueCC->SetBinContent(8,71);
   Npe_noElec_SPMT_nueCC->SetBinContent(9,181);
   Npe_noElec_SPMT_nueCC->SetBinContent(10,238);
   Npe_noElec_SPMT_nueCC->SetBinContent(11,261);
   Npe_noElec_SPMT_nueCC->SetBinContent(12,213);
   Npe_noElec_SPMT_nueCC->SetBinContent(13,167);
   Npe_noElec_SPMT_nueCC->SetBinContent(14,107);
   Npe_noElec_SPMT_nueCC->SetBinContent(15,99);
   Npe_noElec_SPMT_nueCC->SetBinContent(16,71);
   Npe_noElec_SPMT_nueCC->SetBinContent(17,46);
   Npe_noElec_SPMT_nueCC->SetBinContent(18,30);
   Npe_noElec_SPMT_nueCC->SetBinContent(19,3);
   Npe_noElec_SPMT_nueCC->SetEntries(1555);
   Npe_noElec_SPMT_nueCC->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Npe_noElec_SPMT_nueCC->SetLineColor(ci);
   Npe_noElec_SPMT_nueCC->SetLineWidth(3);
   Npe_noElec_SPMT_nueCC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
   Npe_noElec_SPMT_nueCC->GetXaxis()->SetLabelFont(42);
   Npe_noElec_SPMT_nueCC->GetXaxis()->SetLabelSize(0.035);
   Npe_noElec_SPMT_nueCC->GetXaxis()->SetTitleSize(0.035);
   Npe_noElec_SPMT_nueCC->GetXaxis()->SetTitleFont(42);
   Npe_noElec_SPMT_nueCC->GetYaxis()->SetLabelFont(42);
   Npe_noElec_SPMT_nueCC->GetYaxis()->SetLabelSize(0.035);
   Npe_noElec_SPMT_nueCC->GetYaxis()->SetTitleSize(0.035);
   Npe_noElec_SPMT_nueCC->GetYaxis()->SetTitleFont(42);
   Npe_noElec_SPMT_nueCC->GetZaxis()->SetLabelFont(42);
   Npe_noElec_SPMT_nueCC->GetZaxis()->SetLabelSize(0.035);
   Npe_noElec_SPMT_nueCC->GetZaxis()->SetTitleSize(0.035);
   Npe_noElec_SPMT_nueCC->GetZaxis()->SetTitleFont(42);
   Npe_noElec_SPMT_nueCC->Draw("same");
   
   TH1F *Npe_noElec_SPMT_nuNC = new TH1F("Npe_noElec_SPMT_nuNC","",20,3,6.2);
   Npe_noElec_SPMT_nuNC->SetBinContent(0,2112);
   Npe_noElec_SPMT_nuNC->SetBinContent(1,820);
   Npe_noElec_SPMT_nuNC->SetBinContent(2,806);
   Npe_noElec_SPMT_nuNC->SetBinContent(3,896);
   Npe_noElec_SPMT_nuNC->SetBinContent(4,1002);
   Npe_noElec_SPMT_nuNC->SetBinContent(5,930);
   Npe_noElec_SPMT_nuNC->SetBinContent(6,816);
   Npe_noElec_SPMT_nuNC->SetBinContent(7,855);
   Npe_noElec_SPMT_nuNC->SetBinContent(8,819);
   Npe_noElec_SPMT_nuNC->SetBinContent(9,646);
   Npe_noElec_SPMT_nuNC->SetBinContent(10,580);
   Npe_noElec_SPMT_nuNC->SetBinContent(11,474);
   Npe_noElec_SPMT_nuNC->SetBinContent(12,367);
   Npe_noElec_SPMT_nuNC->SetBinContent(13,271);
   Npe_noElec_SPMT_nuNC->SetBinContent(14,160);
   Npe_noElec_SPMT_nuNC->SetBinContent(15,112);
   Npe_noElec_SPMT_nuNC->SetBinContent(16,63);
   Npe_noElec_SPMT_nuNC->SetBinContent(17,44);
   Npe_noElec_SPMT_nuNC->SetBinContent(18,18);
   Npe_noElec_SPMT_nuNC->SetBinContent(19,6);
   Npe_noElec_SPMT_nuNC->SetEntries(11797);
   Npe_noElec_SPMT_nuNC->SetStats(0);

   ci = TColor::GetColor("#33cc00");
   Npe_noElec_SPMT_nuNC->SetLineColor(ci);
   Npe_noElec_SPMT_nuNC->SetLineWidth(3);
   Npe_noElec_SPMT_nuNC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
   Npe_noElec_SPMT_nuNC->GetXaxis()->SetLabelFont(42);
   Npe_noElec_SPMT_nuNC->GetXaxis()->SetLabelSize(0.035);
   Npe_noElec_SPMT_nuNC->GetXaxis()->SetTitleSize(0.035);
   Npe_noElec_SPMT_nuNC->GetXaxis()->SetTitleFont(42);
   Npe_noElec_SPMT_nuNC->GetYaxis()->SetLabelFont(42);
   Npe_noElec_SPMT_nuNC->GetYaxis()->SetLabelSize(0.035);
   Npe_noElec_SPMT_nuNC->GetYaxis()->SetTitleSize(0.035);
   Npe_noElec_SPMT_nuNC->GetYaxis()->SetTitleFont(42);
   Npe_noElec_SPMT_nuNC->GetZaxis()->SetLabelFont(42);
   Npe_noElec_SPMT_nuNC->GetZaxis()->SetLabelSize(0.035);
   Npe_noElec_SPMT_nuNC->GetZaxis()->SetTitleSize(0.035);
   Npe_noElec_SPMT_nuNC->GetZaxis()->SetTitleFont(42);
   Npe_noElec_SPMT_nuNC->Draw("same");
   
   TLegend *leg = new TLegend(0.75,0.7,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Npe_noElec_SPMT_numuCC","#nu_{#mu} CC","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_noElec_SPMT_nueCC","#nu_{e} CC","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_noElec_SPMT_nuNC","#nu_{e}+#nu_{#mu} NC","l");

   ci = TColor::GetColor("#33cc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c26->Modified();
   c26->cd();
   c26->SetSelected(c26);
}
