void LOGNPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut()
{
//=========Macro generated from canvas: c7/
//=========  (Thu Aug 29 17:02:14 2019) by ROOT version 6.12/06
   TCanvas *c7 = new TCanvas("c7", "",1120,480,800,600);
   gStyle->SetOptStat(0);
   c7->Range(4.65625,-0.9651293,8.09375,4.569032);
   c7->SetFillColor(0);
   c7->SetBorderMode(0);
   c7->SetBorderSize(2);
   c7->SetLogy();
   c7->SetBottomMargin(0.12);
   c7->SetFrameBorderMode(0);
   c7->SetFrameBorderMode(0);
   
   TH1F *Lognpe_LPMT_nueCC__7 = new TH1F("Lognpe_LPMT_nueCC__7","",35,5,7.75);
   Lognpe_LPMT_nueCC__7->SetBinContent(1,516);
   Lognpe_LPMT_nueCC__7->SetBinContent(2,757);
   Lognpe_LPMT_nueCC__7->SetBinContent(3,1113);
   Lognpe_LPMT_nueCC__7->SetBinContent(4,1485);
   Lognpe_LPMT_nueCC__7->SetBinContent(5,1897);
   Lognpe_LPMT_nueCC__7->SetBinContent(6,2510);
   Lognpe_LPMT_nueCC__7->SetBinContent(7,2978);
   Lognpe_LPMT_nueCC__7->SetBinContent(8,3647);
   Lognpe_LPMT_nueCC__7->SetBinContent(9,4169);
   Lognpe_LPMT_nueCC__7->SetBinContent(10,4754);
   Lognpe_LPMT_nueCC__7->SetBinContent(11,5205);
   Lognpe_LPMT_nueCC__7->SetBinContent(12,5290);
   Lognpe_LPMT_nueCC__7->SetBinContent(13,5471);
   Lognpe_LPMT_nueCC__7->SetBinContent(14,5317);
   Lognpe_LPMT_nueCC__7->SetBinContent(15,5223);
   Lognpe_LPMT_nueCC__7->SetBinContent(16,4933);
   Lognpe_LPMT_nueCC__7->SetBinContent(17,4462);
   Lognpe_LPMT_nueCC__7->SetBinContent(18,4024);
   Lognpe_LPMT_nueCC__7->SetBinContent(19,3466);
   Lognpe_LPMT_nueCC__7->SetBinContent(20,3054);
   Lognpe_LPMT_nueCC__7->SetBinContent(21,2677);
   Lognpe_LPMT_nueCC__7->SetBinContent(22,2224);
   Lognpe_LPMT_nueCC__7->SetBinContent(23,1902);
   Lognpe_LPMT_nueCC__7->SetBinContent(24,1489);
   Lognpe_LPMT_nueCC__7->SetBinContent(25,1188);
   Lognpe_LPMT_nueCC__7->SetBinContent(26,1023);
   Lognpe_LPMT_nueCC__7->SetBinContent(27,856);
   Lognpe_LPMT_nueCC__7->SetBinContent(28,629);
   Lognpe_LPMT_nueCC__7->SetBinContent(29,498);
   Lognpe_LPMT_nueCC__7->SetBinContent(30,402);
   Lognpe_LPMT_nueCC__7->SetBinContent(31,243);
   Lognpe_LPMT_nueCC__7->SetBinContent(32,45);
   Lognpe_LPMT_nueCC__7->SetBinContent(33,1);
   Lognpe_LPMT_nueCC__7->SetEntries(83448);
   Lognpe_LPMT_nueCC__7->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#3399ff");
   Lognpe_LPMT_nueCC__7->SetFillColor(ci);
   Lognpe_LPMT_nueCC__7->SetFillStyle(3002);

   ci = TColor::GetColor("#3399ff");
   Lognpe_LPMT_nueCC__7->SetLineColor(ci);
   Lognpe_LPMT_nueCC__7->SetLineWidth(5);
   Lognpe_LPMT_nueCC__7->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
   Lognpe_LPMT_nueCC__7->GetXaxis()->SetLabelFont(42);
   Lognpe_LPMT_nueCC__7->GetXaxis()->SetLabelSize(0.05);
   Lognpe_LPMT_nueCC__7->GetXaxis()->SetTitleSize(0.05);
   Lognpe_LPMT_nueCC__7->GetXaxis()->SetTitleFont(42);
   Lognpe_LPMT_nueCC__7->GetYaxis()->SetTitle("entries");
   Lognpe_LPMT_nueCC__7->GetYaxis()->SetLabelFont(42);
   Lognpe_LPMT_nueCC__7->GetYaxis()->SetLabelSize(0.05);
   Lognpe_LPMT_nueCC__7->GetYaxis()->SetTitleSize(0.035);
   Lognpe_LPMT_nueCC__7->GetYaxis()->SetTitleOffset(1.2);
   Lognpe_LPMT_nueCC__7->GetYaxis()->SetTitleFont(42);
   Lognpe_LPMT_nueCC__7->GetZaxis()->SetLabelFont(42);
   Lognpe_LPMT_nueCC__7->GetZaxis()->SetLabelSize(0.035);
   Lognpe_LPMT_nueCC__7->GetZaxis()->SetTitleSize(0.035);
   Lognpe_LPMT_nueCC__7->GetZaxis()->SetTitleFont(42);
   Lognpe_LPMT_nueCC__7->Draw("");
   
   TH1F *Lognpe_LPMT_nueCC_cut__8 = new TH1F("Lognpe_LPMT_nueCC_cut__8","",35,5,7.75);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(1,386);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(2,557);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(3,820);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(4,1090);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(5,1428);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(6,1805);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(7,2038);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(8,2374);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(9,2471);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(10,2526);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(11,2547);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(12,2441);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(13,2375);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(14,2287);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(15,2240);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(16,2077);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(17,1814);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(18,1675);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(19,1482);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(20,1315);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(21,1121);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(22,946);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(23,769);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(24,583);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(25,450);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(26,369);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(27,257);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(28,201);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(29,113);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(30,80);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(31,38);
   Lognpe_LPMT_nueCC_cut__8->SetBinContent(32,6);
   Lognpe_LPMT_nueCC_cut__8->SetEntries(40681);
   Lognpe_LPMT_nueCC_cut__8->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Lognpe_LPMT_nueCC_cut__8->SetFillColor(ci);
   Lognpe_LPMT_nueCC_cut__8->SetFillStyle(3002);

   ci = TColor::GetColor("#ff0000");
   Lognpe_LPMT_nueCC_cut__8->SetLineColor(ci);
   Lognpe_LPMT_nueCC_cut__8->SetLineWidth(5);
   Lognpe_LPMT_nueCC_cut__8->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
   Lognpe_LPMT_nueCC_cut__8->GetXaxis()->SetLabelFont(42);
   Lognpe_LPMT_nueCC_cut__8->GetXaxis()->SetLabelSize(0.035);
   Lognpe_LPMT_nueCC_cut__8->GetXaxis()->SetTitleSize(0.035);
   Lognpe_LPMT_nueCC_cut__8->GetXaxis()->SetTitleFont(42);
   Lognpe_LPMT_nueCC_cut__8->GetYaxis()->SetLabelFont(42);
   Lognpe_LPMT_nueCC_cut__8->GetYaxis()->SetLabelSize(0.035);
   Lognpe_LPMT_nueCC_cut__8->GetYaxis()->SetTitleSize(0.035);
   Lognpe_LPMT_nueCC_cut__8->GetYaxis()->SetTitleOffset(0);
   Lognpe_LPMT_nueCC_cut__8->GetYaxis()->SetTitleFont(42);
   Lognpe_LPMT_nueCC_cut__8->GetZaxis()->SetLabelFont(42);
   Lognpe_LPMT_nueCC_cut__8->GetZaxis()->SetLabelSize(0.035);
   Lognpe_LPMT_nueCC_cut__8->GetZaxis()->SetTitleSize(0.035);
   Lognpe_LPMT_nueCC_cut__8->GetZaxis()->SetTitleFont(42);
   Lognpe_LPMT_nueCC_cut__8->Draw("same");
   
   TH1F *Lognpe_LPMT_bkg1__9 = new TH1F("Lognpe_LPMT_bkg1__9","",35,5,7.75);
   Lognpe_LPMT_bkg1__9->SetBinContent(1,7);
   Lognpe_LPMT_bkg1__9->SetBinContent(2,1);
   Lognpe_LPMT_bkg1__9->SetBinContent(3,3);
   Lognpe_LPMT_bkg1__9->SetBinContent(4,4);
   Lognpe_LPMT_bkg1__9->SetBinContent(5,3);
   Lognpe_LPMT_bkg1__9->SetBinContent(6,74);
   Lognpe_LPMT_bkg1__9->SetBinContent(7,276);
   Lognpe_LPMT_bkg1__9->SetBinContent(8,705);
   Lognpe_LPMT_bkg1__9->SetBinContent(9,1036);
   Lognpe_LPMT_bkg1__9->SetBinContent(10,1108);
   Lognpe_LPMT_bkg1__9->SetBinContent(11,801);
   Lognpe_LPMT_bkg1__9->SetBinContent(12,616);
   Lognpe_LPMT_bkg1__9->SetBinContent(13,453);
   Lognpe_LPMT_bkg1__9->SetBinContent(14,410);
   Lognpe_LPMT_bkg1__9->SetBinContent(15,413);
   Lognpe_LPMT_bkg1__9->SetBinContent(16,298);
   Lognpe_LPMT_bkg1__9->SetBinContent(17,201);
   Lognpe_LPMT_bkg1__9->SetBinContent(18,180);
   Lognpe_LPMT_bkg1__9->SetBinContent(19,173);
   Lognpe_LPMT_bkg1__9->SetBinContent(20,129);
   Lognpe_LPMT_bkg1__9->SetBinContent(21,128);
   Lognpe_LPMT_bkg1__9->SetBinContent(22,96);
   Lognpe_LPMT_bkg1__9->SetBinContent(23,66);
   Lognpe_LPMT_bkg1__9->SetBinContent(24,39);
   Lognpe_LPMT_bkg1__9->SetBinContent(25,29);
   Lognpe_LPMT_bkg1__9->SetBinContent(26,13);
   Lognpe_LPMT_bkg1__9->SetBinContent(27,8);
   Lognpe_LPMT_bkg1__9->SetBinContent(28,6);
   Lognpe_LPMT_bkg1__9->SetBinContent(31,1);
   Lognpe_LPMT_bkg1__9->SetEntries(7277);
   Lognpe_LPMT_bkg1__9->SetStats(0);

   ci = TColor::GetColor("#006600");
   Lognpe_LPMT_bkg1__9->SetFillColor(ci);
   Lognpe_LPMT_bkg1__9->SetFillStyle(3002);

   ci = TColor::GetColor("#006600");
   Lognpe_LPMT_bkg1__9->SetLineColor(ci);
   Lognpe_LPMT_bkg1__9->SetLineWidth(5);
   Lognpe_LPMT_bkg1__9->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
   Lognpe_LPMT_bkg1__9->GetXaxis()->SetLabelFont(42);
   Lognpe_LPMT_bkg1__9->GetXaxis()->SetLabelSize(0.035);
   Lognpe_LPMT_bkg1__9->GetXaxis()->SetTitleSize(0.035);
   Lognpe_LPMT_bkg1__9->GetXaxis()->SetTitleFont(42);
   Lognpe_LPMT_bkg1__9->GetYaxis()->SetLabelFont(42);
   Lognpe_LPMT_bkg1__9->GetYaxis()->SetLabelSize(0.035);
   Lognpe_LPMT_bkg1__9->GetYaxis()->SetTitleSize(0.035);
   Lognpe_LPMT_bkg1__9->GetYaxis()->SetTitleOffset(0);
   Lognpe_LPMT_bkg1__9->GetYaxis()->SetTitleFont(42);
   Lognpe_LPMT_bkg1__9->GetZaxis()->SetLabelFont(42);
   Lognpe_LPMT_bkg1__9->GetZaxis()->SetLabelSize(0.035);
   Lognpe_LPMT_bkg1__9->GetZaxis()->SetTitleSize(0.035);
   Lognpe_LPMT_bkg1__9->GetZaxis()->SetTitleFont(42);
   Lognpe_LPMT_bkg1__9->Draw("same");
   
   TLegend *leg = new TLegend(0.7,0.65,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Lognpe_LPMT_nueCC","#nu_{e} CC","l");

   ci = TColor::GetColor("#3399ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Lognpe_LPMT_nueCC_cut","#nu_{e} CC sel.","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Lognpe_LPMT_bkg1","res. bkg","l");

   ci = TColor::GetColor("#006600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c7->Modified();
   c7->cd();
   c7->SetSelected(c7);
}
