{
//=========Macro generated from canvas: c15/
//=========  (Mon Nov 12 14:16:07 2018) by ROOT version5.34/36
   TCanvas *c15 = new TCanvas("c15", "",65,52,1600,1028);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c15->Range(4.675,-0.375,7.925,3.375);
   c15->SetFillColor(0);
   c15->SetBorderMode(0);
   c15->SetBorderSize(2);
   c15->SetLogy();
   c15->SetFrameBorderMode(0);
   c15->SetFrameBorderMode(0);
   
   TH1F *Npe_Elec_LPMT_nueCC = new TH1F("Npe_Elec_LPMT_nueCC","",20,5,7.6);
   Npe_Elec_LPMT_nueCC->SetBinContent(0,126);
   Npe_Elec_LPMT_nueCC->SetBinContent(1,121);
   Npe_Elec_LPMT_nueCC->SetBinContent(2,218);
   Npe_Elec_LPMT_nueCC->SetBinContent(3,390);
   Npe_Elec_LPMT_nueCC->SetBinContent(4,551);
   Npe_Elec_LPMT_nueCC->SetBinContent(5,623);
   Npe_Elec_LPMT_nueCC->SetBinContent(6,736);
   Npe_Elec_LPMT_nueCC->SetBinContent(7,825);
   Npe_Elec_LPMT_nueCC->SetBinContent(8,754);
   Npe_Elec_LPMT_nueCC->SetBinContent(9,825);
   Npe_Elec_LPMT_nueCC->SetBinContent(10,700);
   Npe_Elec_LPMT_nueCC->SetBinContent(11,603);
   Npe_Elec_LPMT_nueCC->SetBinContent(12,522);
   Npe_Elec_LPMT_nueCC->SetBinContent(13,421);
   Npe_Elec_LPMT_nueCC->SetBinContent(14,337);
   Npe_Elec_LPMT_nueCC->SetBinContent(15,224);
   Npe_Elec_LPMT_nueCC->SetBinContent(16,162);
   Npe_Elec_LPMT_nueCC->SetBinContent(17,128);
   Npe_Elec_LPMT_nueCC->SetBinContent(18,66);
   Npe_Elec_LPMT_nueCC->SetBinContent(19,17);
   Npe_Elec_LPMT_nueCC->SetMinimum(1);
   Npe_Elec_LPMT_nueCC->SetMaximum(1000);
   Npe_Elec_LPMT_nueCC->SetEntries(8349);
   Npe_Elec_LPMT_nueCC->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   Npe_Elec_LPMT_nueCC->SetLineColor(ci);
   Npe_Elec_LPMT_nueCC->SetLineWidth(3);
   Npe_Elec_LPMT_nueCC->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
   Npe_Elec_LPMT_nueCC->GetXaxis()->SetLabelFont(42);
   Npe_Elec_LPMT_nueCC->GetXaxis()->SetLabelSize(0.035);
   Npe_Elec_LPMT_nueCC->GetXaxis()->SetTitleSize(0.035);
   Npe_Elec_LPMT_nueCC->GetXaxis()->SetTitleFont(42);
   Npe_Elec_LPMT_nueCC->GetYaxis()->SetLabelFont(42);
   Npe_Elec_LPMT_nueCC->GetYaxis()->SetLabelSize(0.035);
   Npe_Elec_LPMT_nueCC->GetYaxis()->SetTitleSize(0.035);
   Npe_Elec_LPMT_nueCC->GetYaxis()->SetTitleFont(42);
   Npe_Elec_LPMT_nueCC->GetZaxis()->SetLabelFont(42);
   Npe_Elec_LPMT_nueCC->GetZaxis()->SetLabelSize(0.035);
   Npe_Elec_LPMT_nueCC->GetZaxis()->SetTitleSize(0.035);
   Npe_Elec_LPMT_nueCC->GetZaxis()->SetTitleFont(42);
   Npe_Elec_LPMT_nueCC->Draw("");
   
   TH1F *Npe_Elec_LPMT_numuCC = new TH1F("Npe_Elec_LPMT_numuCC","",20,5,7.6);
   Npe_Elec_LPMT_numuCC->SetBinContent(0,5);
   Npe_Elec_LPMT_numuCC->SetBinContent(1,3);
   Npe_Elec_LPMT_numuCC->SetBinContent(4,1);
   Npe_Elec_LPMT_numuCC->SetBinContent(5,1);
   Npe_Elec_LPMT_numuCC->SetBinContent(6,7);
   Npe_Elec_LPMT_numuCC->SetBinContent(7,11);
   Npe_Elec_LPMT_numuCC->SetBinContent(8,12);
   Npe_Elec_LPMT_numuCC->SetBinContent(9,18);
   Npe_Elec_LPMT_numuCC->SetBinContent(10,14);
   Npe_Elec_LPMT_numuCC->SetBinContent(11,12);
   Npe_Elec_LPMT_numuCC->SetBinContent(12,15);
   Npe_Elec_LPMT_numuCC->SetBinContent(13,15);
   Npe_Elec_LPMT_numuCC->SetBinContent(14,23);
   Npe_Elec_LPMT_numuCC->SetBinContent(15,27);
   Npe_Elec_LPMT_numuCC->SetBinContent(16,18);
   Npe_Elec_LPMT_numuCC->SetBinContent(17,23);
   Npe_Elec_LPMT_numuCC->SetBinContent(18,13);
   Npe_Elec_LPMT_numuCC->SetBinContent(19,3);
   Npe_Elec_LPMT_numuCC->SetEntries(221);
   Npe_Elec_LPMT_numuCC->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   Npe_Elec_LPMT_numuCC->SetLineColor(ci);
   Npe_Elec_LPMT_numuCC->SetLineWidth(3);
   Npe_Elec_LPMT_numuCC->GetXaxis()->SetTitle("log_{10}(NPE_ELEC_{LPMT})");
   Npe_Elec_LPMT_numuCC->GetXaxis()->SetLabelFont(42);
   Npe_Elec_LPMT_numuCC->GetXaxis()->SetLabelSize(0.035);
   Npe_Elec_LPMT_numuCC->GetXaxis()->SetTitleSize(0.035);
   Npe_Elec_LPMT_numuCC->GetXaxis()->SetTitleFont(42);
   Npe_Elec_LPMT_numuCC->GetYaxis()->SetLabelFont(42);
   Npe_Elec_LPMT_numuCC->GetYaxis()->SetLabelSize(0.035);
   Npe_Elec_LPMT_numuCC->GetYaxis()->SetTitleSize(0.035);
   Npe_Elec_LPMT_numuCC->GetYaxis()->SetTitleFont(42);
   Npe_Elec_LPMT_numuCC->GetZaxis()->SetLabelFont(42);
   Npe_Elec_LPMT_numuCC->GetZaxis()->SetLabelSize(0.035);
   Npe_Elec_LPMT_numuCC->GetZaxis()->SetTitleSize(0.035);
   Npe_Elec_LPMT_numuCC->GetZaxis()->SetTitleFont(42);
   Npe_Elec_LPMT_numuCC->Draw("same");
   
   TH1F *Npe_Elec_LPMT_nuNC = new TH1F("Npe_Elec_LPMT_nuNC","",20,5,7.6);
   Npe_Elec_LPMT_nuNC->SetBinContent(0,1188);
   Npe_Elec_LPMT_nuNC->SetBinContent(1,2);
   Npe_Elec_LPMT_nuNC->SetBinContent(2,1);
   Npe_Elec_LPMT_nuNC->SetBinContent(3,3);
   Npe_Elec_LPMT_nuNC->SetBinContent(4,40);
   Npe_Elec_LPMT_nuNC->SetBinContent(5,211);
   Npe_Elec_LPMT_nuNC->SetBinContent(6,361);
   Npe_Elec_LPMT_nuNC->SetBinContent(7,269);
   Npe_Elec_LPMT_nuNC->SetBinContent(8,203);
   Npe_Elec_LPMT_nuNC->SetBinContent(9,169);
   Npe_Elec_LPMT_nuNC->SetBinContent(10,123);
   Npe_Elec_LPMT_nuNC->SetBinContent(11,65);
   Npe_Elec_LPMT_nuNC->SetBinContent(12,71);
   Npe_Elec_LPMT_nuNC->SetBinContent(13,73);
   Npe_Elec_LPMT_nuNC->SetBinContent(14,38);
   Npe_Elec_LPMT_nuNC->SetBinContent(15,30);
   Npe_Elec_LPMT_nuNC->SetBinContent(16,25);
   Npe_Elec_LPMT_nuNC->SetBinContent(17,11);
   Npe_Elec_LPMT_nuNC->SetBinContent(18,8);
   Npe_Elec_LPMT_nuNC->SetBinContent(19,11);
   Npe_Elec_LPMT_nuNC->SetEntries(2902);
   Npe_Elec_LPMT_nuNC->SetStats(0);

   ci = TColor::GetColor("#33cc00");
   Npe_Elec_LPMT_nuNC->SetLineColor(ci);
   Npe_Elec_LPMT_nuNC->SetLineWidth(3);
   Npe_Elec_LPMT_nuNC->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
   Npe_Elec_LPMT_nuNC->GetXaxis()->SetLabelFont(42);
   Npe_Elec_LPMT_nuNC->GetXaxis()->SetLabelSize(0.035);
   Npe_Elec_LPMT_nuNC->GetXaxis()->SetTitleSize(0.035);
   Npe_Elec_LPMT_nuNC->GetXaxis()->SetTitleFont(42);
   Npe_Elec_LPMT_nuNC->GetYaxis()->SetLabelFont(42);
   Npe_Elec_LPMT_nuNC->GetYaxis()->SetLabelSize(0.035);
   Npe_Elec_LPMT_nuNC->GetYaxis()->SetTitleSize(0.035);
   Npe_Elec_LPMT_nuNC->GetYaxis()->SetTitleFont(42);
   Npe_Elec_LPMT_nuNC->GetZaxis()->SetLabelFont(42);
   Npe_Elec_LPMT_nuNC->GetZaxis()->SetLabelSize(0.035);
   Npe_Elec_LPMT_nuNC->GetZaxis()->SetTitleSize(0.035);
   Npe_Elec_LPMT_nuNC->GetZaxis()->SetTitleFont(42);
   Npe_Elec_LPMT_nuNC->Draw("same");
   
   TLegend *leg = new TLegend(0.75,0.7,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Npe_Elec_LPMT_numuCC","#nu_{#mu} CC","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_Elec_LPMT_nueCC","#nu_{e} CC","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_Elec_LPMT_nuNC","#nu_{e}+#nu_{#mu} NC","l");

   ci = TColor::GetColor("#33cc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c15->Modified();
   c15->cd();
   c15->SetSelected(c15);
}
