void NPE_LPMT_nuecuts_bins()
{
//=========Macro generated from canvas: cnue/
//=========  (Mon Oct 28 16:52:21 2019) by ROOT version 6.12/06
   TCanvas *cnue = new TCanvas("cnue", "",65,480,800,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cnue->Range(4.783815,-23.07692,7.327167,169.2308);
   cnue->SetFillColor(0);
   cnue->SetBorderMode(0);
   cnue->SetBorderSize(2);
   cnue->SetLeftMargin(0.085);
   cnue->SetRightMargin(0.05);
   cnue->SetBottomMargin(0.12);
   cnue->SetFrameBorderMode(0);
   cnue->SetFrameBorderMode(0);
   
   TH1F *Npe_LPMT_allcuts__1 = new TH1F("Npe_LPMT_allcuts__1","Inclusive NPE spectrum after all cuts",7,5,7.2);
   Npe_LPMT_allcuts__1->SetBinContent(1,38.35162);
   Npe_LPMT_allcuts__1->SetBinContent(2,112.0304);
   Npe_LPMT_allcuts__1->SetBinContent(3,134.5877);
   Npe_LPMT_allcuts__1->SetBinContent(4,136.8444);
   Npe_LPMT_allcuts__1->SetBinContent(5,89.99854);
   Npe_LPMT_allcuts__1->SetBinContent(6,44.89458);
   Npe_LPMT_allcuts__1->SetBinContent(7,18.027);
   Npe_LPMT_allcuts__1->SetBinContent(8,1.900057);
   Npe_LPMT_allcuts__1->SetBinError(1,6.067918);
   Npe_LPMT_allcuts__1->SetBinError(2,10.29348);
   Npe_LPMT_allcuts__1->SetBinError(3,11.14061);
   Npe_LPMT_allcuts__1->SetBinError(4,11.3389);
   Npe_LPMT_allcuts__1->SetBinError(5,9.207027);
   Npe_LPMT_allcuts__1->SetBinError(6,6.501201);
   Npe_LPMT_allcuts__1->SetBinError(7,4.141494);
   Npe_LPMT_allcuts__1->SetBinError(8,1.264505);
   Npe_LPMT_allcuts__1->SetMinimum(0);
   Npe_LPMT_allcuts__1->SetMaximum(150);
   Npe_LPMT_allcuts__1->SetEntries(643);
   Npe_LPMT_allcuts__1->SetLineWidth(4);
   Npe_LPMT_allcuts__1->SetMarkerStyle(20);
   Npe_LPMT_allcuts__1->SetMarkerSize(1.7);
   Npe_LPMT_allcuts__1->GetXaxis()->SetTitle("log_{10}(NPE)");
   Npe_LPMT_allcuts__1->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_allcuts__1->GetXaxis()->SetLabelSize(0.045);
   Npe_LPMT_allcuts__1->GetXaxis()->SetTitleSize(0.05);
   Npe_LPMT_allcuts__1->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_allcuts__1->GetYaxis()->SetTitle("entries");
   Npe_LPMT_allcuts__1->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_allcuts__1->GetYaxis()->SetLabelSize(0.045);
   Npe_LPMT_allcuts__1->GetYaxis()->SetTitleSize(0.045);
   Npe_LPMT_allcuts__1->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_allcuts__1->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_allcuts__1->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_allcuts__1->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_allcuts__1->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_allcuts__1->Draw("");
   
   TH1F *Npe_LPMT_sgn_allcuts__2 = new TH1F("Npe_LPMT_sgn_allcuts__2","Exclusive flavor NPE spectrum after all cuts",7,5,7.2);
   Npe_LPMT_sgn_allcuts__2->SetBinContent(1,38.35162);
   Npe_LPMT_sgn_allcuts__2->SetBinContent(2,106.6554);
   Npe_LPMT_sgn_allcuts__2->SetBinContent(3,122.2328);
   Npe_LPMT_sgn_allcuts__2->SetBinContent(4,129.066);
   Npe_LPMT_sgn_allcuts__2->SetBinContent(5,84.74953);
   Npe_LPMT_sgn_allcuts__2->SetBinContent(6,44.42004);
   Npe_LPMT_sgn_allcuts__2->SetBinContent(7,18.027);
   Npe_LPMT_sgn_allcuts__2->SetBinContent(8,1.769606);
   Npe_LPMT_sgn_allcuts__2->SetBinError(1,6.067918);
   Npe_LPMT_sgn_allcuts__2->SetBinError(2,10.08433);
   Npe_LPMT_sgn_allcuts__2->SetBinError(3,10.76848);
   Npe_LPMT_sgn_allcuts__2->SetBinError(4,11.07473);
   Npe_LPMT_sgn_allcuts__2->SetBinError(5,8.989592);
   Npe_LPMT_sgn_allcuts__2->SetBinError(6,6.483859);
   Npe_LPMT_sgn_allcuts__2->SetBinError(7,4.141494);
   Npe_LPMT_sgn_allcuts__2->SetBinError(8,1.257758);
   Npe_LPMT_sgn_allcuts__2->SetEntries(574);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ccccff");
   Npe_LPMT_sgn_allcuts__2->SetFillColor(ci);
   Npe_LPMT_sgn_allcuts__2->SetFillStyle(3000);

   ci = TColor::GetColor("#ccccff");
   Npe_LPMT_sgn_allcuts__2->SetLineColor(ci);
   Npe_LPMT_sgn_allcuts__2->SetLineWidth(4);
   Npe_LPMT_sgn_allcuts__2->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
   Npe_LPMT_sgn_allcuts__2->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_sgn_allcuts__2->GetXaxis()->SetLabelSize(0.035);
   Npe_LPMT_sgn_allcuts__2->GetXaxis()->SetTitleSize(0.035);
   Npe_LPMT_sgn_allcuts__2->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_sgn_allcuts__2->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_sgn_allcuts__2->GetYaxis()->SetLabelSize(0.035);
   Npe_LPMT_sgn_allcuts__2->GetYaxis()->SetTitleSize(0.035);
   Npe_LPMT_sgn_allcuts__2->GetYaxis()->SetTitleOffset(0);
   Npe_LPMT_sgn_allcuts__2->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_sgn_allcuts__2->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_sgn_allcuts__2->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_sgn_allcuts__2->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_sgn_allcuts__2->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_sgn_allcuts__2->Draw("SAME HISTO");
   
   TH1F *Npe_LPMT_bkg_allcuts__3 = new TH1F("Npe_LPMT_bkg_allcuts__3","Background NPE spectrum after all cuts",7,5,7.2);
   Npe_LPMT_bkg_allcuts__3->SetBinContent(2,5.375048);
   Npe_LPMT_bkg_allcuts__3->SetBinContent(3,12.35488);
   Npe_LPMT_bkg_allcuts__3->SetBinContent(4,7.778415);
   Npe_LPMT_bkg_allcuts__3->SetBinContent(5,5.249008);
   Npe_LPMT_bkg_allcuts__3->SetBinContent(6,0.4745358);
   Npe_LPMT_bkg_allcuts__3->SetBinContent(8,0.1304509);
   Npe_LPMT_bkg_allcuts__3->SetBinError(2,2.064487);
   Npe_LPMT_bkg_allcuts__3->SetBinError(3,2.855344);
   Npe_LPMT_bkg_allcuts__3->SetBinError(4,2.433343);
   Npe_LPMT_bkg_allcuts__3->SetBinError(5,1.989117);
   Npe_LPMT_bkg_allcuts__3->SetBinError(6,0.4745358);
   Npe_LPMT_bkg_allcuts__3->SetBinError(8,0.1304509);
   Npe_LPMT_bkg_allcuts__3->SetEntries(69);

   ci = TColor::GetColor("#006600");
   Npe_LPMT_bkg_allcuts__3->SetFillColor(ci);
   Npe_LPMT_bkg_allcuts__3->SetFillStyle(3000);

   ci = TColor::GetColor("#006600");
   Npe_LPMT_bkg_allcuts__3->SetLineColor(ci);
   Npe_LPMT_bkg_allcuts__3->SetLineWidth(4);
   Npe_LPMT_bkg_allcuts__3->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
   Npe_LPMT_bkg_allcuts__3->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_bkg_allcuts__3->GetXaxis()->SetLabelSize(0.035);
   Npe_LPMT_bkg_allcuts__3->GetXaxis()->SetTitleSize(0.035);
   Npe_LPMT_bkg_allcuts__3->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_bkg_allcuts__3->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_bkg_allcuts__3->GetYaxis()->SetLabelSize(0.035);
   Npe_LPMT_bkg_allcuts__3->GetYaxis()->SetTitleSize(0.035);
   Npe_LPMT_bkg_allcuts__3->GetYaxis()->SetTitleOffset(0);
   Npe_LPMT_bkg_allcuts__3->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_bkg_allcuts__3->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_bkg_allcuts__3->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_bkg_allcuts__3->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_bkg_allcuts__3->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_bkg_allcuts__3->Draw("SAME HISTO");
   
   TH1F *Npe_LPMT_allcuts__4 = new TH1F("Npe_LPMT_allcuts__4","Inclusive NPE spectrum after all cuts",7,5,7.2);
   Npe_LPMT_allcuts__4->SetBinContent(1,38.35162);
   Npe_LPMT_allcuts__4->SetBinContent(2,112.0304);
   Npe_LPMT_allcuts__4->SetBinContent(3,134.5877);
   Npe_LPMT_allcuts__4->SetBinContent(4,136.8444);
   Npe_LPMT_allcuts__4->SetBinContent(5,89.99854);
   Npe_LPMT_allcuts__4->SetBinContent(6,44.89458);
   Npe_LPMT_allcuts__4->SetBinContent(7,18.027);
   Npe_LPMT_allcuts__4->SetBinContent(8,1.900057);
   Npe_LPMT_allcuts__4->SetBinError(1,6.067918);
   Npe_LPMT_allcuts__4->SetBinError(2,10.29348);
   Npe_LPMT_allcuts__4->SetBinError(3,11.14061);
   Npe_LPMT_allcuts__4->SetBinError(4,11.3389);
   Npe_LPMT_allcuts__4->SetBinError(5,9.207027);
   Npe_LPMT_allcuts__4->SetBinError(6,6.501201);
   Npe_LPMT_allcuts__4->SetBinError(7,4.141494);
   Npe_LPMT_allcuts__4->SetBinError(8,1.264505);
   Npe_LPMT_allcuts__4->SetMinimum(0);
   Npe_LPMT_allcuts__4->SetMaximum(150);
   Npe_LPMT_allcuts__4->SetEntries(643);
   Npe_LPMT_allcuts__4->SetLineWidth(4);
   Npe_LPMT_allcuts__4->SetMarkerStyle(20);
   Npe_LPMT_allcuts__4->SetMarkerSize(1.7);
   Npe_LPMT_allcuts__4->GetXaxis()->SetTitle("log_{10}(NPE)");
   Npe_LPMT_allcuts__4->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_allcuts__4->GetXaxis()->SetLabelSize(0.045);
   Npe_LPMT_allcuts__4->GetXaxis()->SetTitleSize(0.05);
   Npe_LPMT_allcuts__4->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_allcuts__4->GetYaxis()->SetTitle("entries");
   Npe_LPMT_allcuts__4->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_allcuts__4->GetYaxis()->SetLabelSize(0.045);
   Npe_LPMT_allcuts__4->GetYaxis()->SetTitleSize(0.045);
   Npe_LPMT_allcuts__4->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_allcuts__4->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_allcuts__4->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_allcuts__4->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_allcuts__4->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_allcuts__4->Draw("same");
   
   TLegend *leg = new TLegend(0.75,0.63,0.94,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Npe_LPMT_allcuts","#nu_{e} sel.","ple");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.7);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_LPMT_sgn_allcuts","#nu_{e}","f");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3000);

   ci = TColor::GetColor("#ccccff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_LPMT_bkg_allcuts","#nu_{#mu}","f");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3000);

   ci = TColor::GetColor("#006600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1F *Npe_LPMT_allcuts_copy__5 = new TH1F("Npe_LPMT_allcuts_copy__5","Inclusive NPE spectrum after all cuts",7,5,7.2);
   Npe_LPMT_allcuts_copy__5->SetBinContent(1,38.35162);
   Npe_LPMT_allcuts_copy__5->SetBinContent(2,112.0304);
   Npe_LPMT_allcuts_copy__5->SetBinContent(3,134.5877);
   Npe_LPMT_allcuts_copy__5->SetBinContent(4,136.8444);
   Npe_LPMT_allcuts_copy__5->SetBinContent(5,89.99854);
   Npe_LPMT_allcuts_copy__5->SetBinContent(6,44.89458);
   Npe_LPMT_allcuts_copy__5->SetBinContent(7,18.027);
   Npe_LPMT_allcuts_copy__5->SetBinContent(8,1.900057);
   Npe_LPMT_allcuts_copy__5->SetBinError(1,6.067918);
   Npe_LPMT_allcuts_copy__5->SetBinError(2,10.29348);
   Npe_LPMT_allcuts_copy__5->SetBinError(3,11.14061);
   Npe_LPMT_allcuts_copy__5->SetBinError(4,11.3389);
   Npe_LPMT_allcuts_copy__5->SetBinError(5,9.207027);
   Npe_LPMT_allcuts_copy__5->SetBinError(6,6.501201);
   Npe_LPMT_allcuts_copy__5->SetBinError(7,4.141494);
   Npe_LPMT_allcuts_copy__5->SetBinError(8,1.264505);
   Npe_LPMT_allcuts_copy__5->SetMinimum(0);
   Npe_LPMT_allcuts_copy__5->SetMaximum(150);
   Npe_LPMT_allcuts_copy__5->SetEntries(643);
   Npe_LPMT_allcuts_copy__5->SetDirectory(0);
   Npe_LPMT_allcuts_copy__5->SetLineWidth(4);
   Npe_LPMT_allcuts_copy__5->SetMarkerStyle(20);
   Npe_LPMT_allcuts_copy__5->SetMarkerSize(1.7);
   Npe_LPMT_allcuts_copy__5->GetXaxis()->SetTitle("log_{10}(NPE)");
   Npe_LPMT_allcuts_copy__5->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_allcuts_copy__5->GetXaxis()->SetLabelSize(0.045);
   Npe_LPMT_allcuts_copy__5->GetXaxis()->SetTitleSize(0.05);
   Npe_LPMT_allcuts_copy__5->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_allcuts_copy__5->GetYaxis()->SetTitle("entries");
   Npe_LPMT_allcuts_copy__5->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_allcuts_copy__5->GetYaxis()->SetLabelSize(0.045);
   Npe_LPMT_allcuts_copy__5->GetYaxis()->SetTitleSize(0.045);
   Npe_LPMT_allcuts_copy__5->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_allcuts_copy__5->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_allcuts_copy__5->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_allcuts_copy__5->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_allcuts_copy__5->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_allcuts_copy__5->Draw("sameaxis");
   cnue->Modified();
   cnue->cd();
   cnue->SetSelected(cnue);
}
