void NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut()
{
//=========Macro generated from canvas: c15/
//=========  (Thu Aug 29 17:02:11 2019) by ROOT version 6.12/06
   TCanvas *c15 = new TCanvas("c15", "",65,52,800,600);
   gStyle->SetOptStat(0);
   c15->Range(-3750000,-1.086577,3.375e+07,5.459646);
   c15->SetFillColor(0);
   c15->SetBorderMode(0);
   c15->SetBorderSize(2);
   c15->SetLogy();
   c15->SetBottomMargin(0.12);
   c15->SetFrameBorderMode(0);
   c15->SetFrameBorderMode(0);
   
   TH1F *Npe_LPMT_nueCC__1 = new TH1F("Npe_LPMT_nueCC__1","",35,0,3e+07);
   Npe_LPMT_nueCC__1->SetBinContent(1,33688);
   Npe_LPMT_nueCC__1->SetBinContent(2,20165);
   Npe_LPMT_nueCC__1->SetBinContent(3,9719);
   Npe_LPMT_nueCC__1->SetBinContent(4,5360);
   Npe_LPMT_nueCC__1->SetBinContent(5,3461);
   Npe_LPMT_nueCC__1->SetBinContent(6,2315);
   Npe_LPMT_nueCC__1->SetBinContent(7,1688);
   Npe_LPMT_nueCC__1->SetBinContent(8,1250);
   Npe_LPMT_nueCC__1->SetBinContent(9,944);
   Npe_LPMT_nueCC__1->SetBinContent(10,742);
   Npe_LPMT_nueCC__1->SetBinContent(11,559);
   Npe_LPMT_nueCC__1->SetBinContent(12,519);
   Npe_LPMT_nueCC__1->SetBinContent(13,406);
   Npe_LPMT_nueCC__1->SetBinContent(14,371);
   Npe_LPMT_nueCC__1->SetBinContent(15,303);
   Npe_LPMT_nueCC__1->SetBinContent(16,281);
   Npe_LPMT_nueCC__1->SetBinContent(17,209);
   Npe_LPMT_nueCC__1->SetBinContent(18,193);
   Npe_LPMT_nueCC__1->SetBinContent(19,177);
   Npe_LPMT_nueCC__1->SetBinContent(20,129);
   Npe_LPMT_nueCC__1->SetBinContent(21,142);
   Npe_LPMT_nueCC__1->SetBinContent(22,121);
   Npe_LPMT_nueCC__1->SetBinContent(23,107);
   Npe_LPMT_nueCC__1->SetBinContent(24,88);
   Npe_LPMT_nueCC__1->SetBinContent(25,95);
   Npe_LPMT_nueCC__1->SetBinContent(26,82);
   Npe_LPMT_nueCC__1->SetBinContent(27,71);
   Npe_LPMT_nueCC__1->SetBinContent(28,58);
   Npe_LPMT_nueCC__1->SetBinContent(29,47);
   Npe_LPMT_nueCC__1->SetBinContent(30,55);
   Npe_LPMT_nueCC__1->SetBinContent(31,34);
   Npe_LPMT_nueCC__1->SetBinContent(32,27);
   Npe_LPMT_nueCC__1->SetBinContent(33,26);
   Npe_LPMT_nueCC__1->SetBinContent(34,8);
   Npe_LPMT_nueCC__1->SetBinContent(35,1);
   Npe_LPMT_nueCC__1->SetBinContent(36,7);
   Npe_LPMT_nueCC__1->SetEntries(83448);
   Npe_LPMT_nueCC__1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#3399ff");
   Npe_LPMT_nueCC__1->SetFillColor(ci);
   Npe_LPMT_nueCC__1->SetFillStyle(3002);

   ci = TColor::GetColor("#3399ff");
   Npe_LPMT_nueCC__1->SetLineColor(ci);
   Npe_LPMT_nueCC__1->SetLineWidth(5);
   Npe_LPMT_nueCC__1->GetXaxis()->SetTitle("NPE_{LPMT}");
   Npe_LPMT_nueCC__1->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC__1->GetXaxis()->SetLabelSize(0.05);
   Npe_LPMT_nueCC__1->GetXaxis()->SetTitleSize(0.05);
   Npe_LPMT_nueCC__1->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC__1->GetYaxis()->SetTitle("entries");
   Npe_LPMT_nueCC__1->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC__1->GetYaxis()->SetLabelSize(0.05);
   Npe_LPMT_nueCC__1->GetYaxis()->SetTitleSize(0.035);
   Npe_LPMT_nueCC__1->GetYaxis()->SetTitleOffset(1.2);
   Npe_LPMT_nueCC__1->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC__1->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC__1->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_nueCC__1->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_nueCC__1->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC__1->Draw("");
   
   TH1F *Npe_LPMT_nueCC_cut__2 = new TH1F("Npe_LPMT_nueCC_cut__2","",35,0,3e+07);
   Npe_LPMT_nueCC_cut__2->SetBinContent(1,20199);
   Npe_LPMT_nueCC_cut__2->SetBinContent(2,8692);
   Npe_LPMT_nueCC_cut__2->SetBinContent(3,3986);
   Npe_LPMT_nueCC_cut__2->SetBinContent(4,2291);
   Npe_LPMT_nueCC_cut__2->SetBinContent(5,1466);
   Npe_LPMT_nueCC_cut__2->SetBinContent(6,986);
   Npe_LPMT_nueCC_cut__2->SetBinContent(7,678);
   Npe_LPMT_nueCC_cut__2->SetBinContent(8,516);
   Npe_LPMT_nueCC_cut__2->SetBinContent(9,366);
   Npe_LPMT_nueCC_cut__2->SetBinContent(10,269);
   Npe_LPMT_nueCC_cut__2->SetBinContent(11,225);
   Npe_LPMT_nueCC_cut__2->SetBinContent(12,195);
   Npe_LPMT_nueCC_cut__2->SetBinContent(13,127);
   Npe_LPMT_nueCC_cut__2->SetBinContent(14,105);
   Npe_LPMT_nueCC_cut__2->SetBinContent(15,107);
   Npe_LPMT_nueCC_cut__2->SetBinContent(16,80);
   Npe_LPMT_nueCC_cut__2->SetBinContent(17,68);
   Npe_LPMT_nueCC_cut__2->SetBinContent(18,65);
   Npe_LPMT_nueCC_cut__2->SetBinContent(19,44);
   Npe_LPMT_nueCC_cut__2->SetBinContent(20,30);
   Npe_LPMT_nueCC_cut__2->SetBinContent(21,31);
   Npe_LPMT_nueCC_cut__2->SetBinContent(22,25);
   Npe_LPMT_nueCC_cut__2->SetBinContent(23,26);
   Npe_LPMT_nueCC_cut__2->SetBinContent(24,17);
   Npe_LPMT_nueCC_cut__2->SetBinContent(25,25);
   Npe_LPMT_nueCC_cut__2->SetBinContent(26,10);
   Npe_LPMT_nueCC_cut__2->SetBinContent(27,11);
   Npe_LPMT_nueCC_cut__2->SetBinContent(28,10);
   Npe_LPMT_nueCC_cut__2->SetBinContent(29,6);
   Npe_LPMT_nueCC_cut__2->SetBinContent(30,7);
   Npe_LPMT_nueCC_cut__2->SetBinContent(31,9);
   Npe_LPMT_nueCC_cut__2->SetBinContent(32,3);
   Npe_LPMT_nueCC_cut__2->SetBinContent(33,6);
   Npe_LPMT_nueCC_cut__2->SetEntries(40681);
   Npe_LPMT_nueCC_cut__2->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Npe_LPMT_nueCC_cut__2->SetFillColor(ci);
   Npe_LPMT_nueCC_cut__2->SetFillStyle(3002);

   ci = TColor::GetColor("#ff0000");
   Npe_LPMT_nueCC_cut__2->SetLineColor(ci);
   Npe_LPMT_nueCC_cut__2->SetLineWidth(5);
   Npe_LPMT_nueCC_cut__2->GetXaxis()->SetTitle("NPE_{LPMT}");
   Npe_LPMT_nueCC_cut__2->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC_cut__2->GetXaxis()->SetLabelSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetXaxis()->SetTitleSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC_cut__2->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC_cut__2->GetYaxis()->SetLabelSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetYaxis()->SetTitleSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetYaxis()->SetTitleOffset(0);
   Npe_LPMT_nueCC_cut__2->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC_cut__2->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC_cut__2->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC_cut__2->Draw("same");
   
   TH1F *Npe_LPMT_bkg1__3 = new TH1F("Npe_LPMT_bkg1__3","",35,0,3e+07);
   Npe_LPMT_bkg1__3->SetBinContent(1,4563);
   Npe_LPMT_bkg1__3->SetBinContent(2,1545);
   Npe_LPMT_bkg1__3->SetBinContent(3,473);
   Npe_LPMT_bkg1__3->SetBinContent(4,253);
   Npe_LPMT_bkg1__3->SetBinContent(5,161);
   Npe_LPMT_bkg1__3->SetBinContent(6,103);
   Npe_LPMT_bkg1__3->SetBinContent(7,65);
   Npe_LPMT_bkg1__3->SetBinContent(8,34);
   Npe_LPMT_bkg1__3->SetBinContent(9,24);
   Npe_LPMT_bkg1__3->SetBinContent(10,16);
   Npe_LPMT_bkg1__3->SetBinContent(11,14);
   Npe_LPMT_bkg1__3->SetBinContent(12,6);
   Npe_LPMT_bkg1__3->SetBinContent(13,5);
   Npe_LPMT_bkg1__3->SetBinContent(14,1);
   Npe_LPMT_bkg1__3->SetBinContent(15,6);
   Npe_LPMT_bkg1__3->SetBinContent(16,1);
   Npe_LPMT_bkg1__3->SetBinContent(17,2);
   Npe_LPMT_bkg1__3->SetBinContent(18,3);
   Npe_LPMT_bkg1__3->SetBinContent(19,1);
   Npe_LPMT_bkg1__3->SetBinContent(27,1);
   Npe_LPMT_bkg1__3->SetEntries(7277);
   Npe_LPMT_bkg1__3->SetStats(0);

   ci = TColor::GetColor("#006600");
   Npe_LPMT_bkg1__3->SetFillColor(ci);
   Npe_LPMT_bkg1__3->SetFillStyle(3002);

   ci = TColor::GetColor("#006600");
   Npe_LPMT_bkg1__3->SetLineColor(ci);
   Npe_LPMT_bkg1__3->SetLineWidth(5);
   Npe_LPMT_bkg1__3->GetXaxis()->SetTitle("NPE_{LPMT}");
   Npe_LPMT_bkg1__3->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_bkg1__3->GetXaxis()->SetLabelSize(0.035);
   Npe_LPMT_bkg1__3->GetXaxis()->SetTitleSize(0.035);
   Npe_LPMT_bkg1__3->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_bkg1__3->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_bkg1__3->GetYaxis()->SetLabelSize(0.035);
   Npe_LPMT_bkg1__3->GetYaxis()->SetTitleSize(0.035);
   Npe_LPMT_bkg1__3->GetYaxis()->SetTitleOffset(0);
   Npe_LPMT_bkg1__3->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_bkg1__3->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_bkg1__3->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_bkg1__3->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_bkg1__3->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_bkg1__3->Draw("same");
   
   TLegend *leg = new TLegend(0.65,0.6,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Npe_LPMT_nueCC","#nu_{e} CC","l");

   ci = TColor::GetColor("#3399ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_LPMT_nueCC_cut","#nu_{e} CC sel.","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_LPMT_bkg1","res. bkg","l");

   ci = TColor::GetColor("#006600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c15->Modified();
   c15->cd();
   c15->SetSelected(c15);
}
