void NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut()
{
//=========Macro generated from canvas: c15/
//=========  (Sat Jan 12 09:17:42 2019) by ROOT version 6.13/08
   TCanvas *c15 = new TCanvas("c15", "",117,107,800,600);
   gStyle->SetOptStat(0);
   c15->Range(-3750000,-0.6326205,3.375e+07,4.639217);
   c15->SetFillColor(0);
   c15->SetBorderMode(0);
   c15->SetBorderSize(2);
   c15->SetLogy();
   c15->SetBottomMargin(0.12);
   c15->SetFrameBorderMode(0);
   c15->SetFrameBorderMode(0);
   
   TH1F *Npe_LPMT_nueCC__1 = new TH1F("Npe_LPMT_nueCC__1","",35,0,3e+07);
   Npe_LPMT_nueCC__1->SetBinContent(1,6831);
   Npe_LPMT_nueCC__1->SetBinContent(2,4044);
   Npe_LPMT_nueCC__1->SetBinContent(3,1932);
   Npe_LPMT_nueCC__1->SetBinContent(4,1120);
   Npe_LPMT_nueCC__1->SetBinContent(5,693);
   Npe_LPMT_nueCC__1->SetBinContent(6,478);
   Npe_LPMT_nueCC__1->SetBinContent(7,363);
   Npe_LPMT_nueCC__1->SetBinContent(8,265);
   Npe_LPMT_nueCC__1->SetBinContent(9,202);
   Npe_LPMT_nueCC__1->SetBinContent(10,164);
   Npe_LPMT_nueCC__1->SetBinContent(11,120);
   Npe_LPMT_nueCC__1->SetBinContent(12,102);
   Npe_LPMT_nueCC__1->SetBinContent(13,92);
   Npe_LPMT_nueCC__1->SetBinContent(14,68);
   Npe_LPMT_nueCC__1->SetBinContent(15,63);
   Npe_LPMT_nueCC__1->SetBinContent(16,65);
   Npe_LPMT_nueCC__1->SetBinContent(17,47);
   Npe_LPMT_nueCC__1->SetBinContent(18,39);
   Npe_LPMT_nueCC__1->SetBinContent(19,41);
   Npe_LPMT_nueCC__1->SetBinContent(20,40);
   Npe_LPMT_nueCC__1->SetBinContent(21,19);
   Npe_LPMT_nueCC__1->SetBinContent(22,27);
   Npe_LPMT_nueCC__1->SetBinContent(23,22);
   Npe_LPMT_nueCC__1->SetBinContent(24,19);
   Npe_LPMT_nueCC__1->SetBinContent(25,16);
   Npe_LPMT_nueCC__1->SetBinContent(26,14);
   Npe_LPMT_nueCC__1->SetBinContent(27,8);
   Npe_LPMT_nueCC__1->SetBinContent(28,10);
   Npe_LPMT_nueCC__1->SetBinContent(29,5);
   Npe_LPMT_nueCC__1->SetBinContent(30,2);
   Npe_LPMT_nueCC__1->SetBinContent(31,5);
   Npe_LPMT_nueCC__1->SetBinContent(32,2);
   Npe_LPMT_nueCC__1->SetBinContent(33,3);
   Npe_LPMT_nueCC__1->SetEntries(16921);
   Npe_LPMT_nueCC__1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#3399ff");
   Npe_LPMT_nueCC__1->SetFillColor(ci);
   Npe_LPMT_nueCC__1->SetFillStyle(3002);

   ci = TColor::GetColor("#3399ff");
   Npe_LPMT_nueCC__1->SetLineColor(ci);
   Npe_LPMT_nueCC__1->SetLineWidth(5);
   Npe_LPMT_nueCC__1->GetXaxis()->SetTitle("NPE_{LPMT}");
   Npe_LPMT_nueCC__1->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC__1->GetXaxis()->SetLabelSize(0.05);
   Npe_LPMT_nueCC__1->GetXaxis()->SetTitleSize(0.05);
   Npe_LPMT_nueCC__1->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC__1->GetYaxis()->SetTitle("entries");
   Npe_LPMT_nueCC__1->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC__1->GetYaxis()->SetLabelSize(0.05);
   Npe_LPMT_nueCC__1->GetYaxis()->SetTitleSize(0.035);
   Npe_LPMT_nueCC__1->GetYaxis()->SetTitleOffset(1.2);
   Npe_LPMT_nueCC__1->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC__1->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC__1->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_nueCC__1->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_nueCC__1->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC__1->Draw("");
   
   TH1F *Npe_LPMT_nueCC_cut__2 = new TH1F("Npe_LPMT_nueCC_cut__2","",35,0,3e+07);
   Npe_LPMT_nueCC_cut__2->SetBinContent(1,4299);
   Npe_LPMT_nueCC_cut__2->SetBinContent(2,1929);
   Npe_LPMT_nueCC_cut__2->SetBinContent(3,932);
   Npe_LPMT_nueCC_cut__2->SetBinContent(4,587);
   Npe_LPMT_nueCC_cut__2->SetBinContent(5,388);
   Npe_LPMT_nueCC_cut__2->SetBinContent(6,276);
   Npe_LPMT_nueCC_cut__2->SetBinContent(7,202);
   Npe_LPMT_nueCC_cut__2->SetBinContent(8,141);
   Npe_LPMT_nueCC_cut__2->SetBinContent(9,117);
   Npe_LPMT_nueCC_cut__2->SetBinContent(10,83);
   Npe_LPMT_nueCC_cut__2->SetBinContent(11,69);
   Npe_LPMT_nueCC_cut__2->SetBinContent(12,56);
   Npe_LPMT_nueCC_cut__2->SetBinContent(13,56);
   Npe_LPMT_nueCC_cut__2->SetBinContent(14,35);
   Npe_LPMT_nueCC_cut__2->SetBinContent(15,33);
   Npe_LPMT_nueCC_cut__2->SetBinContent(16,37);
   Npe_LPMT_nueCC_cut__2->SetBinContent(17,27);
   Npe_LPMT_nueCC_cut__2->SetBinContent(18,23);
   Npe_LPMT_nueCC_cut__2->SetBinContent(19,19);
   Npe_LPMT_nueCC_cut__2->SetBinContent(20,19);
   Npe_LPMT_nueCC_cut__2->SetBinContent(21,7);
   Npe_LPMT_nueCC_cut__2->SetBinContent(22,16);
   Npe_LPMT_nueCC_cut__2->SetBinContent(23,11);
   Npe_LPMT_nueCC_cut__2->SetBinContent(24,12);
   Npe_LPMT_nueCC_cut__2->SetBinContent(25,11);
   Npe_LPMT_nueCC_cut__2->SetBinContent(26,10);
   Npe_LPMT_nueCC_cut__2->SetBinContent(27,5);
   Npe_LPMT_nueCC_cut__2->SetBinContent(28,6);
   Npe_LPMT_nueCC_cut__2->SetBinContent(29,1);
   Npe_LPMT_nueCC_cut__2->SetBinContent(30,1);
   Npe_LPMT_nueCC_cut__2->SetBinContent(31,4);
   Npe_LPMT_nueCC_cut__2->SetBinContent(32,2);
   Npe_LPMT_nueCC_cut__2->SetBinContent(33,2);
   Npe_LPMT_nueCC_cut__2->SetEntries(9416);
   Npe_LPMT_nueCC_cut__2->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Npe_LPMT_nueCC_cut__2->SetFillColor(ci);
   Npe_LPMT_nueCC_cut__2->SetFillStyle(3002);

   ci = TColor::GetColor("#ff0000");
   Npe_LPMT_nueCC_cut__2->SetLineColor(ci);
   Npe_LPMT_nueCC_cut__2->SetLineWidth(5);
   Npe_LPMT_nueCC_cut__2->GetXaxis()->SetTitle("NPE_{LPMT}");
   Npe_LPMT_nueCC_cut__2->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC_cut__2->GetXaxis()->SetLabelSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetXaxis()->SetTitleSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC_cut__2->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC_cut__2->GetYaxis()->SetLabelSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetYaxis()->SetTitleSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetYaxis()->SetTitleOffset(0);
   Npe_LPMT_nueCC_cut__2->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC_cut__2->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_nueCC_cut__2->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_nueCC_cut__2->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_nueCC_cut__2->Draw("same");
   
   TH1F *Npe_LPMT_bkg1__3 = new TH1F("Npe_LPMT_bkg1__3","",35,0,3e+07);
   Npe_LPMT_bkg1__3->SetBinContent(1,2947);
   Npe_LPMT_bkg1__3->SetBinContent(2,348);
   Npe_LPMT_bkg1__3->SetBinContent(3,123);
   Npe_LPMT_bkg1__3->SetBinContent(4,61);
   Npe_LPMT_bkg1__3->SetBinContent(5,64);
   Npe_LPMT_bkg1__3->SetBinContent(6,35);
   Npe_LPMT_bkg1__3->SetBinContent(7,23);
   Npe_LPMT_bkg1__3->SetBinContent(8,20);
   Npe_LPMT_bkg1__3->SetBinContent(9,12);
   Npe_LPMT_bkg1__3->SetBinContent(10,10);
   Npe_LPMT_bkg1__3->SetBinContent(11,15);
   Npe_LPMT_bkg1__3->SetBinContent(12,10);
   Npe_LPMT_bkg1__3->SetBinContent(13,4);
   Npe_LPMT_bkg1__3->SetBinContent(14,5);
   Npe_LPMT_bkg1__3->SetBinContent(15,4);
   Npe_LPMT_bkg1__3->SetBinContent(17,5);
   Npe_LPMT_bkg1__3->SetBinContent(18,1);
   Npe_LPMT_bkg1__3->SetBinContent(19,2);
   Npe_LPMT_bkg1__3->SetBinContent(20,4);
   Npe_LPMT_bkg1__3->SetBinContent(21,2);
   Npe_LPMT_bkg1__3->SetBinContent(22,3);
   Npe_LPMT_bkg1__3->SetBinContent(23,3);
   Npe_LPMT_bkg1__3->SetBinContent(24,4);
   Npe_LPMT_bkg1__3->SetBinContent(25,3);
   Npe_LPMT_bkg1__3->SetBinContent(31,1);
   Npe_LPMT_bkg1__3->SetEntries(3709);
   Npe_LPMT_bkg1__3->SetStats(0);

   ci = TColor::GetColor("#006600");
   Npe_LPMT_bkg1__3->SetFillColor(ci);
   Npe_LPMT_bkg1__3->SetFillStyle(3002);

   ci = TColor::GetColor("#006600");
   Npe_LPMT_bkg1__3->SetLineColor(ci);
   Npe_LPMT_bkg1__3->SetLineWidth(5);
   Npe_LPMT_bkg1__3->GetXaxis()->SetTitle("NPE_{LPMT}");
   Npe_LPMT_bkg1__3->GetXaxis()->SetLabelFont(42);
   Npe_LPMT_bkg1__3->GetXaxis()->SetLabelSize(0.035);
   Npe_LPMT_bkg1__3->GetXaxis()->SetTitleSize(0.035);
   Npe_LPMT_bkg1__3->GetXaxis()->SetTitleFont(42);
   Npe_LPMT_bkg1__3->GetYaxis()->SetLabelFont(42);
   Npe_LPMT_bkg1__3->GetYaxis()->SetLabelSize(0.035);
   Npe_LPMT_bkg1__3->GetYaxis()->SetTitleSize(0.035);
   Npe_LPMT_bkg1__3->GetYaxis()->SetTitleOffset(0);
   Npe_LPMT_bkg1__3->GetYaxis()->SetTitleFont(42);
   Npe_LPMT_bkg1__3->GetZaxis()->SetLabelFont(42);
   Npe_LPMT_bkg1__3->GetZaxis()->SetLabelSize(0.035);
   Npe_LPMT_bkg1__3->GetZaxis()->SetTitleSize(0.035);
   Npe_LPMT_bkg1__3->GetZaxis()->SetTitleFont(42);
   Npe_LPMT_bkg1__3->Draw("same");
   
   TLegend *leg = new TLegend(0.65,0.6,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Npe_LPMT_nueCC","#nu_{e} CC","l");

   ci = TColor::GetColor("#3399ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_LPMT_nueCC_cut","#nu_{e} CC sel.","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Npe_LPMT_bkg1","res. bkg","l");

   ci = TColor::GetColor("#006600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c15->Modified();
   c15->cd();
   c15->SetSelected(c15);
}
