void NuSpectrum2() {

  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);
  TCanvas *c1 = new TCanvas("c1","",1200,1000);
  TCanvas *c2 = new TCanvas("c2","",1200,1000);
  TGraph *H_Flux_Mu_osc;
  TGraph *H_Flux_Mu_noosc;
  TGraph *H_Flux_E_osc;
  TGraph *H_Flux_E_noosc;
  TGraphErrors *Mu_flux;
  TGraphErrors *E_flux;
  TGraphErrors *Mu_SK_flux;
  TGraphErrors *E_SK_flux;

  std::ifstream NueSpec("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/bayes/output_Nue_osc_NEW/Unf_spectrum_7_7.txt");
  //std::ifstream NuMuSpec("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/bayes/output_Numu_osc_NEW/Unf_spectrum_8_8.txt");
  std::ifstream NuMuSpec("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/bayes/output_Numu_osc/Unf_spectrum_7_8.txt");

  //TFile *_file0 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/bayes/output_Numu_osc_NEW/plot_8_8.root");
  TFile *_file0 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/bayes/output_Numu_osc/plot_7_8.root");
  _file0->GetObject("Honda_Flux_noosc",H_Flux_Mu_noosc);
  _file0->GetObject("Honda_Flux_osc",H_Flux_Mu_osc);
  _file0->GetObject("Unfolded_flux_1_iter",Mu_flux);
  _file0->GetObject("SK_Flux",Mu_SK_flux);
  TFile *_file1 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/bayes/output_Nue_osc_NEW/plot_7_7.root");
  _file1->GetObject("Honda_Flux_noosc",H_Flux_E_noosc);
  _file1->GetObject("Honda_Flux_osc",H_Flux_E_osc);
  _file1->GetObject("Unfolded_flux_1_iter",E_flux);
  //_file1->GetObject("Unfolded_flux",E_flux);
  _file1->GetObject("SK_Flux",E_SK_flux);
  TLegend * leg1 = new TLegend(0.12,0.15,0.55,0.35);
  TLegend * leg2 = new TLegend(0.12,0.15,0.55,0.35);
  H_Flux_Mu_noosc->SetLineColor(kBlue);
  H_Flux_Mu_noosc->SetLineStyle(2);
  H_Flux_Mu_osc->SetLineColor(kBlue);
  Mu_flux->SetMarkerStyle(20);
  Mu_flux->SetMarkerSize(2.5);
  Mu_flux->SetMarkerColor(kBlue);
  Mu_flux->SetLineWidth(3);
  Mu_flux->SetLineColor(kBlue);
  Mu_SK_flux->SetMarkerStyle(28);
  Mu_SK_flux->SetMarkerSize(2.5);
  //Mu_SK_flux->SetMarkerColor(kOrange-2);
  Mu_SK_flux->SetLineWidth(2);
  //Mu_SK_flux->SetLineColor(kBlue);
  H_Flux_E_noosc->SetLineColor(kRed);
  H_Flux_E_noosc->SetLineStyle(2);
  H_Flux_E_osc->SetLineColor(kRed);
  E_flux->SetMarkerStyle(20);
  E_flux->SetMarkerSize(2.5);
  E_flux->SetMarkerColor(kRed);
  E_flux->SetLineWidth(3);
  E_flux->SetLineColor(kRed);
  E_SK_flux->SetMarkerStyle(28);
  E_SK_flux->SetMarkerSize(2.5);
  //E_SK_flux->SetMarkerColor(kGreen+2);
  E_SK_flux->SetLineWidth(2);
  //E_SK_flux->SetLineColor(kRed);
  leg1->AddEntry(H_Flux_Mu_noosc, "HKKM14 #nu_{#mu} Flux (w/o osc.)", "l");
  leg1->AddEntry(H_Flux_Mu_osc, "HKKM14 #nu_{#mu} Flux (w/ osc.)", "l");
  leg1->AddEntry(Mu_flux, "This work (8 yrs) #nu_{#mu}", "pe");
  leg1->AddEntry(Mu_SK_flux, "PRD 94, 052001 (#nu_{#mu})", "pe");
  leg1->SetBorderSize(0);
  leg2->AddEntry(H_Flux_E_noosc, "HKKM14 #nu_{e} Flux (w/o osc.)", "l");
  leg2->AddEntry(H_Flux_E_osc, "HKKM14 #nu_{e} Flux (w/ osc.)", "l");
  leg2->AddEntry(E_flux, "This work (8 yrs) #nu_{e}", "pe");
  leg2->AddEntry(E_SK_flux, "PRD 94, 052001 (#nu_{e})", "pe");
  leg2->SetBorderSize(0);
  c1->cd();
  gPad->SetLogy();
  H_Flux_Mu_noosc->Draw("AL");
  H_Flux_Mu_osc->Draw("CL");
  Mu_SK_flux->Draw("PE");
  Mu_flux->Draw("PE");
  leg1->Draw();
  c2->cd();
  gPad->SetLogy();
  H_Flux_E_noosc->Draw("AL");
  H_Flux_E_osc->Draw("CL");
  E_SK_flux->Draw("PE");
  E_flux->Draw("PE");
  leg2->Draw();  
  c1->SaveAs("Plot/Spec_mu.png");
  c2->SaveAs("Plot/Spec_me.png");
}
