void DATA_makespectrum_cuts() {
  gStyle->SetOptStat(0);
  gStyle->SetPadBottomMargin(0.12);
  gStyle->SetTitleH(0.1);
  gStyle->SetTitleW(1.05);

  TTree *mytree;
  TFile *_file1 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/treemaker/trees/DATA_10K_1m_TOT.root");
  //TFile *_file1 = TFile::Open("/home/sgiulio/Giulio/University/JUNO/juno-unfolding/treemaker/trees/MC_100K_1m_FULL.root");
  _file1->GetObject("Data",mytree);

  TCanvas *c15 = new TCanvas("c15","",800,600);
  TLegend * leg4 = new TLegend(0.65,0.9,0.9,0.6);
  TH1F *Npe_LPMT_nueCC = new TH1F("Npe_LPMT_nueCC","",12,0.,3.0E7);
  Npe_LPMT_nueCC->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_LPMT_nueCC->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_nueCC->GetXaxis()->SetLabelSize(0.05);
  Npe_LPMT_nueCC->GetYaxis()->SetTitle("entries");
  Npe_LPMT_nueCC->GetYaxis()->SetLabelSize(0.05);
  Npe_LPMT_nueCC->GetYaxis()->SetTitleOffset(1.2);
  Npe_LPMT_nueCC->SetLineWidth(5);
  Npe_LPMT_nueCC->SetLineColor(kAzure+1);
  Npe_LPMT_nueCC->SetFillColor(kAzure+1);
  Npe_LPMT_nueCC->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_nueCC","(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  Npe_LPMT_nueCC->Draw();
  TH1F *Npe_LPMT_nueCC_cut = new TH1F("Npe_LPMT_nueCC_cut","",12,0.,3.0E7);
  Npe_LPMT_nueCC_cut->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_LPMT_nueCC_cut->SetLineWidth(5);
  Npe_LPMT_nueCC_cut->SetLineColor(kRed);
  Npe_LPMT_nueCC_cut->SetFillColor(kRed);
  Npe_LPMT_nueCC_cut->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_nueCC_cut","(trueNPE_LPMT_CD)","Tres_RMS<75 && CCint==1 && abs(init_lepID)==11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  Npe_LPMT_nueCC_cut->Draw("same");
  TH1F *Npe_LPMT_bkg1 = new TH1F("Npe_LPMT_bkg1","",12,0.,3.0E7);
  Npe_LPMT_bkg1->GetXaxis()->SetTitle("NPE_{LPMT}");
  gPad->SetLogy();
  Npe_LPMT_bkg1->SetLineWidth(5);
  Npe_LPMT_bkg1->SetLineColor(kGreen+3);
  Npe_LPMT_bkg1->SetFillColor(kGreen+3);
  Npe_LPMT_bkg1->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_bkg1","(trueNPE_LPMT_CD)","Tres_RMS<75 && abs(init_lepID)!=11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  c15->cd();
  Npe_LPMT_bkg1->Draw("same");
  leg4->AddEntry(Npe_LPMT_nueCC, "#nu_{e} CC" ,"l");
  leg4->AddEntry(Npe_LPMT_nueCC_cut, "#nu_{e} CC sel." ,"l");  
  leg4->AddEntry(Npe_LPMT_bkg1, "res. bkg" ,"l");
  leg4->Draw();
  c15->SaveAs("Plot/DATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.png");
  c15->SaveAs("Plot/DATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.pdf");
  c15->SaveAs("Plot/DATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.C");
  ///////////////////////////////////////////////////////////////////////////////////
  
  TCanvas *c25 = new TCanvas("c25","",800,600);
  TLegend * leg14 = new TLegend(0.65,0.9,0.9,0.6);
  TH1F *Npe_LPMT_numuCC = new TH1F("Npe_LPMT_numuCC","",12,0.,3.0E7);
  gPad->SetLogy();
  Npe_LPMT_numuCC->SetLineWidth(5);
  Npe_LPMT_numuCC->SetLineColor(kAzure+1);
  Npe_LPMT_numuCC->SetFillColor(kAzure+1);
  Npe_LPMT_numuCC->SetFillStyle(3002);
  Npe_LPMT_numuCC->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_LPMT_numuCC->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_numuCC->GetXaxis()->SetLabelSize(0.05);
  Npe_LPMT_numuCC->GetYaxis()->SetTitle("entries");
  Npe_LPMT_numuCC->GetYaxis()->SetLabelSize(0.05);
  Npe_LPMT_numuCC->GetYaxis()->SetTitleOffset(1.2);
  mytree->Project("Npe_LPMT_numuCC","(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  leg14->AddEntry(Npe_LPMT_numuCC, "#nu_{#mu} CC" ,"l");
  TH1F *Npe_LPMT_numuCC_cut = new TH1F("Npe_LPMT_numuCC_cut","",12,0.,3.0E7);
  Npe_LPMT_numuCC_cut->GetXaxis()->SetTitle("NPE_{LPMT}");
  gPad->SetLogy();
  Npe_LPMT_numuCC_cut->SetLineWidth(5);
  Npe_LPMT_numuCC_cut->SetLineColor(kRed);
  Npe_LPMT_numuCC_cut->SetFillColor(kRed);
  Npe_LPMT_numuCC_cut->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_numuCC_cut","(trueNPE_LPMT_CD)","Tres_RMS>95 && CCint==1 && abs(init_lepID)==13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  leg14->AddEntry(Npe_LPMT_numuCC_cut, "#nu_{#mu} CC sel." ,"l");
  TH1F *Npe_LPMT_bkg2 = new TH1F("Npe_LPMT_bkg2","",12,0.,3.0E7);
  Npe_LPMT_bkg2->GetXaxis()->SetTitle("NPE_{LPMT}");
  gPad->SetLogy();
  Npe_LPMT_bkg2->SetLineWidth(5);
  Npe_LPMT_bkg2->SetLineColor(kGreen+3);
  Npe_LPMT_bkg2->SetFillColor(kGreen+3);
  Npe_LPMT_bkg2->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_bkg2","(trueNPE_LPMT_CD)","Tres_RMS>95 && abs(init_lepID)!=13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  c25->cd();
  Npe_LPMT_numuCC->Draw();
  Npe_LPMT_numuCC_cut->Draw("same");
  Npe_LPMT_bkg2->Draw("same");
  leg14->AddEntry(Npe_LPMT_bkg2, "res. bkg" ,"l");
  leg14->Draw();
  c25->SaveAs("Plot/DATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.png");
  c25->SaveAs("Plot/DATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.pdf");
  c25->SaveAs("Plot/DATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.C");

  //////////////////////////////////LOGPLOTS//////////////////////////

  TCanvas *c7 = new TCanvas("c7","",800,600);
  TLegend * leg8 = new TLegend(0.7,0.9,0.9,0.65);
  TH1F *Lognpe_LPMT_allcutsNue = new TH1F("Lognpe_LPMT_allcutsNue","",12,5.0,7.2);
  Lognpe_LPMT_allcutsNue->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  Lognpe_LPMT_allcutsNue->GetXaxis()->SetTitleSize(0.05);
  Lognpe_LPMT_allcutsNue->GetXaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_allcutsNue->GetYaxis()->SetTitle("entries");
  Lognpe_LPMT_allcutsNue->GetYaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_allcutsNue->GetYaxis()->SetTitleOffset(1.2);
  Lognpe_LPMT_allcutsNue->SetLineWidth(5);
  Lognpe_LPMT_allcutsNue->SetLineColor(kAzure+1);
  Lognpe_LPMT_allcutsNue->SetFillColor(kAzure+1);
  Lognpe_LPMT_allcutsNue->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_allcutsNue","log10(trueNPE_LPMT_CD)","Tres_RMS<75 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  Lognpe_LPMT_allcutsNue->Draw();
  TH1F *Lognpe_LPMT_allcuts_nue = new TH1F("Lognpe_LPMT_allcuts_nue","",12,5.0,7.2);
  Lognpe_LPMT_allcuts_nue->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  Lognpe_LPMT_allcuts_nue->SetLineWidth(5);
  Lognpe_LPMT_allcuts_nue->SetLineColor(kRed);
  Lognpe_LPMT_allcuts_nue->SetFillColor(kRed);
  Lognpe_LPMT_allcuts_nue->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_allcuts_nue","log10(trueNPE_LPMT_CD)","Tres_RMS<75 && abs(init_nuID)==12 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  Lognpe_LPMT_allcuts_nue->Draw("same");
  TH1F *Lognpe_LPMT_allcuts_bkg1 = new TH1F("Lognpe_LPMT_allcuts_bkg1","",12,5.0,7.2);
  Lognpe_LPMT_allcuts_bkg1->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  gPad->SetLogy();
  Lognpe_LPMT_allcuts_bkg1->SetLineWidth(5);
  Lognpe_LPMT_allcuts_bkg1->SetLineColor(kGreen+3);
  Lognpe_LPMT_allcuts_bkg1->SetFillColor(kGreen+3);
  Lognpe_LPMT_allcuts_bkg1->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_allcuts_bkg1","log10(trueNPE_LPMT_CD)","Tres_RMS<75 && abs(init_nuID)!=12 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  c7->cd();
  Lognpe_LPMT_allcuts_bkg1->Draw("same");
  leg8->AddEntry(Lognpe_LPMT_allcutsNue, "sel." ,"l");
  leg8->AddEntry(Lognpe_LPMT_allcuts_nue, "#nu_{e} sel." ,"l");  
  leg8->AddEntry(Lognpe_LPMT_allcuts_bkg1, "res. bkg" ,"l");
  leg8->Draw();
  c7->SaveAs("Plot/LOGDATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.png");
  c7->SaveAs("Plot/LOGDATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.pdf");
  c7->SaveAs("Plot/LOGDATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.C");
  ///////////////////////////////////////////////////////////////////////////////////
  
  TCanvas *c17 = new TCanvas("c17","",800,600);
  TLegend * leg18 = new TLegend(0.7,0.9,0.9,0.65);
  TH1F *Lognpe_LPMT_allcutsNumu = new TH1F("Lognpe_LPMT_allcutsNumu","",12,5.7,7.2);
  gPad->SetLogy();
  Lognpe_LPMT_allcutsNumu->SetLineWidth(5);
  Lognpe_LPMT_allcutsNumu->SetLineColor(kAzure+1);
  Lognpe_LPMT_allcutsNumu->SetFillColor(kAzure+1);
  Lognpe_LPMT_allcutsNumu->SetFillStyle(3002);
  Lognpe_LPMT_allcutsNumu->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  Lognpe_LPMT_allcutsNumu->GetXaxis()->SetTitleSize(0.05);
  Lognpe_LPMT_allcutsNumu->GetXaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_allcutsNumu->GetYaxis()->SetTitle("entries");
  Lognpe_LPMT_allcutsNumu->GetYaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_allcutsNumu->GetYaxis()->SetTitleOffset(1.2);
  mytree->Project("Lognpe_LPMT_allcutsNumu","log10(trueNPE_LPMT_CD)","Tres_RMS>95 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  leg18->AddEntry(Lognpe_LPMT_allcutsNumu, "sel." ,"l");
  TH1F *Lognpe_LPMT_allcuts_numu = new TH1F("Lognpe_LPMT_allcuts_numu","",12,5.7,7.2);
  Lognpe_LPMT_allcuts_numu->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  gPad->SetLogy();
  Lognpe_LPMT_allcuts_numu->SetLineWidth(5);
  Lognpe_LPMT_allcuts_numu->SetLineColor(kRed);
  Lognpe_LPMT_allcuts_numu->SetFillColor(kRed);
  Lognpe_LPMT_allcuts_numu->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_allcuts_numu","log10(trueNPE_LPMT_CD)","Tres_RMS>95 && abs(init_nuID)==14 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  leg18->AddEntry(Lognpe_LPMT_allcuts_numu, "#nu_{#mu} sel." ,"l");
  TH1F *Lognpe_LPMT_allcuts_bkg2 = new TH1F("Lognpe_LPMT_allcuts_bkg2","",12,5.7,7.2);
  Lognpe_LPMT_allcuts_bkg2->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  gPad->SetLogy();
  Lognpe_LPMT_allcuts_bkg2->SetLineWidth(5);
  Lognpe_LPMT_allcuts_bkg2->SetLineColor(kGreen+3);
  Lognpe_LPMT_allcuts_bkg2->SetFillColor(kGreen+3);
  Lognpe_LPMT_allcuts_bkg2->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_allcuts_bkg2","log10(trueNPE_LPMT_CD)","Tres_RMS>95 && abs(init_nuID)!=14 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  c17->cd();
  Lognpe_LPMT_allcutsNumu->Draw();
  Lognpe_LPMT_allcuts_numu->Draw("same");
  Lognpe_LPMT_allcuts_bkg2->Draw("same");
  leg18->AddEntry(Lognpe_LPMT_allcuts_bkg2, "res. bkg" ,"l");
  leg18->Draw();
  c17->SaveAs("Plot/LOGDATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.png");
  c17->SaveAs("Plot/LOGDATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.pdf");
  c17->SaveAs("Plot/LOGDATA_NPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.C");
  
}
