void makespectrum_cont() {
  gStyle->SetOptStat(0);
  //gStyle->SetPadBottomMargin(0.0);
  gStyle->SetOptTitle(0);

  TTree *mytree;
  TFile *_file1 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/treemaker/trees/MC_500K_1m_TOT_NEW.root");
  _file1->GetObject("Data",mytree);

  TCanvas *c80 = new TCanvas("c80","",1200,1000);
  TLegend * leg80a = new TLegend(0.65,0.9,0.9,0.6);
  leg80a->SetBorderSize(0);
  TLegend * leg80b = new TLegend(0.65,0.9,0.9,0.6);
  leg80b->SetBorderSize(0);
  TLegend * leg80c = new TLegend(0.65,0.9,0.9,0.6);
  leg80c->SetBorderSize(0);
  c80->cd();
  TH1F *Enu_nux_FC = new TH1F("Enu_nux_FC","",100,0.,20.15);
  Enu_nux_FC->GetXaxis()->SetTitle("E_{#nu} [GeV]");
  Enu_nux_FC->GetXaxis()->SetTitleSize(0.1);
  Enu_nux_FC->GetXaxis()->SetLabelSize(0.1);
  Enu_nux_FC->GetYaxis()->SetTitle("entries");
  Enu_nux_FC->GetYaxis()->SetLabelSize(0.1);
  Enu_nux_FC->GetYaxis()->SetTitleSize(0.08);
  Enu_nux_FC->GetYaxis()->SetTitleOffset(0.5);
  Enu_nux_FC->SetLineWidth(3);
  Enu_nux_FC->SetLineColor(30);
  mytree->Project("Enu_nux_FC","nuEnergy/1000.","NCint==1 && FC==1","");
  TH1F *Enu_nux_PC = new TH1F("Enu_nux_PC","",100,0.,20.15);
  Enu_nux_PC->SetLineWidth(3);
  Enu_nux_PC->SetLineColor(30);
  Enu_nux_PC->SetLineStyle(2);
  mytree->Project("Enu_nux_PC","nuEnergy/1000.","NCint==1 && PC==1","");
  TH1F *Enu_nue_FC = new TH1F("Enu_nue_FC","",100,0.,20.15);
  Enu_nue_FC->GetXaxis()->SetTitle("E_{#nu} [GeV]");
  Enu_nue_FC->GetXaxis()->SetTitleSize(0.1);
  Enu_nue_FC->GetXaxis()->SetLabelSize(0.1);
  Enu_nue_FC->GetYaxis()->SetTitle("entries");
  Enu_nue_FC->GetYaxis()->SetTitleSize(0.08);
  Enu_nue_FC->GetYaxis()->SetLabelSize(0.1);
  Enu_nue_FC->GetYaxis()->SetTitleOffset(0.5);
  gPad->SetLogy();
  Enu_nue_FC->SetLineWidth(3);
  Enu_nue_FC->SetLineColor(46);
  mytree->Project("Enu_nue_FC","nuEnergy/1000.","abs(init_lepID)==11 && CCint==1 && FC==1","");
  TH1F *Enu_nue_PC = new TH1F("Enu_nue_PC","",100,0.,20.15);
  gPad->SetLogy();
  Enu_nue_PC->SetLineWidth(3);
  Enu_nue_PC->SetLineColor(46);
  Enu_nue_PC->SetLineStyle(2);
  mytree->Project("Enu_nue_PC","nuEnergy/1000.","abs(init_lepID)==11 && CCint==1 && PC==1","");
  TH1F *Enu_numu_FC = new TH1F("Enu_numu_FC","",100,0.,20.15);
  Enu_numu_FC->GetXaxis()->SetTitle("E_{#nu} [GeV]");
  Enu_numu_FC->GetXaxis()->SetTitleSize(0.1);
  Enu_numu_FC->GetXaxis()->SetLabelSize(0.1);
  Enu_numu_FC->GetYaxis()->SetTitle("entries");
  Enu_numu_FC->GetYaxis()->SetTitleSize(0.08);
  Enu_numu_FC->GetYaxis()->SetLabelSize(0.1);
  Enu_numu_FC->GetYaxis()->SetTitleOffset(0.5);
  Enu_numu_FC->GetYaxis()->SetRangeUser(2.,5.E4);
  Enu_numu_FC->SetLineWidth(3);
  Enu_numu_FC->SetLineColor(9);
  mytree->Project("Enu_numu_FC","nuEnergy/1000.","abs(init_lepID)==13 && CCint==1 && FC==1","");
  TH1F *Enu_numu_PC = new TH1F("Enu_numu_PC","",100,0.,20.15);
  Enu_numu_PC->SetLineWidth(3);
  Enu_numu_PC->SetLineColor(9);
  Enu_numu_PC->SetLineStyle(2);
  mytree->Project("Enu_numu_PC","nuEnergy/1000.","abs(init_lepID)==13 && CCint==1 && PC==1","");
  leg80a->AddEntry(Enu_nue_FC, "#nu_{e}^{CC} FC" ,"l");
  leg80a->AddEntry(Enu_nue_PC, "#nu_{e}^{CC} PC" ,"l");
  leg80b->AddEntry(Enu_numu_FC, "#nu_{#mu}^{CC} FC" ,"l");
  leg80b->AddEntry(Enu_numu_PC, "#nu_{#mu}^{CC} PC" ,"l");
  leg80c->AddEntry(Enu_nux_FC, "#nu_{x}^{NC} FC" ,"l");
  leg80c->AddEntry(Enu_nux_PC, "#nu_{x}^{NC} PC" ,"l");

  TPad *p1 = new TPad("p1", "p1", 0.05, 0.6333334, 0.9, 0.9, 0, 0, 0);
  p1->SetTopMargin(0);
  p1->SetBottomMargin(0);
  p1->SetRightMargin(0.02);
  p1->Draw();
  TPad *p2 = new TPad("p2", "p2", 0.05, 0.3666667, 0.9, 0.6333334, 0, 0, 0);
  p2->SetTopMargin(0);
  p2->SetBottomMargin(0);
  p2->SetRightMargin(0.02);
  p2->Draw();
  TPad *p3 = new TPad("p3", "p3", 0.05, 0.1, 0.9, 0.3666667, 0, 0, 0);
  p3->SetTopMargin(0);
  p3->SetRightMargin(0.02);
  p3->SetBottomMargin(0.25);
  p3->Draw();

  p1->cd();
  gPad->SetLogy();
  Enu_nue_FC->GetXaxis()->SetLabelSize(0);
  Enu_nue_FC->Draw();
  Enu_nue_PC->Draw("same");
  leg80a->Draw();

  p2->cd();
  gPad->SetLogy();
  Enu_numu_FC->GetXaxis()->SetLabelSize(0);
  Enu_numu_FC->Draw();
  Enu_numu_PC->Draw("same");
  leg80b->Draw();

  p3->cd();
  gPad->SetLogy();
  Enu_nux_FC->Draw();
  Enu_nux_PC->Draw("same");
  leg80c->Draw();

  c80->SaveAs("Plot/Ev_contained_0-20GeV_1m.png");
  c80->SaveAs("Plot/Ev_contained_0-20GeV_1m.pdf");
  c80->SaveAs("Plot/Ev_contained_0-20GeV_1m.C");

  ///////////////////////////LOGPLOTS////////////////////////////////////////

  TCanvas *c81 = new TCanvas("c81","",1200,1000);
  TLegend * leg81a = new TLegend(0.12,0.7,0.23,0.97);
  leg81a->SetBorderSize(0);
  TLegend * leg81b = new TLegend(0.12,0.7,0.23,0.97);
  leg81b->SetBorderSize(0);
  TLegend * leg81c = new TLegend(0.12,0.7,0.23,0.97);
  leg81c->SetBorderSize(0);
  c81->cd();
  TH1F *LogEnu_nux_FC = new TH1F("LogEnu_nux_FC","",75,-1.7,1.3);
  LogEnu_nux_FC->GetXaxis()->SetTitle("log_{10}(E_{#nu} / GeV)");
  LogEnu_nux_FC->GetXaxis()->SetTitleSize(0.1);
  LogEnu_nux_FC->GetXaxis()->SetLabelSize(0.08);
  LogEnu_nux_FC->GetYaxis()->SetTitle("entries");
  LogEnu_nux_FC->GetYaxis()->SetLabelSize(0.09);
  LogEnu_nux_FC->GetYaxis()->SetTitleSize(0.07);
  LogEnu_nux_FC->GetYaxis()->SetTitleOffset(0.5);
  LogEnu_nux_FC->SetLineWidth(3);
  LogEnu_nux_FC->SetLineColor(30);
  mytree->Project("LogEnu_nux_FC","log10(nuEnergy/1000.)","NCint==1 && FC==1","");
  TH1F *LogEnu_nux_PC = new TH1F("LogEnu_nux_PC","",75,-1.7,1.3);
  LogEnu_nux_PC->SetLineWidth(3);
  LogEnu_nux_PC->SetLineColor(30);
  LogEnu_nux_PC->SetLineStyle(2);
  mytree->Project("LogEnu_nux_PC","log10(nuEnergy/1000.)","NCint==1 && PC==1","");
  TH1F *LogEnu_nue_FC = new TH1F("LogEnu_nue_FC","",75,-1.7,1.3);
  LogEnu_nue_FC->GetXaxis()->SetTitle("log_{10}(E_{#nu} / GeV)");
  LogEnu_nue_FC->GetXaxis()->SetTitleSize(0.1);
  LogEnu_nue_FC->GetXaxis()->SetLabelSize(0.08);
  LogEnu_nue_FC->GetYaxis()->SetTitle("entries");
  LogEnu_nue_FC->GetYaxis()->SetTitleSize(0.08);
  LogEnu_nue_FC->GetYaxis()->SetLabelSize(0.09);
  LogEnu_nue_FC->GetYaxis()->SetTitleOffset(0.5);
  LogEnu_nue_FC->GetYaxis()->SetRangeUser(2.,6000.);
  gPad->SetLogy();
  LogEnu_nue_FC->SetLineWidth(3);
  LogEnu_nue_FC->SetLineColor(46);
  mytree->Project("LogEnu_nue_FC","log10(nuEnergy/1000.)","abs(init_lepID)==11 && CCint==1 && FC==1","");
  TH1F *LogEnu_nue_PC = new TH1F("LogEnu_nue_PC","",75,-1.7,1.3);
  gPad->SetLogy();
  LogEnu_nue_PC->SetLineWidth(3);
  LogEnu_nue_PC->SetLineColor(46);
  LogEnu_nue_PC->SetLineStyle(2);
  mytree->Project("LogEnu_nue_PC","log10(nuEnergy/1000.)","abs(init_lepID)==11 && CCint==1 && PC==1","");
  TH1F *LogEnu_numu_FC = new TH1F("LogEnu_numu_FC","",75,-1.7,1.3);
  LogEnu_numu_FC->GetXaxis()->SetTitle("log_{10}(E_{#nu} / GeV)");
  LogEnu_numu_FC->GetXaxis()->SetTitleSize(0.1);
  LogEnu_numu_FC->GetXaxis()->SetLabelSize(0.08);
  LogEnu_numu_FC->GetYaxis()->SetTitle("entries");
  LogEnu_numu_FC->GetYaxis()->SetTitleSize(0.08);
  LogEnu_numu_FC->GetYaxis()->SetLabelSize(0.09);
  LogEnu_numu_FC->GetYaxis()->SetTitleOffset(0.5);
  LogEnu_numu_FC->GetYaxis()->SetRangeUser(10.,2.E4);
  LogEnu_numu_FC->SetLineWidth(3);
  LogEnu_numu_FC->SetLineColor(9);
  mytree->Project("LogEnu_numu_FC","log10(nuEnergy/1000.)","abs(init_lepID)==13 && CCint==1 && FC==1","");
  TH1F *LogEnu_numu_PC = new TH1F("LogEnu_numu_PC","",75,-1.7,1.3);
  LogEnu_numu_PC->SetLineWidth(3);
  LogEnu_numu_PC->SetLineColor(9);
  LogEnu_numu_PC->SetLineStyle(2);
  mytree->Project("LogEnu_numu_PC","log10(nuEnergy/1000.)","abs(init_lepID)==13 && CCint==1 && PC==1","");
  leg81a->AddEntry(LogEnu_nue_FC, "#nu_{e}^{CC} FC" ,"l");
  leg81a->AddEntry(LogEnu_nue_PC, "#nu_{e}^{CC} PC" ,"l");
  leg81b->AddEntry(LogEnu_numu_FC, "#nu_{#mu}^{CC} FC" ,"l");
  leg81b->AddEntry(LogEnu_numu_PC, "#nu_{#mu}^{CC} PC" ,"l");
  leg81c->AddEntry(LogEnu_nux_FC, "#nu_{x}^{NC} FC" ,"l");
  leg81c->AddEntry(LogEnu_nux_PC, "#nu_{x}^{NC} PC" ,"l");

  TPad *p11 = new TPad("p11", "p11", 0.0, 0.66, 1.0, 0.99, 0, 0, 0);
  p11->SetTopMargin(0);
  p11->SetBottomMargin(0);
  p11->SetRightMargin(0.02);
  p11->Draw();
  TPad *p22 = new TPad("p22", "p22", 0.0, 0.33, 1.0, 0.66, 0, 0, 0);
  p22->SetTopMargin(0);
  p22->SetBottomMargin(0);
  p22->SetRightMargin(0.02);
  p22->Draw();
  TPad *p33 = new TPad("p33", "p33", 0.0, 0.0, 1.0, 0.33, 0, 0, 0);
  p33->SetTopMargin(0);
  p33->SetRightMargin(0.02);
  p33->SetBottomMargin(0.25);
  p33->Draw();

  p11->cd();
  gPad->SetLogy();
  LogEnu_nue_FC->GetXaxis()->SetLabelSize(0);
  LogEnu_nue_FC->Draw();
  LogEnu_nue_PC->Draw("same");
  leg81a->Draw();

  p22->cd();
  gPad->SetLogy();
  LogEnu_numu_FC->GetXaxis()->SetLabelSize(0);
  LogEnu_numu_FC->Draw();
  LogEnu_numu_PC->Draw("same");
  leg81b->Draw();

  p33->cd();
  gPad->SetLogy();
  LogEnu_nux_FC->Draw();
  LogEnu_nux_PC->Draw("same");
  leg81c->Draw();

  c81->SaveAs("Plot/LOGEv_contained_0-20GeV_1m.png");
  c81->SaveAs("Plot/LOGEv_contained_0-20GeV_1m.pdf");
  c81->SaveAs("Plot/LOGEv_contained_0-20GeV_1m.C");

}
