void makespectrum_fidcuts() {
  gStyle->SetOptStat(0);
  gStyle->SetPadBottomMargin(0.12);
  gStyle->SetTitleH(0.1);
  gStyle->SetTitleW(1.05);

  TTree *mytree;
  TFile *_file1 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/treemaker/trees/MC_500K_1m_TOT_NEW.root");
  //TFile *_file1 = TFile::Open("/home/sgiulio/Giulio/University/JUNO/juno-unfolding/treemaker/trees/MC_100K_1m_FULL.root");
  _file1->GetObject("Data",mytree);
  TCanvas *c80 = new TCanvas("c80","",1000,600);
  TLegend * leg80 = new TLegend(0.65,0.9,0.9,0.6);
  c80->cd();
  TH1F *Npe_LPMT_numuCC = new TH1F("Npe_LPMT_numuCC","",100,1.E5,3.E7);
  gPad->SetLogy();
  Npe_LPMT_numuCC->SetLineWidth(5);
  Npe_LPMT_numuCC->SetLineColor(kBlue+2);
  Npe_LPMT_numuCC->SetFillColor(kBlue+2);
  Npe_LPMT_numuCC->SetFillStyle(3002);
  Npe_LPMT_numuCC->GetXaxis()->SetTitle("NPE_{LPMT}^{CD}");
  Npe_LPMT_numuCC->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_numuCC->GetXaxis()->SetLabelSize(0.05);
  Npe_LPMT_numuCC->GetYaxis()->SetTitle("entries");
  Npe_LPMT_numuCC->GetYaxis()->SetLabelSize(0.05);
  Npe_LPMT_numuCC->GetYaxis()->SetTitleOffset(1.2);
  mytree->Project("Npe_LPMT_numuCC","(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  leg80->AddEntry(Npe_LPMT_numuCC, "#nu_{#mu} CC" ,"l");
  Npe_LPMT_numuCC->Draw();
  TH1F *Npe_LPMT_nueCC = new TH1F("Npe_LPMT_nueCC","",100,1.E5,3.E7);
  Npe_LPMT_nueCC->GetXaxis()->SetTitle("NPE_{LPMT}^{CD}");
  Npe_LPMT_nueCC->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_nueCC->GetXaxis()->SetLabelSize(0.05);
  Npe_LPMT_nueCC->GetYaxis()->SetTitle("entries");
  Npe_LPMT_nueCC->GetYaxis()->SetLabelSize(0.05);
  Npe_LPMT_nueCC->GetYaxis()->SetTitleOffset(1.2);
  Npe_LPMT_nueCC->SetLineWidth(5);
  Npe_LPMT_nueCC->SetLineColor(kRed);
  Npe_LPMT_nueCC->SetFillColor(kRed);
  Npe_LPMT_nueCC->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_nueCC","(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  leg80->AddEntry(Npe_LPMT_nueCC, "#nu_{e} CC" ,"l");
  Npe_LPMT_nueCC->Draw("same");
  TH1F *Npe_LPMT_nuNC = new TH1F("Npe_LPMT_nuNC","",100,1.E5,3.E7);
  Npe_LPMT_nuNC->GetXaxis()->SetTitle("NPE_{LPMT}^{CD}");
  Npe_LPMT_nuNC->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_nuNC->GetXaxis()->SetLabelSize(0.05);
  Npe_LPMT_nuNC->GetYaxis()->SetTitle("entries");
  Npe_LPMT_nuNC->GetYaxis()->SetLabelSize(0.05);
  Npe_LPMT_nuNC->GetYaxis()->SetTitleOffset(1.2);
  Npe_LPMT_nuNC->SetLineWidth(5);
  Npe_LPMT_nuNC->SetLineColor(kSpring-1);
  Npe_LPMT_nuNC->SetFillColor(kSpring-1);
  Npe_LPMT_nuNC->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_nuNC","(trueNPE_LPMT_CD)","NCint==1 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");  
  leg80->AddEntry(Npe_LPMT_nuNC, "#nu_{x} NC" ,"l");
  Npe_LPMT_nuNC->Draw("same");
  leg80->Draw();
  c80->SaveAs("Plot/NPE_LPMT_effFidCut_0-20GeV_16volcut_1m.png");
  c80->SaveAs("Plot/NPE_LPMT_effFidCut_0-20GeV_16volcut_1m.pdf");
  c80->SaveAs("Plot/NPE_LPMT_effFidCut_0-20GeV_16volcut_1m.C");

  /////////////////////////////LOGPLOTS//////////////////////////////////////////////////////

  TCanvas *c81 = new TCanvas("c81","",1000,600);
  TLegend * leg81 = new TLegend(0.65,0.9,0.9,0.6);
  c81->cd();
  TH1F *Lognpe_LPMT_numuCC = new TH1F("Lognpe_LPMT_numuCC","",100,5.0,7.3);
  gPad->SetLogy();
  Lognpe_LPMT_numuCC->SetLineWidth(5);
  Lognpe_LPMT_numuCC->SetLineColor(kBlue+2);
  Lognpe_LPMT_numuCC->SetFillColor(kBlue+2);
  Lognpe_LPMT_numuCC->SetFillStyle(3002);
  Lognpe_LPMT_numuCC->GetXaxis()->SetTitle("Log_{10} (NPE_{LPMT}^{CD})");
  Lognpe_LPMT_numuCC->GetXaxis()->SetTitleSize(0.05);
  Lognpe_LPMT_numuCC->GetXaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_numuCC->GetYaxis()->SetTitle("entries");
  Lognpe_LPMT_numuCC->GetYaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_numuCC->GetYaxis()->SetTitleOffset(1.2);
  mytree->Project("Lognpe_LPMT_numuCC","log10(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  leg81->AddEntry(Lognpe_LPMT_numuCC, "#nu_{#mu} CC" ,"l");
  Lognpe_LPMT_numuCC->Draw();
  TH1F *Lognpe_LPMT_nueCC = new TH1F("Lognpe_LPMT_nueCC","",100,5.0,7.3);
  Lognpe_LPMT_nueCC->GetXaxis()->SetTitle("Log_{10} (NPE_{LPMT}^{CD})");
  Lognpe_LPMT_nueCC->GetXaxis()->SetTitleSize(0.05);
  Lognpe_LPMT_nueCC->GetXaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_nueCC->GetYaxis()->SetTitle("entries");
  Lognpe_LPMT_nueCC->GetYaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_nueCC->GetYaxis()->SetTitleOffset(1.2);
  Lognpe_LPMT_nueCC->SetLineWidth(5);
  Lognpe_LPMT_nueCC->SetLineColor(kRed);
  Lognpe_LPMT_nueCC->SetFillColor(kRed);
  Lognpe_LPMT_nueCC->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_nueCC","log10(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  leg81->AddEntry(Lognpe_LPMT_nueCC, "#nu_{e} CC" ,"l");
  Lognpe_LPMT_nueCC->Draw("same");
  TH1F *Lognpe_LPMT_nuNC = new TH1F("Lognpe_LPMT_nuNC","",100,5.0,7.3);
  Lognpe_LPMT_nuNC->GetXaxis()->SetTitle("Log_{10} (NPE_{LPMT}^{CD})");
  Lognpe_LPMT_nuNC->GetXaxis()->SetTitleSize(0.05);
  Lognpe_LPMT_nuNC->GetXaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_nuNC->GetYaxis()->SetTitle("entries");
  Lognpe_LPMT_nuNC->GetYaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_nuNC->GetYaxis()->SetTitleOffset(1.2);
  Lognpe_LPMT_nuNC->SetLineWidth(5);
  Lognpe_LPMT_nuNC->SetLineColor(kSpring-1);
  Lognpe_LPMT_nuNC->SetFillColor(kSpring-1);
  Lognpe_LPMT_nuNC->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_nuNC","log10(trueNPE_LPMT_CD)","NCint==1 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");  
  leg81->AddEntry(Lognpe_LPMT_nuNC, "#nu_{x} NC" ,"l");
  Lognpe_LPMT_nuNC->Draw("same");
  leg81->Draw();
  c81->SaveAs("Plot/LOGNPE_LPMT_effFidCut_0-20GeV_16volcut_1m.png");
  c81->SaveAs("Plot/LOGNPE_LPMT_effFidCut_0-20GeV_16volcut_1m.pdf");
  c81->SaveAs("Plot/LOGNPE_LPMT_effFidCut_0-20GeV_16volcut_1m.C");

  
}
