void makeallspectrum_cuts_flav() {
  gStyle->SetOptStat(0);
  gStyle->SetPadBottomMargin(0.12);
  gStyle->SetTitleH(0.1);
  gStyle->SetTitleW(1.05);

  static const int binsE_nuE = 10;
  static const int binsNPE_nuE = 10;
  static const int binsE_nuMu = 8;
  static const int binsNPE_nuMu = 8;
  static const float lowE_nuE = -1.0;
  static const float lowNPE_nuE = 5.0;
  static const float upE_nuE = 1.2;
  static const float upNPE_nuE = 7.2;
  static const float lowE_nuMu = -0.3;
  static const float lowNPE_nuMu = 5.7;
  static const float upE_nuMu = 1.2;
  static const float upNPE_nuMu = 7.2;

  TTree *mytree;
  TFile *_file1 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/treemaker/trees/MC_500K_1m_TOT_FULL.root");
  //TFile *_file1 = TFile::Open("/home/sgiulio/Giulio/University/JUNO/juno-unfolding/treemaker/trees/MC_100K_1m_SHORT.root");
  _file1->GetObject("Data",mytree);

  //////////////////////////////////LOGPLOTS-Ev//////////////////////////

  TCanvas *c17 = new TCanvas("c17","",800,600);
  TLegend * leg6 = new TLegend(0.35,0.15,0.6,0.4);
  TH1F *logEv_Nue = new TH1F("logEv_Nue","",binsE_nuE,lowE_nuE,upE_nuE);
  logEv_Nue->GetXaxis()->SetTitle("log_{10}(E_{#nu} [GeV])");
  logEv_Nue->GetXaxis()->SetTitleSize(0.05);
  logEv_Nue->GetXaxis()->SetLabelSize(0.04);
  logEv_Nue->GetYaxis()->SetTitle("entries");
  logEv_Nue->GetYaxis()->SetLabelSize(0.05);
  logEv_Nue->GetYaxis()->SetTitleOffset(1.2);
  logEv_Nue->GetYaxis()->SetRangeUser(1.,50000.);
  logEv_Nue->SetLineWidth(5);
  logEv_Nue->SetLineColor(kOrange+1);
  logEv_Nue->SetFillColor(kOrange+1);
  logEv_Nue->SetFillStyle(3002);
  mytree->Project("logEv_Nue","log10(nuEnergy/1000.)","((CCint==1 && abs(init_lepID)==11) || (NCint==1 && abs(init_lepID)==12))","");
  logEv_Nue->Draw();
  TH1F *logEv_Nue_fidcut = new TH1F("logEv_Nue_fidcut","",binsE_nuE,lowE_nuE,upE_nuE);
  logEv_Nue_fidcut->SetLineWidth(5);
  logEv_Nue_fidcut->SetLineColor(kAzure+1);
  logEv_Nue_fidcut->SetFillColor(kAzure+1);
  logEv_Nue_fidcut->SetFillStyle(3002);
  mytree->Project("logEv_Nue_fidcut","log10(nuEnergy/1000.)","((CCint==1 && abs(init_lepID)==11) || (NCint==1 && abs(init_lepID)==12)) && newVradius<16000. && trueNPE_LPMT_WP < 60.","");
  logEv_Nue_fidcut->Draw("same");
  TH1F *logEv_Nue_timecut = new TH1F("logEv_Nue_timecut","",binsE_nuE,lowE_nuE,upE_nuE);
  logEv_Nue_timecut->GetXaxis()->SetTitle("log_{10}(E_{#nu} [GeV])");
  logEv_Nue_timecut->SetLineWidth(5);
  logEv_Nue_timecut->SetLineColor(kRed);
  logEv_Nue_timecut->SetFillColor(kRed);
  logEv_Nue_timecut->SetFillStyle(3002);
  mytree->Project("logEv_Nue_timecut","log10(nuEnergy/1000.)","Tres_RMS<75 && ((CCint==1 && abs(init_lepID)==11) || (NCint==1 && abs(init_lepID)==12)) && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.0","");
  logEv_Nue_timecut->Draw("same");
  TH1F *logEv_bkg1 = new TH1F("logEv_bkg1","",binsE_nuE,lowE_nuE,upE_nuE);
  logEv_bkg1->GetXaxis()->SetTitle("log_{10}(E_{#nu} [GeV])");
  gPad->SetLogy();
  logEv_bkg1->SetLineWidth(5);
  logEv_bkg1->SetLineColor(kGreen+3);
  logEv_bkg1->SetFillColor(kGreen+3);
  logEv_bkg1->SetFillStyle(3002);
  mytree->Project("logEv_bkg1","log10(nuEnergy/1000.)","Tres_RMS<75 && abs(init_lepID)!=11 && abs(init_lepID)!=12 && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.0","");
  c17->cd();
  logEv_bkg1->Draw("same");
  leg6->AddEntry(logEv_Nue, "#nu_{e} - inj." ,"l");
  leg6->AddEntry(logEv_Nue_fidcut, "#nu_{e} - fid." ,"l");
  leg6->AddEntry(logEv_Nue_timecut, "#nu_{e} - sel." ,"l");  
  leg6->AddEntry(logEv_bkg1, "Res. bkg" ,"l");
  leg6->Draw();
  c17->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_FLAV_less75nscut.png");
  c17->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_FLAV_less75nscut.pdf");
  c17->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_FLAV_less75nscut.C");
  c17->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_FLAV_less75nscut.root");

  ///////////////////////////////////////////////////////////////////////////////////

  TCanvas *c18 = new TCanvas("c18","",800,600);
  TLegend * leg7 = new TLegend(0.35,0.15,0.6,0.4);
  TH1F *logEv_Numu = new TH1F("logEv_Numu","",binsE_nuMu,lowE_nuMu,upE_nuMu);
  logEv_Numu->GetXaxis()->SetTitle("log_{10}(E_{#nu} [GeV])");
  logEv_Numu->GetXaxis()->SetTitleSize(0.05);
  logEv_Numu->GetXaxis()->SetLabelSize(0.04);
  logEv_Numu->GetYaxis()->SetTitle("entries");
  logEv_Numu->GetYaxis()->SetLabelSize(0.05);
  logEv_Numu->GetYaxis()->SetTitleOffset(1.2);
  logEv_Numu->GetYaxis()->SetRangeUser(5.,80000.);
  logEv_Numu->SetLineWidth(5);
  logEv_Numu->SetLineColor(kOrange+1);
  logEv_Numu->SetFillColor(kOrange+1);
  logEv_Numu->SetFillStyle(3002);
  mytree->Project("logEv_Numu","log10(nuEnergy/1000.)","((CCint==1 && abs(init_lepID)==13) || (NCint==1 && abs(init_lepID)==14))","");
  logEv_Numu->Draw();
  TH1F *logEv_Numu_fidcut = new TH1F("logEv_Numu_fidcut","",binsE_nuMu,lowE_nuMu,upE_nuMu);
  logEv_Numu_fidcut->SetLineWidth(5);
  logEv_Numu_fidcut->SetLineColor(kAzure+1);
  logEv_Numu_fidcut->SetFillColor(kAzure+1);
  logEv_Numu_fidcut->SetFillStyle(3002);
  mytree->Project("logEv_Numu_fidcut","log10(nuEnergy/1000.)","((CCint==1 && abs(init_lepID)==13) || (NCint==1 && abs(init_lepID)==14)) && newVradius<16000. && trueNPE_LPMT_WP < 60.","");
  logEv_Numu_fidcut->Draw("same");
  TH1F *logEv_Numu_timecut = new TH1F("logEv_Numu_timecut","",binsE_nuMu,lowE_nuMu,upE_nuMu);
  logEv_Numu_timecut->GetXaxis()->SetTitle("log_{10}(E_{#nu} [GeV])");
  logEv_Numu_timecut->SetLineWidth(5);
  logEv_Numu_timecut->SetLineColor(kRed);
  logEv_Numu_timecut->SetFillColor(kRed);
  logEv_Numu_timecut->SetFillStyle(3002);
  mytree->Project("logEv_Numu_timecut","log10(nuEnergy/1000.)","Tres_RMS>95 && ((CCint==1 && abs(init_lepID)==13) || (NCint==1 && abs(init_lepID)==14)) && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.7","");
  logEv_Numu_timecut->Draw("same");
  TH1F *logEv_bkg2 = new TH1F("logEv_bkg2","",binsE_nuMu,lowE_nuMu,upE_nuMu);
  logEv_bkg2->GetXaxis()->SetTitle("log_{10}(E_{#nu} [GeV])");
  gPad->SetLogy();
  logEv_bkg2->SetLineWidth(5);
  logEv_bkg2->SetLineColor(kGreen+3);
  logEv_bkg2->SetFillColor(kGreen+3);
  logEv_bkg2->SetFillStyle(3002);
  mytree->Project("logEv_bkg2","log10(nuEnergy/1000.)","Tres_RMS>95 && abs(init_lepID)!=13 && abs(init_lepID)!=14 && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.7","");
  c18->cd();
  logEv_bkg2->Draw("same");
  leg7->AddEntry(logEv_Numu, "#nu_{#mu} - inj." ,"l");
  leg7->AddEntry(logEv_Numu_fidcut, "#nu_{#mu} - fid." ,"l");
  leg7->AddEntry(logEv_Numu_timecut, "#nu_{#mu} - sel." ,"l");
  leg7->AddEntry(logEv_bkg2, "Res. bkg" ,"l");
  leg7->Draw();
  c18->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_FLAV_over95nscut.png");
  c18->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_FLAV_over95nscut.pdf");
  c18->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_FLAV_over95nscut.C");
  c18->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_FLAV_over95nscut.root");

  //////////////////////////////////LOGPLOTS-NPE//////////////////////////

  TCanvas *c117 = new TCanvas("c117","",800,600);
  TLegend * leg16 = new TLegend(0.15,0.15,0.4,0.45);
  TH1F *logNPE_Nue = new TH1F("logNPE_Nue","",binsNPE_nuE,lowNPE_nuE,upNPE_nuE);
  logNPE_Nue->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  logNPE_Nue->GetXaxis()->SetTitleSize(0.05);
  logNPE_Nue->GetXaxis()->SetLabelSize(0.04);
  logNPE_Nue->GetYaxis()->SetTitle("entries");
  logNPE_Nue->GetYaxis()->SetLabelSize(0.05);
  logNPE_Nue->GetYaxis()->SetTitleOffset(1.2);
  logNPE_Nue->GetYaxis()->SetRangeUser(1.,50000.);
  logNPE_Nue->SetLineWidth(5);
  logNPE_Nue->SetLineColor(kOrange+1);
  logNPE_Nue->SetFillColor(kOrange+1);
  logNPE_Nue->SetFillStyle(3002);
  mytree->Project("logNPE_Nue","log10(trueNPE_LPMT_CD)","((CCint==1 && abs(init_lepID)==11) || (NCint==1 && abs(init_lepID)==12))","");
  logNPE_Nue->Draw();
  TH1F *logNPE_Nue_fidcut = new TH1F("logNPE_Nue_fidcut","",binsNPE_nuE,lowNPE_nuE,upNPE_nuE);
  logNPE_Nue_fidcut->SetLineWidth(5);
  logNPE_Nue_fidcut->SetLineColor(kAzure+1);
  logNPE_Nue_fidcut->SetFillColor(kAzure+1);
  logNPE_Nue_fidcut->SetFillStyle(3002);
  mytree->Project("logNPE_Nue_fidcut","log10(trueNPE_LPMT_CD)","((CCint==1 && abs(init_lepID)==11) || (NCint==1 && abs(init_lepID)==12)) && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.0","");
  logNPE_Nue_fidcut->Draw("same");
  TH1F *logNPE_all_timecut = new TH1F("logNPE_all_timecut","",binsNPE_nuE,lowNPE_nuE,upNPE_nuE);
  logNPE_all_timecut->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  logNPE_all_timecut->SetLineWidth(5);
  logNPE_all_timecut->SetLineColor(kGray+3);
  logNPE_all_timecut->SetFillColor(kGray+3);
  logNPE_all_timecut->SetFillStyle(3002);
  mytree->Project("logNPE_all_timecut","log10(trueNPE_LPMT_CD)","Tres_RMS<75 && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.0","");
  //logNPE_all_timecut->Draw("same");
  TH1F *logNPE_Nue_timecut = new TH1F("logNPE_Nue_timecut","",binsNPE_nuE,lowNPE_nuE,upNPE_nuE);
  logNPE_Nue_timecut->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  logNPE_Nue_timecut->SetLineWidth(5);
  logNPE_Nue_timecut->SetLineColor(kRed);
  logNPE_Nue_timecut->SetFillColor(kRed);
  logNPE_Nue_timecut->SetFillStyle(3002);
  mytree->Project("logNPE_Nue_timecut","log10(trueNPE_LPMT_CD)","Tres_RMS<75 && ((CCint==1 && abs(init_lepID)==11) || (NCint==1 && abs(init_lepID)==12)) && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.0","");
  logNPE_Nue_timecut->Draw("same");
  TH1F *logNPE_bkg1 = new TH1F("logNPE_bkg1","",binsNPE_nuE,lowNPE_nuE,upNPE_nuE);
  logNPE_bkg1->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  gPad->SetLogy();
  logNPE_bkg1->SetLineWidth(5);
  logNPE_bkg1->SetLineColor(kGreen+3);
  logNPE_bkg1->SetFillColor(kGreen+3);
  logNPE_bkg1->SetFillStyle(3002);
  mytree->Project("logNPE_bkg1","log10(trueNPE_LPMT_CD)","Tres_RMS<75 && abs(init_lepID)!=11 && abs(init_lepID)!=12 && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.0","");
  c117->cd();
  logNPE_bkg1->Draw("same");
  leg16->AddEntry(logNPE_Nue, "#nu_{e}" ,"l");
  leg16->AddEntry(logNPE_Nue_fidcut, "#nu_{e} fid." ,"l");
  leg16->AddEntry(logNPE_Nue_timecut, "#nu_{e} sel." ,"l");  
  leg16->AddEntry(logNPE_bkg1, "res. bkg" ,"l");
  leg16->Draw();
  c117->SaveAs("Plot/logNPE_eff_0-20GeV_16volcut_1m_FLAV_less75nscut.png");
  c117->SaveAs("Plot/logNPE_eff_0-20GeV_16volcut_1m_FLAV_less75nscut.pdf");
  c117->SaveAs("Plot/logNPE_eff_0-20GeV_16volcut_1m_FLAV_less75nscut.C");

  ///////////////////////////////////////////////////////////////////////////////////

  TCanvas *c118 = new TCanvas("c118","",800,600);
  TLegend * leg17 = new TLegend(0.15,0.15,0.4,0.45);
  TH1F *logNPE_Numu = new TH1F("logNPE_Numu","",binsNPE_nuMu,lowNPE_nuMu,upNPE_nuMu);
  logNPE_Numu->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  logNPE_Numu->GetXaxis()->SetTitleSize(0.05);
  logNPE_Numu->GetXaxis()->SetLabelSize(0.04);
  logNPE_Numu->GetYaxis()->SetTitle("entries");
  logNPE_Numu->GetYaxis()->SetLabelSize(0.05);
  logNPE_Numu->GetYaxis()->SetTitleOffset(1.2);
  logNPE_Numu->GetYaxis()->SetRangeUser(1.,50000.);
  logNPE_Numu->SetLineWidth(5);
  logNPE_Numu->SetLineColor(kOrange+1);
  logNPE_Numu->SetFillColor(kOrange+1);
  logNPE_Numu->SetFillStyle(3002);
  mytree->Project("logNPE_Numu","log10(trueNPE_LPMT_CD)","((CCint==1 && abs(init_lepID)==13) || (NCint==1 && abs(init_lepID)==14))","");
  logNPE_Numu->Draw();
  TH1F *logNPE_Numu_fidcut = new TH1F("logNPE_Numu_fidcut","",binsNPE_nuMu,lowNPE_nuMu,upNPE_nuMu);
  logNPE_Numu_fidcut->SetLineWidth(5);
  logNPE_Numu_fidcut->SetLineColor(kAzure+1);
  logNPE_Numu_fidcut->SetFillColor(kAzure+1);
  logNPE_Numu_fidcut->SetFillStyle(3002);
  mytree->Project("logNPE_Numu_fidcut","log10(trueNPE_LPMT_CD)","((CCint==1 && abs(init_lepID)==13) || (NCint==1 && abs(init_lepID)==14)) && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.7","");
  logNPE_Numu_fidcut->Draw("same");
  TH1F *logNPE_Numu_timecut = new TH1F("logNPE_Numu_timecut","",binsNPE_nuMu,lowNPE_nuMu,upNPE_nuMu);
  logNPE_Numu_timecut->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  logNPE_Numu_timecut->SetLineWidth(5);
  logNPE_Numu_timecut->SetLineColor(kRed);
  logNPE_Numu_timecut->SetFillColor(kRed);
  logNPE_Numu_timecut->SetFillStyle(3002);
  mytree->Project("logNPE_Numu_timecut","log10(trueNPE_LPMT_CD)","Tres_RMS>95 && ((CCint==1 && abs(init_lepID)==13) || (NCint==1 && abs(init_lepID)==14)) && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.7","");
  logNPE_Numu_timecut->Draw("same");
  TH1F *logNPE_bkg2 = new TH1F("logNPE_bkg2","",binsNPE_nuMu,lowNPE_nuMu,upNPE_nuMu);
  logNPE_bkg2->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  gPad->SetLogy();
  logNPE_bkg2->SetLineWidth(5);
  logNPE_bkg2->SetLineColor(kGreen+3);
  logNPE_bkg2->SetFillColor(kGreen+3);
  logNPE_bkg2->SetFillStyle(3002);
  mytree->Project("logNPE_bkg2","log10(trueNPE_LPMT_CD)","Tres_RMS>95 && abs(init_lepID)!=13 && abs(init_lepID)!=14 && newVradius<16000. && trueNPE_LPMT_WP < 60. && log10(trueNPE_LPMT_CD) > 5.7","");
  c118->cd();
  logNPE_bkg2->Draw("same");
  leg17->AddEntry(logNPE_Numu, "#nu_{#mu} FC" ,"l");
  leg17->AddEntry(logNPE_Numu_fidcut, "#nu_{#mu} FC fid." ,"l");
  leg17->AddEntry(logNPE_Numu_timecut, "#nu_{#mu} FC sel." ,"l");
  leg17->AddEntry(logNPE_bkg2, "res. bkg" ,"l");
  leg17->Draw();
  c118->SaveAs("Plot/logNPE_eff_0-20GeV_16volcut_1m_FLAV_over95nscut.png");
  c118->SaveAs("Plot/logNPE_eff_0-20GeV_16volcut_1m_FLAV_over95nscut.pdf");
  c118->SaveAs("Plot/logNPE_eff_0-20GeV_16volcut_1m_FLAV_over95nscut.C");

}
