void makespectrum_cuts() {
  gStyle->SetOptStat(0);
  gStyle->SetPadBottomMargin(0.12);
  gStyle->SetTitleH(0.1);
  gStyle->SetTitleW(1.05);

  TTree *mytree;
  TFile *_file1 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/treemaker/trees/MC_500K_1m_TOT.root");
  //TFile *_file1 = TFile::Open("/home/sgiulio/Giulio/University/JUNO/juno-unfolding/treemaker/trees/MC_100K_1m_FULL.root");
  _file1->GetObject("Data",mytree);

  TCanvas *c15 = new TCanvas("c15","",800,600);
  TLegend * leg4 = new TLegend(0.65,0.9,0.9,0.6);
  TH1F *Npe_LPMT_nueCC = new TH1F("Npe_LPMT_nueCC","",35,0.,3.0E7);
  Npe_LPMT_nueCC->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_LPMT_nueCC->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_nueCC->GetXaxis()->SetLabelSize(0.05);
  Npe_LPMT_nueCC->GetYaxis()->SetTitle("entries");
  Npe_LPMT_nueCC->GetYaxis()->SetLabelSize(0.05);
  Npe_LPMT_nueCC->GetYaxis()->SetTitleOffset(1.2);
  Npe_LPMT_nueCC->SetLineWidth(5);
  Npe_LPMT_nueCC->SetLineColor(kAzure+1);
  Npe_LPMT_nueCC->SetFillColor(kAzure+1);
  Npe_LPMT_nueCC->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_nueCC","(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  Npe_LPMT_nueCC->Draw();
  TH1F *Npe_LPMT_nueCC_cut = new TH1F("Npe_LPMT_nueCC_cut","",35,0.,3.0E7);
  Npe_LPMT_nueCC_cut->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_LPMT_nueCC_cut->SetLineWidth(5);
  Npe_LPMT_nueCC_cut->SetLineColor(kRed);
  Npe_LPMT_nueCC_cut->SetFillColor(kRed);
  Npe_LPMT_nueCC_cut->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_nueCC_cut","(trueNPE_LPMT_CD)","Tres_RMS<75 && CCint==1 && abs(init_lepID)==11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  Npe_LPMT_nueCC_cut->Draw("same");
  TH1F *Npe_LPMT_bkg1 = new TH1F("Npe_LPMT_bkg1","",35,0.,3.0E7);
  Npe_LPMT_bkg1->GetXaxis()->SetTitle("NPE_{LPMT}");
  gPad->SetLogy();
  Npe_LPMT_bkg1->SetLineWidth(5);
  Npe_LPMT_bkg1->SetLineColor(kGreen+3);
  Npe_LPMT_bkg1->SetFillColor(kGreen+3);
  Npe_LPMT_bkg1->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_bkg1","(trueNPE_LPMT_CD)","Tres_RMS<75 && abs(init_lepID)!=11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  c15->cd();
  Npe_LPMT_bkg1->Draw("same");
  leg4->AddEntry(Npe_LPMT_nueCC, "#nu_{e} CC" ,"l");
  leg4->AddEntry(Npe_LPMT_nueCC_cut, "#nu_{e} CC sel." ,"l");  
  leg4->AddEntry(Npe_LPMT_bkg1, "res. bkg" ,"l");
  leg4->Draw();
  c15->SaveAs("Plot/NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.png");
  c15->SaveAs("Plot/NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.pdf");
  c15->SaveAs("Plot/NPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.C");
  ///////////////////////////////////////////////////////////////////////////////////
  
  TCanvas *c25 = new TCanvas("c25","",800,600);
  TLegend * leg14 = new TLegend(0.65,0.9,0.9,0.6);
  TH1F *Npe_LPMT_numuCC = new TH1F("Npe_LPMT_numuCC","",35,0.,3.0E7);
  gPad->SetLogy();
  Npe_LPMT_numuCC->SetLineWidth(5);
  Npe_LPMT_numuCC->SetLineColor(kAzure+1);
  Npe_LPMT_numuCC->SetFillColor(kAzure+1);
  Npe_LPMT_numuCC->SetFillStyle(3002);
  Npe_LPMT_numuCC->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_LPMT_numuCC->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_numuCC->GetXaxis()->SetLabelSize(0.05);
  Npe_LPMT_numuCC->GetYaxis()->SetTitle("entries");
  Npe_LPMT_numuCC->GetYaxis()->SetLabelSize(0.05);
  Npe_LPMT_numuCC->GetYaxis()->SetTitleOffset(1.2);
  mytree->Project("Npe_LPMT_numuCC","(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  leg14->AddEntry(Npe_LPMT_numuCC, "#nu_{#mu} CC" ,"l");
  TH1F *Npe_LPMT_numuCC_cut = new TH1F("Npe_LPMT_numuCC_cut","",35,0.,3.0E7);
  Npe_LPMT_numuCC_cut->GetXaxis()->SetTitle("NPE_{LPMT}");
  gPad->SetLogy();
  Npe_LPMT_numuCC_cut->SetLineWidth(5);
  Npe_LPMT_numuCC_cut->SetLineColor(kRed);
  Npe_LPMT_numuCC_cut->SetFillColor(kRed);
  Npe_LPMT_numuCC_cut->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_numuCC_cut","(trueNPE_LPMT_CD)","Tres_RMS>95 && CCint==1 && abs(init_lepID)==13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  leg14->AddEntry(Npe_LPMT_numuCC_cut, "#nu_{#mu} CC sel." ,"l");
  TH1F *Npe_LPMT_bkg2 = new TH1F("Npe_LPMT_bkg2","",35,0.,3.0E7);
  Npe_LPMT_bkg2->GetXaxis()->SetTitle("NPE_{LPMT}");
  gPad->SetLogy();
  Npe_LPMT_bkg2->SetLineWidth(5);
  Npe_LPMT_bkg2->SetLineColor(kGreen+3);
  Npe_LPMT_bkg2->SetFillColor(kGreen+3);
  Npe_LPMT_bkg2->SetFillStyle(3002);
  mytree->Project("Npe_LPMT_bkg2","(trueNPE_LPMT_CD)","Tres_RMS>95 && abs(init_lepID)!=13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  c25->cd();
  Npe_LPMT_numuCC->Draw();
  Npe_LPMT_numuCC_cut->Draw("same");
  Npe_LPMT_bkg2->Draw("same");
  leg14->AddEntry(Npe_LPMT_bkg2, "res. bkg" ,"l");
  leg14->Draw();
  c25->SaveAs("Plot/NPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.png");
  c25->SaveAs("Plot/NPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.pdf");
  c25->SaveAs("Plot/NPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.C");

  //////////////////////////////////LOGPLOTS//////////////////////////

  TCanvas *c7 = new TCanvas("c7","",800,600);
  TLegend * leg8 = new TLegend(0.7,0.9,0.9,0.65);
  TH1F *Lognpe_LPMT_nueCC = new TH1F("Lognpe_LPMT_nueCC","",35,5.0,7.75);
  Lognpe_LPMT_nueCC->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  Lognpe_LPMT_nueCC->GetXaxis()->SetTitleSize(0.05);
  Lognpe_LPMT_nueCC->GetXaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_nueCC->GetYaxis()->SetTitle("entries");
  Lognpe_LPMT_nueCC->GetYaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_nueCC->GetYaxis()->SetTitleOffset(1.2);
  Lognpe_LPMT_nueCC->SetLineWidth(5);
  Lognpe_LPMT_nueCC->SetLineColor(kAzure+1);
  Lognpe_LPMT_nueCC->SetFillColor(kAzure+1);
  Lognpe_LPMT_nueCC->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_nueCC","log10(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  Lognpe_LPMT_nueCC->Draw();
  TH1F *Lognpe_LPMT_nueCC_cut = new TH1F("Lognpe_LPMT_nueCC_cut","",35,5.0,7.75);
  Lognpe_LPMT_nueCC_cut->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  Lognpe_LPMT_nueCC_cut->SetLineWidth(5);
  Lognpe_LPMT_nueCC_cut->SetLineColor(kRed);
  Lognpe_LPMT_nueCC_cut->SetFillColor(kRed);
  Lognpe_LPMT_nueCC_cut->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_nueCC_cut","log10(trueNPE_LPMT_CD)","Tres_RMS<75 && CCint==1 && abs(init_lepID)==11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  Lognpe_LPMT_nueCC_cut->Draw("same");
  TH1F *Lognpe_LPMT_bkg1 = new TH1F("Lognpe_LPMT_bkg1","",35,5.0,7.75);
  Lognpe_LPMT_bkg1->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  gPad->SetLogy();
  Lognpe_LPMT_bkg1->SetLineWidth(5);
  Lognpe_LPMT_bkg1->SetLineColor(kGreen+3);
  Lognpe_LPMT_bkg1->SetFillColor(kGreen+3);
  Lognpe_LPMT_bkg1->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_bkg1","log10(trueNPE_LPMT_CD)","Tres_RMS<75 && abs(init_lepID)!=11 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 1.E5","");
  c7->cd();
  Lognpe_LPMT_bkg1->Draw("same");
  leg8->AddEntry(Lognpe_LPMT_nueCC, "#nu_{e} CC" ,"l");
  leg8->AddEntry(Lognpe_LPMT_nueCC_cut, "#nu_{e} CC sel." ,"l");  
  leg8->AddEntry(Lognpe_LPMT_bkg1, "res. bkg" ,"l");
  leg8->Draw();
  c7->SaveAs("Plot/LOGNPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.png");
  c7->SaveAs("Plot/LOGNPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.pdf");
  c7->SaveAs("Plot/LOGNPE_LPMT_eff_0-20GeV_16volcut_1m_less75nscut_withfidcut.C");
  ///////////////////////////////////////////////////////////////////////////////////
  
  TCanvas *c17 = new TCanvas("c17","",800,600);
  TLegend * leg18 = new TLegend(0.7,0.9,0.9,0.65);
  TH1F *Lognpe_LPMT_numuCC = new TH1F("Lognpe_LPMT_numuCC","",35,5.7,7.75);
  gPad->SetLogy();
  Lognpe_LPMT_numuCC->SetLineWidth(5);
  Lognpe_LPMT_numuCC->SetLineColor(kAzure+1);
  Lognpe_LPMT_numuCC->SetFillColor(kAzure+1);
  Lognpe_LPMT_numuCC->SetFillStyle(3002);
  Lognpe_LPMT_numuCC->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  Lognpe_LPMT_numuCC->GetXaxis()->SetTitleSize(0.05);
  Lognpe_LPMT_numuCC->GetXaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_numuCC->GetYaxis()->SetTitle("entries");
  Lognpe_LPMT_numuCC->GetYaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_numuCC->GetYaxis()->SetTitleOffset(1.2);
  mytree->Project("Lognpe_LPMT_numuCC","log10(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  leg18->AddEntry(Lognpe_LPMT_numuCC, "#nu_{#mu} CC" ,"l");
  TH1F *Lognpe_LPMT_numuCC_cut = new TH1F("Lognpe_LPMT_numuCC_cut","",35,5.7,7.75);
  Lognpe_LPMT_numuCC_cut->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  gPad->SetLogy();
  Lognpe_LPMT_numuCC_cut->SetLineWidth(5);
  Lognpe_LPMT_numuCC_cut->SetLineColor(kRed);
  Lognpe_LPMT_numuCC_cut->SetFillColor(kRed);
  Lognpe_LPMT_numuCC_cut->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_numuCC_cut","log10(trueNPE_LPMT_CD)","Tres_RMS>95 && CCint==1 && abs(init_lepID)==13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  leg18->AddEntry(Lognpe_LPMT_numuCC_cut, "#nu_{#mu} CC sel." ,"l");
  TH1F *Lognpe_LPMT_bkg2 = new TH1F("Lognpe_LPMT_bkg2","",35,5.7,7.75);
  Lognpe_LPMT_bkg2->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  gPad->SetLogy();
  Lognpe_LPMT_bkg2->SetLineWidth(5);
  Lognpe_LPMT_bkg2->SetLineColor(kGreen+3);
  Lognpe_LPMT_bkg2->SetFillColor(kGreen+3);
  Lognpe_LPMT_bkg2->SetFillStyle(3002);
  mytree->Project("Lognpe_LPMT_bkg2","log10(trueNPE_LPMT_CD)","Tres_RMS>95 && abs(init_lepID)!=13 && newVradius<16000. && trueNPE_LPMT_WP < 60. && trueNPE_LPMT_CD > 5.E5","");
  c17->cd();
  Lognpe_LPMT_numuCC->Draw();
  Lognpe_LPMT_numuCC_cut->Draw("same");
  Lognpe_LPMT_bkg2->Draw("same");
  leg18->AddEntry(Lognpe_LPMT_bkg2, "res. bkg" ,"l");
  leg18->Draw();
  c17->SaveAs("Plot/LOGNPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.png");
  c17->SaveAs("Plot/LOGNPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.pdf");
  c17->SaveAs("Plot/LOGNPE_LPMT_eff_0-20GeV_16volcut_1m_over95nscut_withfidcut.C");

  ///////////////////////////////S/S+B////////////////////////////////////////////////

  TCanvas *c67 = new TCanvas("c67","",800,600);
  TH1F *Npe_LPMT_nueCC_DEN = (TH1F*)Npe_LPMT_nueCC_cut->Clone("Npe_LPMT_nueCC_DEN");
  TH1F *Npe_LPMT_nueCC_SB = (TH1F*)Npe_LPMT_nueCC_cut->Clone("Npe_LPMT_nueCC_SB");
  Npe_LPMT_nueCC_SB->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_LPMT_nueCC_SB->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_nueCC_SB->GetXaxis()->SetLabelSize(0.05);
  Npe_LPMT_nueCC_SB->GetYaxis()->SetTitle("S/(S+B)");
  Npe_LPMT_nueCC_SB->GetYaxis()->SetLabelSize(0.05);
  Npe_LPMT_nueCC_SB->GetYaxis()->SetTitleOffset(1.2);
  Npe_LPMT_nueCC_SB->SetLineWidth(5);
  Npe_LPMT_nueCC_SB->SetLineColor(kRed);
  Npe_LPMT_nueCC_SB->SetFillColor(0);
  Npe_LPMT_nueCC_DEN->Add(Npe_LPMT_bkg1);
  Npe_LPMT_nueCC_SB->Divide(Npe_LPMT_nueCC_DEN);
  c67->cd();
  Npe_LPMT_nueCC_SB->Draw();
  c67->SaveAs("Plot/NPE_LPMT_nueCC_SB_0-20GeV_16volcut_1m_less75nscut_withfidcut.png");
  c67->SaveAs("Plot/NPE_LPMT_nueCC_SB_0-20GeV_16volcut_1m_less75nscut_withfidcut.pdf");
  c67->SaveAs("Plot/NPE_LPMT_nueCC_SB_0-20GeV_16volcut_1m_less75nscut_withfidcut.C");

  TCanvas *c55 = new TCanvas("c55","",800,600);
  TH1F *Npe_LPMT_numuCC_DEN = (TH1F*)Npe_LPMT_numuCC_cut->Clone("Npe_LPMT_numuCC_DEN");
  TH1F *Npe_LPMT_numuCC_SB = (TH1F*)Npe_LPMT_numuCC_cut->Clone("Npe_LPMT_numuCC_SB");
  Npe_LPMT_numuCC_SB->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_LPMT_numuCC_SB->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_numuCC_SB->GetXaxis()->SetLabelSize(0.05);
  Npe_LPMT_numuCC_SB->GetYaxis()->SetTitle("S/(S+B)");
  Npe_LPMT_numuCC_SB->GetYaxis()->SetLabelSize(0.05);
  Npe_LPMT_numuCC_SB->GetYaxis()->SetTitleOffset(1.2);
  Npe_LPMT_numuCC_SB->SetLineWidth(5);
  Npe_LPMT_numuCC_SB->SetLineColor(kBlue+2);
  Npe_LPMT_numuCC_SB->SetFillColor(0);
  Npe_LPMT_numuCC_DEN->Add(Npe_LPMT_bkg2);
  Npe_LPMT_numuCC_SB->Divide(Npe_LPMT_numuCC_DEN);
  c55->cd();
  Npe_LPMT_numuCC_SB->Draw();
  c55->SaveAs("Plot/NPE_LPMT_numuCC_SB_0-20GeV_16volcut_1m_over95nscut_withfidcut.png");
  c55->SaveAs("Plot/NPE_LPMT_numuCC_SB_0-20GeV_16volcut_1m_over95nscut_withfidcut.pdf");
  c55->SaveAs("Plot/NPE_LPMT_numuCC_SB_0-20GeV_16volcut_1m_over95nscut_withfidcut.C");

  TCanvas *c89 = new TCanvas("c89","",800,600);
  TH1F *Lognpe_LPMT_nueCC_DEN = (TH1F*)Lognpe_LPMT_nueCC_cut->Clone("Lognpe_LPMT_nueCC_DEN");
  TH1F *Lognpe_LPMT_nueCC_SB = (TH1F*)Lognpe_LPMT_nueCC_cut->Clone("Lognpe_LPMT_nueCC_SB");
  Lognpe_LPMT_nueCC_SB->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  Lognpe_LPMT_nueCC_SB->GetXaxis()->SetTitleSize(0.05);
  Lognpe_LPMT_nueCC_SB->GetXaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_nueCC_SB->GetYaxis()->SetTitle("S/(S+B)");
  Lognpe_LPMT_nueCC_SB->GetYaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_nueCC_SB->GetYaxis()->SetTitleOffset(1.2);
  Lognpe_LPMT_nueCC_SB->SetLineWidth(5);
  Lognpe_LPMT_nueCC_SB->SetLineColor(kRed);
  Lognpe_LPMT_nueCC_SB->SetFillColor(0);
  Lognpe_LPMT_nueCC_DEN->Add(Lognpe_LPMT_bkg1);
  Lognpe_LPMT_nueCC_SB->Divide(Lognpe_LPMT_nueCC_DEN);
  c89->cd();
  Lognpe_LPMT_nueCC_SB->Draw();
  c89->SaveAs("Plot/LOGNPE_LPMT_nueCC_SB_0-20GeV_16volcut_1m_less75nscut_withfidcut.png");
  c89->SaveAs("Plot/LOGNPE_LPMT_nueCC_SB_0-20GeV_16volcut_1m_less75nscut_withfidcut.pdf");
  c89->SaveAs("Plot/LOGNPE_LPMT_nueCC_SB_0-20GeV_16volcut_1m_less75nscut_withfidcut.C");

  TCanvas *c45 = new TCanvas("c45","",800,600);
  TH1F *Lognpe_LPMT_numuCC_DEN = (TH1F*)Lognpe_LPMT_numuCC_cut->Clone("Lognpe_LPMT_numuCC_DEN");
  TH1F *Lognpe_LPMT_numuCC_SB = (TH1F*)Lognpe_LPMT_numuCC_cut->Clone("Lognpe_LPMT_numuCC_SB");
  Lognpe_LPMT_numuCC_SB->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  Lognpe_LPMT_numuCC_SB->GetXaxis()->SetTitleSize(0.05);
  Lognpe_LPMT_numuCC_SB->GetXaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_numuCC_SB->GetYaxis()->SetTitle("S/(S+B)");
  Lognpe_LPMT_numuCC_SB->GetYaxis()->SetLabelSize(0.05);
  Lognpe_LPMT_numuCC_SB->GetYaxis()->SetTitleOffset(1.2);
  Lognpe_LPMT_numuCC_SB->SetLineWidth(5);
  Lognpe_LPMT_numuCC_SB->SetLineColor(kBlue+2);
  Lognpe_LPMT_numuCC_SB->SetFillColor(0);
  Lognpe_LPMT_numuCC_DEN->Add(Lognpe_LPMT_bkg2);
  Lognpe_LPMT_numuCC_SB->Divide(Lognpe_LPMT_numuCC_DEN);
  c45->cd();
  Lognpe_LPMT_numuCC_SB->Draw();
  c45->SaveAs("Plot/LOGNPE_LPMT_numuCC_SB_0-20GeV_16volcut_1m_over95nscut_withfidcut.png");
  c45->SaveAs("Plot/LOGNPE_LPMT_numuCC_SB_0-20GeV_16volcut_1m_over95nscut_withfidcut.pdf");
  c45->SaveAs("Plot/LOGNPE_LPMT_numuCC_SB_0-20GeV_16volcut_1m_over95nscut_withfidcut.C");
  
}
