void makeplots_nu_all() {
  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);

  TFile *_file1 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/treemaker/trees/MC_500K_1m_TOT.root");
  TCanvas *c15 = new TCanvas("c15","",1600,1200);
  TLegend * leg4 = new TLegend(0.75,0.9,0.9,0.75);
  TH1F *Npe_LPMT_nueCC = new TH1F("Npe_LPMT_nueCC","",20,5.,7.3);
  Npe_LPMT_nueCC->GetXaxis()->SetTitle("log_{10}(N_{PE})");
  gPad->SetLogy();
  Npe_LPMT_nueCC->SetLineWidth(2);
  Npe_LPMT_nueCC->SetLineColor(kRed);
  Data->Project("Npe_LPMT_nueCC","log10(trueNPE_LPMT)","Tres_RMS<80 && CCint==1 && abs(init_lepID)==11 && newVradius<16000","");
  Npe_LPMT_nueCC->Draw();
  leg4->AddEntry(Npe_LPMT_nueCC, "#nu_{e} CC" ,"l");
  TH1F *Npe_LPMT_numuCC = new TH1F("Npe_LPMT_numuCC","",20,5.,7.3);
  Npe_LPMT_numuCC->GetXaxis()->SetTitle("log_{10}(N_{PE})");
  Npe_LPMT_numuCC->SetLineWidth(2);
  Npe_LPMT_numuCC->SetLineColor(kBlue);
  Data->Project("Npe_LPMT_numuCC","log10(trueNPE_LPMT)","Tres_RMS<80 && CCint==1 && abs(init_lepID)==13 && newVradius<16000","");
  Npe_LPMT_numuCC->Draw("same");
  leg4->AddEntry(Npe_LPMT_numuCC, "#nu_{#mu} CC" ,"l");
  TH1F *Npe_LPMT_nuNC = new TH1F("Npe_LPMT_nuNC","",20,5.,7.3);
  Npe_LPMT_nuNC->GetXaxis()->SetTitle("log_{10}(N_{PE})");
  gPad->SetLogy();
  Npe_LPMT_nuNC->SetLineWidth(2);
  Npe_LPMT_nuNC->SetLineColor(kSpring-1);
  Data->Project("Npe_LPMT_nuNC","log10(trueNPE_LPMT)","Tres_RMS<80 && NCint==1 && newVradius<16000","");
  c15->cd();
  Npe_LPMT_nuNC->Draw("same");
  leg4->AddEntry(Npe_LPMT_nuNC, "#nu_{e}+#nu_{#mu} NC" ,"l");
  leg4->Draw();
  c15->SaveAs("Plot/logNPE_LPMT_nuall_CC+NC_0-20GeV_16volcut_1m_ALL_80nscut.png");
  c15->SaveAs("Plot/logNPE_LPMT_nuall_CC+NC_0-20GeV_16volcut_1m_ALL_80nscut.pdf");
  c15->SaveAs("Plot/logNPE_LPMT_nuall_CC+NC_0-20GeV_16volcut_1m_ALL_80nscut.C");
  ///////////////////////////////////////////////////////////////////////////////////
  TCanvas *c16 = new TCanvas("c16","",1600,1200);
  TLegend * leg4 = new TLegend(0.75,0.9,0.9,0.75);
  TH1F *Npe_SPMT_nueCC = new TH1F("Npe_SPMT_nueCC","",20,3.,6.05);
  Npe_SPMT_nueCC->GetXaxis()->SetTitle("log_{10}(N_{PE})");
  gPad->SetLogy();
  Npe_SPMT_nueCC->SetLineWidth(2);
  Npe_SPMT_nueCC->SetLineColor(kRed);
  Data->Project("Npe_SPMT_nueCC","log10(trueNPE_SPMT)","Tres_RMS<80 && CCint==1 && abs(init_lepID)==11 && newVradius<16000","");
  Npe_SPMT_nueCC->Draw();
  leg4->AddEntry(Npe_SPMT_nueCC, "#nu_{e} CC" ,"l");
  TH1F *Npe_SPMT_numuCC = new TH1F("Npe_SPMT_numuCC","",20,3.,6.05);
  Npe_SPMT_numuCC->GetXaxis()->SetTitle("log_{10}(N_{PE})");
  Npe_SPMT_numuCC->SetLineWidth(2);
  Npe_SPMT_numuCC->SetLineColor(kBlue);
  Data->Project("Npe_SPMT_numuCC","log10(trueNPE_SPMT)","Tres_RMS<80 && CCint==1 && abs(init_lepID)==13 && newVradius<16000","");
  Npe_SPMT_numuCC->Draw("same");
  leg4->AddEntry(Npe_SPMT_numuCC, "#nu_{#mu} CC" ,"l");
  TH1F *Npe_SPMT_nuNC = new TH1F("Npe_SPMT_nuNC","",20,3.,6.05);
  Npe_SPMT_nuNC->GetXaxis()->SetTitle("log_{10}(N_{PE})");
  gPad->SetLogy();
  Npe_SPMT_nuNC->SetLineWidth(2);
  Npe_SPMT_nuNC->SetLineColor(kSpring-1);
  Data->Project("Npe_SPMT_nuNC","log10(trueNPE_SPMT)","Tres_RMS<80 && NCint==1 && newVradius<16000","");
  c16->cd();
  Npe_SPMT_nuNC->Draw("same");
  leg4->AddEntry(Npe_SPMT_nuNC, "#nu_{e}+#nu_{#mu} NC" ,"l");
  leg4->Draw();
  c16->SaveAs("Plot/logNPE_SPMT_nuall_CC+NC_0-20GeV_16volcut_1m_ALL_80nscut.png");
  c16->SaveAs("Plot/logNPE_SPMT_nuall_CC+NC_0-20GeV_16volcut_1m_ALL_80nscut.pdf");
  c16->SaveAs("Plot/logNPE_SPMT_nuall_CC+NC_0-20GeV_16volcut_1m_ALL_80nscut.C");
  }
