void makeplots_Ev_proc() {
  gStyle->SetOptStat(0);
  gStyle->SetPadBottomMargin(0.12);
  gStyle->SetTitleH(0.1);
  gStyle->SetTitleW(1.05);
  //gStyle->SetOptTitle(0);

  TTree *mytree;
  TFile *_file1 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/treemaker/trees/MC_500K_1m_TOT_NEW.root");
  _file1->GetObject("Data",mytree);

  static const float lowNPE_Nue = 5.0;
  static const float upNPE_Nue = 7.2;
  static const float lowNPE_Numu = 5.7;
  static const float upNPE_Numu = 7.2;
  static const int NPEBINS_Nue = 7;
  static const int NPEBINS_Numu = 8;

  TCanvas *c81 = new TCanvas("c81","",1000,600);
  TLegend * leg81 = new TLegend(0.5,0.45,0.75,0.15);
  TH1F *LogNPE_nuNC = new TH1F("LogNPE_nuNC","",100,5.0,7.2);
  gPad->SetLogy();
  LogNPE_nuNC->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  LogNPE_nuNC->GetYaxis()->SetTitle("entries");
  LogNPE_nuNC->GetXaxis()->SetTitleSize(0.05);
  LogNPE_nuNC->GetXaxis()->SetLabelSize(0.05);
  LogNPE_nuNC->GetYaxis()->SetLabelSize(0.05);
  LogNPE_nuNC->GetYaxis()->SetTitleOffset(1.2);
  LogNPE_nuNC->SetLineWidth(5);
  LogNPE_nuNC->SetLineColor(kSpring-1);
  LogNPE_nuNC->SetFillColor(kSpring-1);
  LogNPE_nuNC->SetFillStyle(3002);
  mytree->Project("LogNPE_nuNC","log10((trueNPE_LPMT_CD-lepEnergy))","NCint==1 && Int_flag != 7 && (trueNPE_LPMT_CD)!=0","");
  c81->cd();
  TH1F *LogNPE_nueCC = new TH1F("LogNPE_nueCC","",NPEBINS_Nue,lowNPE_Nue,upNPE_Nue);
  gPad->SetLogy();
  LogNPE_nueCC->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  LogNPE_nueCC->GetYaxis()->SetTitle("entries");
  LogNPE_nueCC->GetXaxis()->SetTitleSize(0.05);
  LogNPE_nueCC->GetXaxis()->SetLabelSize(0.05);
  LogNPE_nueCC->GetYaxis()->SetLabelSize(0.05);
  LogNPE_nueCC->GetYaxis()->SetTitleOffset(1.2);
  LogNPE_nueCC->SetLineWidth(5);
  LogNPE_nueCC->SetLineColor(kRed);
  LogNPE_nueCC->SetFillColor(kRed);
  LogNPE_nueCC->SetFillStyle(3002);
  mytree->Project("LogNPE_nueCC","log10(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==11","");
  TH1F *LogNPE_numuCC = new TH1F("LogNPE_numuCC","",NPEBINS_Numu,lowNPE_Numu,upNPE_Numu);
  LogNPE_numuCC->GetXaxis()->SetTitle("log_{10} (NPE_{LPMT})");
  LogNPE_numuCC->GetYaxis()->SetTitle("entries");
  LogNPE_numuCC->GetXaxis()->SetTitleSize(0.05);
  LogNPE_numuCC->GetXaxis()->SetLabelSize(0.05);
  LogNPE_numuCC->GetYaxis()->SetLabelSize(0.05);
  LogNPE_numuCC->GetYaxis()->SetTitleOffset(1.2);
  LogNPE_numuCC->SetLineWidth(5);
  LogNPE_numuCC->SetLineColor(kBlue+2);
  LogNPE_numuCC->SetFillColor(kBlue+2);
  LogNPE_numuCC->SetFillStyle(3002);
  mytree->Project("LogNPE_numuCC","log10(trueNPE_LPMT_CD)","CCint==1 && abs(init_lepID)==13","");
  LogNPE_numuCC->Draw();
  LogNPE_nueCC->Draw("same");
  LogNPE_nuNC->Draw("same");
  leg81->AddEntry(LogNPE_numuCC, "#nu_{#mu} CC" ,"l");
  leg81->AddEntry(LogNPE_nueCC, "#nu_{e} CC" ,"l");
  leg81->AddEntry(LogNPE_nuNC, "#nu_{x} NC" ,"l");
  leg81->Draw();

  /////////////////////////LOGPLOTS-CHANNELS//////////////////////////////////////////

  ////////////////////////nuE////////////////////////////////////////////////////////
  
  TCanvas *c82 = new TCanvas("c82","",1000,600);
  TLegend * leg82 = new TLegend(0.7,0.5,0.9,0.9);
  TCanvas *c82a = new TCanvas("c82a","",1000,600);
  TLegend * leg82a = new TLegend(0.7,0.5,0.9,0.9);
  TCanvas *c82b = new TCanvas("c82b","",1000,600);
  TLegend * leg82b = new TLegend(0.7,0.5,0.9,0.9);
  TH1F *LogNPE_numuCC_COH = new TH1F("LogNPE_numuCC_COH","",NPEBINS_Numu,lowNPE_Numu,upNPE_Numu);
  LogNPE_numuCC_COH->SetLineWidth(4);
  LogNPE_numuCC_COH->SetLineColor(kViolet+7);
  mytree->Project("LogNPE_numuCC_COH","log10(trueNPE_LPMT_CD)","abs(init_nuID)==14 && CCint==1 && Int_flag == 4 && trueNPE_LPMT_CD!=0","");
  TH1F *LogNPE_numuCC_QEL = new TH1F("LogNPE_numuCC_QEL","",NPEBINS_Numu,lowNPE_Numu,upNPE_Numu);
  LogNPE_numuCC_QEL->SetLineWidth(4);
  LogNPE_numuCC_QEL->SetLineColor(kAzure+3);
  mytree->Project("LogNPE_numuCC_QEL","log10(trueNPE_LPMT_CD)","abs(init_nuID)==14 && CCint==1 && Int_flag==1 && trueNPE_LPMT_CD!=0","");
  TH1F *LogNPE_numuCC_RES = new TH1F("LogNPE_numuCC_RES","",NPEBINS_Numu,lowNPE_Numu,upNPE_Numu);
  LogNPE_numuCC_RES->SetLineWidth(4);
  LogNPE_numuCC_RES->SetLineColor(kAzure-3);
  mytree->Project("LogNPE_numuCC_RES","log10(trueNPE_LPMT_CD)","abs(init_nuID)==14 && CCint==1 && Int_flag == 2 && trueNPE_LPMT_CD!=0","");
  TH1F *LogNPE_numuCC_DIS = new TH1F("LogNPE_numuCC_DIS","",NPEBINS_Numu,lowNPE_Numu,upNPE_Numu);
  LogNPE_numuCC_DIS->SetLineWidth(4);
  LogNPE_numuCC_DIS->SetLineColor(kBlue-5);
  mytree->Project("LogNPE_numuCC_DIS","log10(trueNPE_LPMT_CD)","abs(init_nuID)==14 && CCint==1 && Int_flag == 3 && trueNPE_LPMT_CD!=0","");
  TH1F *LogNPE_nueCC_COH = new TH1F("LogNPE_nueCC_COH","",NPEBINS_Nue,lowNPE_Nue,upNPE_Nue);
  LogNPE_nueCC_COH->SetLineWidth(4);
  LogNPE_nueCC_COH->SetLineColor(kPink-7);
  mytree->Project("LogNPE_nueCC_COH","log10(trueNPE_LPMT_CD)","abs(init_nuID)==12 && CCint==1 && Int_flag == 4 && trueNPE_LPMT_CD!=0","");
  TH1F *LogNPE_nueCC_QEL = new TH1F("LogNPE_nueCC_QEL","",NPEBINS_Nue,lowNPE_Nue,upNPE_Nue);
  LogNPE_nueCC_QEL->SetLineWidth(4);
  LogNPE_nueCC_QEL->SetLineColor(kRed+3);
  mytree->Project("LogNPE_nueCC_QEL","log10(trueNPE_LPMT_CD)","abs(init_nuID)==12 && CCint==1 && Int_flag==1 && trueNPE_LPMT_CD!=0","");
  TH1F *LogNPE_nueCC_RES = new TH1F("LogNPE_nueCC_RES","",NPEBINS_Nue,lowNPE_Nue,upNPE_Nue);
  LogNPE_nueCC_RES->SetLineWidth(4);
  LogNPE_nueCC_RES->SetLineColor(kPink-1);
  mytree->Project("LogNPE_nueCC_RES","log10(trueNPE_LPMT_CD)","abs(init_nuID)==12 && CCint==1 && Int_flag == 2 && trueNPE_LPMT_CD!=0","");
  TH1F *LogNPE_nueCC_DIS = new TH1F("LogNPE_nueCC_DIS","",NPEBINS_Nue,lowNPE_Nue,upNPE_Nue);
  LogNPE_nueCC_DIS->SetLineWidth(4);
  LogNPE_nueCC_DIS->SetLineColor(kOrange+4);
  mytree->Project("LogNPE_nueCC_DIS","log10(trueNPE_LPMT_CD)","abs(init_nuID)==12 && CCint==1 && Int_flag == 3 && trueNPE_LPMT_CD!=0","");
  TH1F *LogNPE_nueEL = new TH1F("LogNPE_nueEL","",100,5.0,7.2);
  mytree->Project("LogNPE_nueEL","log10(trueNPE_LPMT_CD-lepEnergy)","NCint==1 && Int_flag == 7","");
  TH1F *LogNPE_nuNC_COH = new TH1F("LogNPE_nuNC_COH","",100,5.0,7.2);
  LogNPE_nuNC_COH->SetLineWidth(4);
  LogNPE_nuNC_COH->SetLineColor(kTeal+7);
  mytree->Project("LogNPE_nuNC_COH","log10(trueNPE_LPMT_CD-lepEnergy)","NCint==1 && Int_flag == 4 && (trueNPE_LPMT_CD)!=0","");
  TH1F *LogNPE_nuNC_QEL = new TH1F("LogNPE_nuNC_QEL","",100,5.0,7.2);
  LogNPE_nuNC_QEL->SetLineWidth(4);
  LogNPE_nuNC_QEL->SetLineColor(kSpring-7);
  mytree->Project("LogNPE_nuNC_QEL","log10(trueNPE_LPMT_CD-lepEnergy)","NCint==1 && Int_flag==1 && (trueNPE_LPMT_CD)!=0","");
  TH1F *LogNPE_nuNC_RES = new TH1F("LogNPE_nuNC_RES","",100,5.0,7.2);
  LogNPE_nuNC_RES->SetLineWidth(4);
  LogNPE_nuNC_RES->SetLineColor(kSpring+4);
  mytree->Project("LogNPE_nuNC_RES","log10(trueNPE_LPMT_CD-lepEnergy)","NCint==1 && Int_flag == 2 && (trueNPE_LPMT_CD)!=0","");
  TH1F *LogNPE_nuNC_DIS = new TH1F("LogNPE_nuNC_DIS","",100,5.0,7.2);
  LogNPE_nuNC_DIS->SetLineWidth(4);
  LogNPE_nuNC_DIS->SetLineColor(kTeal+3);
  mytree->Project("LogNPE_nuNC_DIS","log10(trueNPE_LPMT_CD-lepEnergy)","NCint==1 && Int_flag == 3 && (trueNPE_LPMT_CD)!=0","");
  c82a->cd();
  LogNPE_numuCC->Draw();
  LogNPE_numuCC_COH->Draw("same");
  LogNPE_numuCC_QEL->Draw("same");
  LogNPE_numuCC_RES->Draw("same");
  LogNPE_numuCC_DIS->Draw("same");
  leg82a->AddEntry(LogNPE_numuCC, "#nu_{#mu} CC - all" ,"l");
  leg82a->AddEntry(LogNPE_numuCC_COH, "#nu_{#mu} CC - coh" ,"l");
  leg82a->AddEntry(LogNPE_numuCC_QEL, "#nu_{#mu} CC - qel" ,"l");
  leg82a->AddEntry(LogNPE_numuCC_RES, "#nu_{#mu} CC - res" ,"l");
  leg82a->AddEntry(LogNPE_numuCC_DIS, "#nu_{#mu} CC - dis" ,"l");
  leg82a->Draw();
  c82->cd();
  LogNPE_nueCC->Draw(); 
  LogNPE_nueCC_COH->Draw("same");
  LogNPE_nueCC_QEL->Draw("same");
  LogNPE_nueCC_RES->Draw("same");
  LogNPE_nueCC_DIS->Draw("same");
  leg82->AddEntry(LogNPE_nueCC, "#nu_{e} CC - all" ,"l");
  leg82->AddEntry(LogNPE_nueCC_COH, "#nu_{e} CC - coh" ,"l");
  leg82->AddEntry(LogNPE_nueCC_QEL, "#nu_{e} CC - qel" ,"l");
  leg82->AddEntry(LogNPE_nueCC_RES, "#nu_{e} CC - res" ,"l");
  leg82->AddEntry(LogNPE_nueCC_DIS, "#nu_{e} CC - dis" ,"l");
  leg82->Draw();
  c82b->cd();
  LogNPE_nuNC->Draw();
  LogNPE_nuNC_COH->Draw("same");
  LogNPE_nuNC_QEL->Draw("same");
  LogNPE_nuNC_RES->Draw("same");
  LogNPE_nuNC_DIS->Draw("same");
  leg82b->AddEntry(LogNPE_nuNC, "#nu NC - all" ,"l");
  leg82b->AddEntry(LogNPE_nuNC_COH, "#nu NC - coh" ,"l");
  leg82b->AddEntry(LogNPE_nuNC_QEL, "#nu NC - qel" ,"l");
  leg82b->AddEntry(LogNPE_nuNC_RES, "#nu NC - res" ,"l");
  leg82b->AddEntry(LogNPE_nuNC_DIS, "#nu NC - dis" ,"l");
  leg82b->Draw();

  c82->SaveAs("Plot/GENIE_logNPE_bins_channels_nueCC.png");
  c82->SaveAs("Plot/GENIE_logNPE_bins_channels_nueCC.pdf");
  c82->SaveAs("Plot/GENIE_logNPE_bins_channels_nueCC.C");

  c82a->SaveAs("Plot/GENIE_logNPE_bins_channels_numuCC.png");
  c82a->SaveAs("Plot/GENIE_logNPE_bins_channels_numuCC.pdf");
  c82a->SaveAs("Plot/GENIE_logNPE_bins_channels_numuCC.C");

  ///////////////////////////////////////////////////////////////////////////////////////////////

  static const float lowE_Nue = -1.0;
  static const float upE_Nue = 1.05;
  static const float lowE_Numu = -0.3;
  static const float upE_Numu = 1.05;
  static const int EBINS_Nue = 8;
  static const int EBINS_Numu = 8;

  TCanvas *c551 = new TCanvas("c551","",1000,600);
  TLegend * leg551 = new TLegend(0.5,0.45,0.75,0.15);
  TH1F *LogE_nuNC = new TH1F("LogE_nuNC","",100,-1.0,1.05);
  gPad->SetLogy();
  LogE_nuNC->GetXaxis()->SetTitle("log_{10} (True E_{#nu} [GeV])");
  LogE_nuNC->GetYaxis()->SetTitle("entries");
  LogE_nuNC->GetXaxis()->SetTitleSize(0.05);
  LogE_nuNC->GetXaxis()->SetLabelSize(0.05);
  LogE_nuNC->GetYaxis()->SetLabelSize(0.05);
  LogE_nuNC->GetYaxis()->SetTitleOffset(1.2);
  LogE_nuNC->SetLineWidth(5);
  LogE_nuNC->SetLineColor(kSpring-1);
  LogE_nuNC->SetFillColor(kSpring-1);
  LogE_nuNC->SetFillStyle(3002);
  mytree->Project("LogE_nuNC","log10(((nuEnergy/1000.)-lepEnergy))","NCint==1 && Int_flag != 7 && ((nuEnergy/1000.))!=0","");
  c551->cd();
  TH1F *LogE_nueCC = new TH1F("LogE_nueCC","",EBINS_Nue,lowE_Nue,upE_Nue);
  gPad->SetLogy();
  LogE_nueCC->GetXaxis()->SetTitle("log_{10} (True E_{#nu} [GeV])");
  LogE_nueCC->GetYaxis()->SetTitle("entries");
  LogE_nueCC->GetXaxis()->SetTitleSize(0.05);
  LogE_nueCC->GetXaxis()->SetLabelSize(0.05);
  LogE_nueCC->GetYaxis()->SetLabelSize(0.05);
  LogE_nueCC->GetYaxis()->SetTitleOffset(1.2);
  LogE_nueCC->SetLineWidth(5);
  LogE_nueCC->SetLineColor(kRed);
  LogE_nueCC->SetFillColor(kRed);
  LogE_nueCC->SetFillStyle(3002);
  mytree->Project("LogE_nueCC","log10((nuEnergy/1000.))","CCint==1 && abs(init_lepID)==11","");
  TH1F *LogE_numuCC = new TH1F("LogE_numuCC","",EBINS_Numu,lowE_Numu,upE_Numu);
  LogE_numuCC->GetXaxis()->SetTitle("log_{10} (True E_{#nu} [GeV])");
  LogE_numuCC->GetYaxis()->SetTitle("entries");
  LogE_numuCC->GetXaxis()->SetTitleSize(0.05);
  LogE_numuCC->GetXaxis()->SetLabelSize(0.05);
  LogE_numuCC->GetYaxis()->SetLabelSize(0.05);
  LogE_numuCC->GetYaxis()->SetTitleOffset(1.2);
  LogE_numuCC->SetLineWidth(5);
  LogE_numuCC->SetLineColor(kBlue+2);
  LogE_numuCC->SetFillColor(kBlue+2);
  LogE_numuCC->SetFillStyle(3002);
  mytree->Project("LogE_numuCC","log10((nuEnergy/1000.))","CCint==1 && abs(init_lepID)==13","");
  LogE_numuCC->Draw();
  LogE_nueCC->Draw("same");
  LogE_nuNC->Draw("same");
  leg551->AddEntry(LogE_numuCC, "#nu_{#mu} CC" ,"l");
  leg551->AddEntry(LogE_nueCC, "#nu_{e} CC" ,"l");
  leg551->AddEntry(LogE_nuNC, "#nu_{x} NC" ,"l");
  leg551->Draw();

  /////////////////////////LOGPLOTS-CHANNELS//////////////////////////////////////////

  ////////////////////////nuE////////////////////////////////////////////////////////
  
  TCanvas *c552 = new TCanvas("c552","",1000,600);
  TLegend * leg552 = new TLegend(0.7,0.5,0.9,0.9);
  TCanvas *c552a = new TCanvas("c552a","",1000,600);
  TLegend * leg552a = new TLegend(0.7,0.5,0.9,0.9);
  TCanvas *c552b = new TCanvas("c552b","",1000,600);
  TLegend * leg552b = new TLegend(0.7,0.5,0.9,0.9);
  TH1F *LogE_numuCC_COH = new TH1F("LogE_numuCC_COH","",EBINS_Numu,lowE_Numu,upE_Numu);
  LogE_numuCC_COH->SetLineWidth(4);
  LogE_numuCC_COH->SetLineColor(kViolet+7);
  mytree->Project("LogE_numuCC_COH","log10((nuEnergy/1000.))","abs(init_nuID)==14 && CCint==1 && Int_flag == 4 && (nuEnergy/1000.)!=0","");
  TH1F *LogE_numuCC_QEL = new TH1F("LogE_numuCC_QEL","",EBINS_Numu,lowE_Numu,upE_Numu);
  LogE_numuCC_QEL->SetLineWidth(4);
  LogE_numuCC_QEL->SetLineColor(kAzure+3);
  mytree->Project("LogE_numuCC_QEL","log10((nuEnergy/1000.))","abs(init_nuID)==14 && CCint==1 && Int_flag==1 && (nuEnergy/1000.)!=0","");
  TH1F *LogE_numuCC_RES = new TH1F("LogE_numuCC_RES","",EBINS_Numu,lowE_Numu,upE_Numu);
  LogE_numuCC_RES->SetLineWidth(4);
  LogE_numuCC_RES->SetLineColor(kAzure-3);
  mytree->Project("LogE_numuCC_RES","log10((nuEnergy/1000.))","abs(init_nuID)==14 && CCint==1 && Int_flag == 2 && (nuEnergy/1000.)!=0","");
  TH1F *LogE_numuCC_DIS = new TH1F("LogE_numuCC_DIS","",EBINS_Numu,lowE_Numu,upE_Numu);
  LogE_numuCC_DIS->SetLineWidth(4);
  LogE_numuCC_DIS->SetLineColor(kBlue-5);
  mytree->Project("LogE_numuCC_DIS","log10((nuEnergy/1000.))","abs(init_nuID)==14 && CCint==1 && Int_flag == 3 && (nuEnergy/1000.)!=0","");
  TH1F *LogE_nueCC_COH = new TH1F("LogE_nueCC_COH","",EBINS_Nue,lowE_Nue,upE_Nue);
  LogE_nueCC_COH->SetLineWidth(4);
  LogE_nueCC_COH->SetLineColor(kPink-7);
  mytree->Project("LogE_nueCC_COH","log10((nuEnergy/1000.))","abs(init_nuID)==12 && CCint==1 && Int_flag == 4 && (nuEnergy/1000.)!=0","");
  TH1F *LogE_nueCC_QEL = new TH1F("LogE_nueCC_QEL","",EBINS_Nue,lowE_Nue,upE_Nue);
  LogE_nueCC_QEL->SetLineWidth(4);
  LogE_nueCC_QEL->SetLineColor(kRed+3);
  mytree->Project("LogE_nueCC_QEL","log10((nuEnergy/1000.))","abs(init_nuID)==12 && CCint==1 && Int_flag==1 && (nuEnergy/1000.)!=0","");
  TH1F *LogE_nueCC_RES = new TH1F("LogE_nueCC_RES","",EBINS_Nue,lowE_Nue,upE_Nue);
  LogE_nueCC_RES->SetLineWidth(4);
  LogE_nueCC_RES->SetLineColor(kPink-1);
  mytree->Project("LogE_nueCC_RES","log10((nuEnergy/1000.))","abs(init_nuID)==12 && CCint==1 && Int_flag == 2 && (nuEnergy/1000.)!=0","");
  TH1F *LogE_nueCC_DIS = new TH1F("LogE_nueCC_DIS","",EBINS_Nue,lowE_Nue,upE_Nue);
  LogE_nueCC_DIS->SetLineWidth(4);
  LogE_nueCC_DIS->SetLineColor(kOrange+4);
  mytree->Project("LogE_nueCC_DIS","log10((nuEnergy/1000.))","abs(init_nuID)==12 && CCint==1 && Int_flag == 3 && (nuEnergy/1000.)!=0","");
  TH1F *LogE_nueEL = new TH1F("LogE_nueEL","",100,-1.0,1.05);
  mytree->Project("LogE_nueEL","log10((nuEnergy/1000.)-lepEnergy)","NCint==1 && Int_flag == 7","");
  TH1F *LogE_nuNC_COH = new TH1F("LogE_nuNC_COH","",100,-1.0,1.05);
  LogE_nuNC_COH->SetLineWidth(4);
  LogE_nuNC_COH->SetLineColor(kTeal+7);
  mytree->Project("LogE_nuNC_COH","log10((nuEnergy/1000.)-lepEnergy)","NCint==1 && Int_flag == 4 && ((nuEnergy/1000.))!=0","");
  TH1F *LogE_nuNC_QEL = new TH1F("LogE_nuNC_QEL","",100,-1.0,1.05);
  LogE_nuNC_QEL->SetLineWidth(4);
  LogE_nuNC_QEL->SetLineColor(kSpring-7);
  mytree->Project("LogE_nuNC_QEL","log10((nuEnergy/1000.)-lepEnergy)","NCint==1 && Int_flag==1 && ((nuEnergy/1000.))!=0","");
  TH1F *LogE_nuNC_RES = new TH1F("LogE_nuNC_RES","",100,-1.0,1.05);
  LogE_nuNC_RES->SetLineWidth(4);
  LogE_nuNC_RES->SetLineColor(kSpring+4);
  mytree->Project("LogE_nuNC_RES","log10((nuEnergy/1000.)-lepEnergy)","NCint==1 && Int_flag == 2 && ((nuEnergy/1000.))!=0","");
  TH1F *LogE_nuNC_DIS = new TH1F("LogE_nuNC_DIS","",100,-1.0,1.05);
  LogE_nuNC_DIS->SetLineWidth(4);
  LogE_nuNC_DIS->SetLineColor(kTeal+3);
  mytree->Project("LogE_nuNC_DIS","log10((nuEnergy/1000.)-lepEnergy)","NCint==1 && Int_flag == 3 && ((nuEnergy/1000.))!=0","");
  c552a->cd();
  LogE_numuCC->Draw();
  LogE_numuCC_COH->Draw("same");
  LogE_numuCC_QEL->Draw("same");
  LogE_numuCC_RES->Draw("same");
  LogE_numuCC_DIS->Draw("same");
  leg552a->AddEntry(LogE_numuCC, "#nu_{#mu} CC - all" ,"l");
  leg552a->AddEntry(LogE_numuCC_COH, "#nu_{#mu} CC - coh" ,"l");
  leg552a->AddEntry(LogE_numuCC_QEL, "#nu_{#mu} CC - qel" ,"l");
  leg552a->AddEntry(LogE_numuCC_RES, "#nu_{#mu} CC - res" ,"l");
  leg552a->AddEntry(LogE_numuCC_DIS, "#nu_{#mu} CC - dis" ,"l");
  leg552a->Draw();
  c552->cd();
  LogE_nueCC->Draw(); 
  LogE_nueCC_COH->Draw("same");
  LogE_nueCC_QEL->Draw("same");
  LogE_nueCC_RES->Draw("same");
  LogE_nueCC_DIS->Draw("same");
  leg552->AddEntry(LogE_nueCC, "#nu_{e} CC - all" ,"l");
  leg552->AddEntry(LogE_nueCC_COH, "#nu_{e} CC - coh" ,"l");
  leg552->AddEntry(LogE_nueCC_QEL, "#nu_{e} CC - qel" ,"l");
  leg552->AddEntry(LogE_nueCC_RES, "#nu_{e} CC - res" ,"l");
  leg552->AddEntry(LogE_nueCC_DIS, "#nu_{e} CC - dis" ,"l");
  leg552->Draw();
  c552b->cd();
  LogE_nuNC->Draw();
  LogE_nuNC_COH->Draw("same");
  LogE_nuNC_QEL->Draw("same");
  LogE_nuNC_RES->Draw("same");
  LogE_nuNC_DIS->Draw("same");
  leg552b->AddEntry(LogE_nuNC, "#nu NC - all" ,"l");
  leg552b->AddEntry(LogE_nuNC_COH, "#nu NC - coh" ,"l");
  leg552b->AddEntry(LogE_nuNC_QEL, "#nu NC - qel" ,"l");
  leg552b->AddEntry(LogE_nuNC_RES, "#nu NC - res" ,"l");
  leg552b->AddEntry(LogE_nuNC_DIS, "#nu NC - dis" ,"l");
  leg552b->Draw();

  c552->SaveAs("Plot/GENIE_logE_bins_channels_nueCC.png");
  c552->SaveAs("Plot/GENIE_logE_bins_channels_nueCC.pdf");
  c552->SaveAs("Plot/GENIE_logE_bins_channels_nueCC.C");

  c552a->SaveAs("Plot/GENIE_logE_bins_channels_numuCC.png");
  c552a->SaveAs("Plot/GENIE_logE_bins_channels_numuCC.pdf");
  c552a->SaveAs("Plot/GENIE_logE_bins_channels_numuCC.C");

  
}

