void makespectrum() {
  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);

  TTree *mytree;
  TFile *_file1 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/matrix/treemaker/trees/MC_70K_1m.root");
  _file1->GetObject("Data",mytree);
  TCanvas *c15 = new TCanvas("c15","",1600,1200);
  TLegend * leg4 = new TLegend(0.75,0.9,0.9,0.7);
  TH1F *Npe_Elec_LPMT_nueCC = new TH1F("Npe_Elec_LPMT_nueCC","",20,5.,7.6);
  Npe_Elec_LPMT_nueCC->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  gPad->SetLogy();
  Npe_Elec_LPMT_nueCC->SetLineWidth(3);
  Npe_Elec_LPMT_nueCC->SetLineColor(kRed);
  mytree->Project("Npe_Elec_LPMT_nueCC","log10(trueNPE_LPMT)","Tres_RMS<80 && CCint==1 && abs(init_lepID)==11 && newVradius<16000","");
  c15->cd();
  Npe_Elec_LPMT_nueCC->GetYaxis()->SetRangeUser(1.,1000.);
  Npe_Elec_LPMT_nueCC->Draw();
  TH1F *Npe_Elec_LPMT_numuCC = new TH1F("Npe_Elec_LPMT_numuCC","",20,5.,7.6);
  Npe_Elec_LPMT_numuCC->GetXaxis()->SetTitle("log_{10}(NPE_ELEC_{LPMT})");
  Npe_Elec_LPMT_numuCC->SetLineWidth(3);
  Npe_Elec_LPMT_numuCC->SetLineColor(kBlue);
  mytree->Project("Npe_Elec_LPMT_numuCC","log10(trueNPE_LPMT)","Tres_RMS<80 && CCint==1 && abs(init_lepID)==13 && newVradius<16000","");
  Npe_Elec_LPMT_numuCC->Draw("same");
  TH1F *Npe_Elec_LPMT_nuNC = new TH1F("Npe_Elec_LPMT_nuNC","",20,5.,7.6);
  Npe_Elec_LPMT_nuNC->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  gPad->SetLogy();
  Npe_Elec_LPMT_nuNC->SetLineWidth(3);
  Npe_Elec_LPMT_nuNC->SetLineColor(kSpring-1);
  mytree->Project("Npe_Elec_LPMT_nuNC","log10(trueNPE_LPMT)","Tres_RMS<80 && NCint==1 && newVradius<16000","");
  Npe_Elec_LPMT_nuNC->Draw("same");
  leg4->AddEntry(Npe_Elec_LPMT_numuCC, "#nu_{#mu} CC" ,"l");  
  leg4->AddEntry(Npe_Elec_LPMT_nueCC, "#nu_{e} CC" ,"l");
  leg4->AddEntry(Npe_Elec_LPMT_nuNC, "#nu_{e}+#nu_{#mu} NC" ,"l");
  leg4->Draw();
  c15->SaveAs("Plot/logNPE_LPMT_nuall_0-20GeV_16volcut_1m_less80nscut.png");
  c15->SaveAs("Plot/logNPE_LPMT_nuall_0-20GeV_16volcut_1m_less80nscut.pdf");
  c15->SaveAs("Plot/logNPE_LPMT_nuall_0-20GeV_16volcut_1m_less80nscut.C");
  ///////////////////////////////////////////////////////////////////////////////////
  TCanvas *c16 = new TCanvas("c16","",1600,1200);
  TLegend * leg5 = new TLegend(0.75,0.9,0.9,0.7);
  TH1F *Npe_Elec_SPMT_nueCC = new TH1F("Npe_Elec_SPMT_nueCC","",20,3.,6.2);
  Npe_Elec_SPMT_nueCC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
  gPad->SetLogy();
  Npe_Elec_SPMT_nueCC->SetLineWidth(3);
  Npe_Elec_SPMT_nueCC->SetLineColor(kRed);
  mytree->Project("Npe_Elec_SPMT_nueCC","log10(trueNPE_SPMT)","Tres_RMS<80 && CCint==1 && abs(init_lepID)==11 && newVradius<16000","");
  Npe_Elec_SPMT_nueCC->Draw();
  leg5->AddEntry(Npe_Elec_SPMT_nueCC, "#nu_{e} CC" ,"l");
  TH1F *Npe_Elec_SPMT_numuCC = new TH1F("Npe_Elec_SPMT_numuCC","",20,3.,6.2);
  Npe_Elec_SPMT_numuCC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
  Npe_Elec_SPMT_numuCC->SetLineWidth(3);
  Npe_Elec_SPMT_numuCC->SetLineColor(kBlue);
  mytree->Project("Npe_Elec_SPMT_numuCC","log10(trueNPE_SPMT)","Tres_RMS<80 && CCint==1 && abs(init_lepID)==13 && newVradius<16000","");
  Npe_Elec_SPMT_numuCC->Draw("same");
  leg5->AddEntry(Npe_Elec_SPMT_numuCC, "#nu_{#mu} CC" ,"l");
  TH1F *Npe_Elec_SPMT_nuNC = new TH1F("Npe_Elec_SPMT_nuNC","",20,3.,6.2);
  Npe_Elec_SPMT_nuNC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
  gPad->SetLogy();
  Npe_Elec_SPMT_nuNC->SetLineWidth(3);
  Npe_Elec_SPMT_nuNC->SetLineColor(kSpring-1);
  mytree->Project("Npe_Elec_SPMT_nuNC","log10(trueNPE_SPMT)","Tres_RMS<80 && NCint==1 && newVradius<16000","");
  c16->cd();
  Npe_Elec_SPMT_nuNC->Draw("same");
  leg5->AddEntry(Npe_Elec_SPMT_nuNC, "#nu_{e}+#nu_{#mu} NC" ,"l");
  leg5->Draw();
  c16->SaveAs("Plot/logNPE_SPMT_nuall_0-20GeV_16volcut_1m_less80nscut.png");
  c16->SaveAs("Plot/logNPE_SPMT_nuall_0-20GeV_16volcut_1m_less80nscut.pdf");
  c16->SaveAs("Plot/logNPE_SPMT_nuall_0-20GeV_16volcut_1m_less80nscut.C");

  /////////////////////////////////////////////////////////////////////
  
  TCanvas *c25 = new TCanvas("c25","",1600,1200);
  TLegend * leg14 = new TLegend(0.75,0.9,0.9,0.7);
  TH1F *Npe_noElec_LPMT_numuCC = new TH1F("Npe_noElec_LPMT_numuCC","",20,5.,7.6);
  Npe_noElec_LPMT_numuCC->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  Npe_noElec_LPMT_numuCC->SetLineWidth(3);
  Npe_noElec_LPMT_numuCC->SetLineColor(kBlue);
  mytree->Project("Npe_noElec_LPMT_numuCC","log10(trueNPE_LPMT)","Tres_RMS>90 && CCint==1 && abs(init_lepID)==13 && newVradius<16000","");
  Npe_noElec_LPMT_numuCC->Draw();
  leg14->AddEntry(Npe_noElec_LPMT_numuCC, "#nu_{#mu} CC" ,"l");
  TH1F *Npe_noElec_LPMT_nueCC = new TH1F("Npe_noElec_LPMT_nueCC","",20,5.,7.6);
  Npe_noElec_LPMT_nueCC->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  gPad->SetLogy();
  Npe_noElec_LPMT_nueCC->SetLineWidth(3);
  Npe_noElec_LPMT_nueCC->SetLineColor(kRed);
  mytree->Project("Npe_noElec_LPMT_nueCC","log10(trueNPE_LPMT)","Tres_RMS>90 && CCint==1 && abs(init_lepID)==11 && newVradius<16000","");
  Npe_noElec_LPMT_nueCC->Draw("same");
  leg14->AddEntry(Npe_noElec_LPMT_nueCC, "#nu_{e} CC" ,"l");
  TH1F *Npe_noElec_LPMT_nuNC = new TH1F("Npe_noElec_LPMT_nuNC","",20,5.,7.6);
  Npe_noElec_LPMT_nuNC->GetXaxis()->SetTitle("log_{10}(NPE_{LPMT})");
  gPad->SetLogy();
  Npe_noElec_LPMT_nuNC->SetLineWidth(3);
  Npe_noElec_LPMT_nuNC->SetLineColor(kSpring-1);
  mytree->Project("Npe_noElec_LPMT_nuNC","log10(trueNPE_LPMT)","Tres_RMS>90 && NCint==1 && newVradius<16000","");
  c25->cd();
  Npe_noElec_LPMT_nuNC->Draw("same");
  leg14->AddEntry(Npe_noElec_LPMT_nuNC, "#nu_{e}+#nu_{#mu} NC" ,"l");
  leg14->Draw();
  c25->SaveAs("Plot/logNPE_LPMT_nuall_0-20GeV_16volcut_1m_over90nscut.png");
  c25->SaveAs("Plot/logNPE_LPMT_nuall_0-20GeV_16volcut_1m_over90nscut.pdf");
  c25->SaveAs("Plot/logNPE_LPMT_nuall_0-20GeV_16volcut_1m_over90nscut.C");
  ///////////////////////////////////////////////////////////////////////////////////
  TCanvas *c26 = new TCanvas("c26","",1600,1200);
  TLegend * leg15 = new TLegend(0.75,0.9,0.9,0.7);
  TH1F *Npe_noElec_SPMT_numuCC = new TH1F("Npe_noElec_SPMT_numuCC","",20,3.,6.2);
  Npe_noElec_SPMT_numuCC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
  Npe_noElec_SPMT_numuCC->SetLineWidth(3);
  Npe_noElec_SPMT_numuCC->SetLineColor(kBlue);
  mytree->Project("Npe_noElec_SPMT_numuCC","log10(trueNPE_SPMT)","Tres_RMS>90 && CCint==1 && abs(init_lepID)==13 && newVradius<16000","");
  Npe_noElec_SPMT_numuCC->Draw();
  leg15->AddEntry(Npe_noElec_SPMT_numuCC, "#nu_{#mu} CC" ,"l");
  TH1F *Npe_noElec_SPMT_nueCC = new TH1F("Npe_noElec_SPMT_nueCC","",20,3.,6.2);
  Npe_noElec_SPMT_nueCC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
  gPad->SetLogy();
  Npe_noElec_SPMT_nueCC->SetLineWidth(3);
  Npe_noElec_SPMT_nueCC->SetLineColor(kRed);
  mytree->Project("Npe_noElec_SPMT_nueCC","log10(trueNPE_SPMT)","Tres_RMS>90 && CCint==1 && abs(init_lepID)==11 && newVradius<16000","");
  Npe_noElec_SPMT_nueCC->Draw("same");
  leg15->AddEntry(Npe_noElec_SPMT_nueCC, "#nu_{e} CC" ,"l");
  TH1F *Npe_noElec_SPMT_nuNC = new TH1F("Npe_noElec_SPMT_nuNC","",20,3.,6.2);
  Npe_noElec_SPMT_nuNC->GetXaxis()->SetTitle("log_{10}(NPE_{SPMT})");
  gPad->SetLogy();
  Npe_noElec_SPMT_nuNC->SetLineWidth(3);
  Npe_noElec_SPMT_nuNC->SetLineColor(kSpring-1);
  mytree->Project("Npe_noElec_SPMT_nuNC","log10(trueNPE_SPMT)","Tres_RMS>90 && NCint==1 && newVradius<16000","");
  c26->cd();
  Npe_noElec_SPMT_nuNC->Draw("same");
  leg15->AddEntry(Npe_noElec_SPMT_nuNC, "#nu_{e}+#nu_{#mu} NC" ,"l");
  leg15->Draw();
  c26->SaveAs("Plot/logNPE_SPMT_nuall_0-20GeV_16volcut_1m_over90nscut.png");
  c26->SaveAs("Plot/logNPE_SPMT_nuall_0-20GeV_16volcut_1m_over90nscut.pdf");
  c26->SaveAs("Plot/logNPE_SPMT_nuall_0-20GeV_16volcut_1m_over90nscut.C");

}
