void makespectrum_lin() {
  gStyle->SetOptStat(0);
  gStyle->SetPadBottomMargin(0.12);
  gStyle->SetTitleH(0.1);
  gStyle->SetTitleW(1.05);

  TTree *mytree;
  TFile *_file1 = TFile::Open("/storage/DATA-02/juno/Users/sgiulio/Atmo/analysis/unfolding/treemaker/trees/MC_100K_1m.root");
  _file1->GetObject("Data",mytree);
  TCanvas *c15 = new TCanvas("c15","",800,600);
  TLegend * leg4 = new TLegend(0.65,0.9,0.9,0.6);
  TH1F *Npe_Elec_LPMT_nueCC = new TH1F("Npe_Elec_LPMT_nueCC","",75,0.,3.0E7);
  Npe_Elec_LPMT_nueCC->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_Elec_LPMT_nueCC->GetXaxis()->SetTitleSize(0.05);
  Npe_Elec_LPMT_nueCC->GetXaxis()->SetLabelSize(0.05);
  Npe_Elec_LPMT_nueCC->GetYaxis()->SetTitle("entries");
  Npe_Elec_LPMT_nueCC->GetYaxis()->SetLabelSize(0.05);
  Npe_Elec_LPMT_nueCC->GetYaxis()->SetTitleOffset(1.2);
  Npe_Elec_LPMT_nueCC->SetLineWidth(5);
  Npe_Elec_LPMT_nueCC->SetLineColor(kRed);
  mytree->Project("Npe_Elec_LPMT_nueCC","(trueNPE_LPMT)","Tres_RMS<80 && CCint==1 && abs(init_lepID)==11 && newVradius<16000","");
  Npe_Elec_LPMT_nueCC->Draw();
  TH1F *Npe_Elec_LPMT_numuCC = new TH1F("Npe_Elec_LPMT_numuCC","",75,0.,3.0E7);
  Npe_Elec_LPMT_numuCC->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_Elec_LPMT_numuCC->SetLineWidth(5);
  Npe_Elec_LPMT_numuCC->SetLineColor(kBlue+2);
  mytree->Project("Npe_Elec_LPMT_numuCC","(trueNPE_LPMT)","Tres_RMS<80 && CCint==1 && abs(init_lepID)==13 && newVradius<16000","");
  Npe_Elec_LPMT_numuCC->Draw("same");
  TH1F *Npe_Elec_LPMT_nuNC = new TH1F("Npe_Elec_LPMT_nuNC","",75,0.,3.0E7);
  Npe_Elec_LPMT_nuNC->GetXaxis()->SetTitle("NPE_{LPMT}");
  gPad->SetLogy();
  Npe_Elec_LPMT_nuNC->SetLineWidth(5);
  Npe_Elec_LPMT_nuNC->SetLineColor(kSpring-1);
  mytree->Project("Npe_Elec_LPMT_nuNC","(trueNPE_LPMT)","Tres_RMS<80 && NCint==1 && newVradius<16000","");
  c15->cd();
  Npe_Elec_LPMT_nuNC->Draw("same");
  leg4->AddEntry(Npe_Elec_LPMT_numuCC, "#nu_{#mu} CC" ,"l");  
  leg4->AddEntry(Npe_Elec_LPMT_nueCC, "#nu_{e} CC" ,"l");
  leg4->AddEntry(Npe_Elec_LPMT_nuNC, "#nu_{e}+#nu_{#mu} NC" ,"l");
  leg4->Draw();
  c15->SaveAs("Plot/NPE_LPMT_nuall_0-20GeV_16volcut_1m_less80nscut.png");
  c15->SaveAs("Plot/NPE_LPMT_nuall_0-20GeV_16volcut_1m_less80nscut.pdf");
  c15->SaveAs("Plot/NPE_LPMT_nuall_0-20GeV_16volcut_1m_less80nscut.C");
  ///////////////////////////////////////////////////////////////////////////////////
  
  TCanvas *c25 = new TCanvas("c25","",1200,600);
  TLegend * leg14 = new TLegend(0.65,0.9,0.9,0.6);
  TH1F *Npe_noElec_LPMT_numuCC = new TH1F("Npe_noElec_LPMT_numuCC","",75,0.,3.0E7);
  gPad->SetLogy();
  Npe_noElec_LPMT_numuCC->SetLineWidth(5);
  Npe_noElec_LPMT_numuCC->SetLineColor(kBlue+2);
  mytree->Project("Npe_noElec_LPMT_numuCC","(trueNPE_LPMT)","Tres_RMS>90 && CCint==1 && abs(init_lepID)==13 && newVradius<16000","");
  leg14->AddEntry(Npe_noElec_LPMT_numuCC, "#nu_{#mu} CC" ,"l");
  TH1F *Npe_noElec_LPMT_nueCC = new TH1F("Npe_noElec_LPMT_nueCC","",75,0.,3.0E7);
  Npe_noElec_LPMT_nueCC->GetXaxis()->SetTitle("NPE_{LPMT}");
  gPad->SetLogy();
  Npe_noElec_LPMT_nueCC->SetLineWidth(5);
  Npe_noElec_LPMT_nueCC->SetLineColor(kRed);
  mytree->Project("Npe_noElec_LPMT_nueCC","(trueNPE_LPMT)","Tres_RMS>90 && CCint==1 && abs(init_lepID)==11 && newVradius<16000","");
  leg14->AddEntry(Npe_noElec_LPMT_nueCC, "#nu_{e} CC" ,"l");
  TH1F *Npe_noElec_LPMT_nuNC = new TH1F("Npe_noElec_LPMT_nuNC","",75,0.,3.0E7);
  Npe_noElec_LPMT_nuNC->GetXaxis()->SetTitle("NPE_{LPMT}");
  gPad->SetLogy();
  Npe_noElec_LPMT_nuNC->SetLineWidth(5);
  Npe_noElec_LPMT_nuNC->SetLineColor(kSpring-1);
  Npe_noElec_LPMT_nuNC->GetXaxis()->SetTitle("NPE_{LPMT}");
  Npe_noElec_LPMT_nuNC->GetXaxis()->SetTitleSize(0.05);
  Npe_noElec_LPMT_nuNC->GetXaxis()->SetLabelSize(0.05);
  Npe_noElec_LPMT_nuNC->GetYaxis()->SetTitle("entries");
  Npe_noElec_LPMT_nuNC->GetYaxis()->SetLabelSize(0.05);
  Npe_noElec_LPMT_nuNC->GetYaxis()->SetTitleOffset(1.2);
  mytree->Project("Npe_noElec_LPMT_nuNC","(trueNPE_LPMT)","Tres_RMS>90 && NCint==1 && newVradius<16000","");
  c25->cd();
  Npe_noElec_LPMT_nuNC->Draw();
  Npe_noElec_LPMT_numuCC->Draw("same");
  Npe_noElec_LPMT_nueCC->Draw("same");
  leg14->AddEntry(Npe_noElec_LPMT_nuNC, "#nu_{e}+#nu_{#mu} NC" ,"l");
  leg14->Draw();
  c25->SaveAs("Plot/NPE_LPMT_nuall_0-20GeV_16volcut_1m_over90nscut.png");
  c25->SaveAs("Plot/NPE_LPMT_nuall_0-20GeV_16volcut_1m_over90nscut.pdf");
  c25->SaveAs("Plot/NPE_LPMT_nuall_0-20GeV_16volcut_1m_over90nscut.C");

}
