void maketruespectrum_cuts() {
  gStyle->SetOptStat(0);
  gStyle->SetPadBottomMargin(0.12);
  gStyle->SetTitleH(0.1);
  gStyle->SetTitleW(1.05);

  static const int binsE_nuE = 12;
  static const int binsNPE_nuE = 10;
  static const int binsE_nuMu = 10;
  static const int binsNPE_nuMu = 8;
  static const float lowE_nuE = 2.0;
  static const float lowNPE_nuE = 5.0;
  static const float upE_nuE = 4.2;
  static const float upNPE_nuE = 7.2;
  static const float lowE_nuMu = 2.48;
  static const float lowNPE_nuMu = 5.7;
  static const float upE_nuMu = 4.2;
  static const float upNPE_nuMu = 7.2;

  TTree *mytree;
  //TFile *_file1 = TFile::Open("/home/sgiulio/Giulio/University/JUNO/juno-unfolding/treemaker/trees/MC_100K_1m_COMPLETE.root");
  //TFile *_file1 = TFile::Open("/storage/gpfs_data/juno/junofs/users/sgiulio/Atmo/analysis/unfolding/treemaker/trees/MC_100K_1m_TOT_12.root");
  TFile *_file1 = TFile::Open("/storage/gpfs_data/juno/junofs/users/sgiulio/Atmo/analysis/unfolding/treemaker/trees/MC_500K_1m_TOT_FULL.root");
  _file1->GetObject("Data",mytree);

  TCanvas *c15 = new TCanvas("c15","",800,600);
  TLegend * leg4 = new TLegend(0.65,0.9,0.9,0.6);
  TH1F *Ev_nueCC = new TH1F("Ev_nueCC","",35,0.,2.05E4);
  Ev_nueCC->GetXaxis()->SetTitle("E_{#nu} [MeV]");
  Ev_nueCC->GetXaxis()->SetTitleSize(0.05);
  Ev_nueCC->GetXaxis()->SetLabelSize(0.04);
  Ev_nueCC->GetYaxis()->SetTitle("entries");
  Ev_nueCC->GetYaxis()->SetLabelSize(0.05);
  Ev_nueCC->GetYaxis()->SetTitleOffset(1.2);
  Ev_nueCC->SetLineWidth(5);
  Ev_nueCC->SetLineColor(kOrange);
  Ev_nueCC->SetFillColor(kOrange);
  Ev_nueCC->SetFillStyle(3002);
  mytree->Project("Ev_nueCC","nuEnergy","CCint==1 && abs(init_lepID)==11","");
  Ev_nueCC->Draw();
  TH1F *Ev_nueCC_fidcut = new TH1F("Ev_nueCC_fidcut","",35,0.,2.05E4);
  Ev_nueCC_fidcut->SetLineWidth(5);
  Ev_nueCC_fidcut->SetLineColor(kAzure+1);
  Ev_nueCC_fidcut->SetFillColor(kAzure+1);
  Ev_nueCC_fidcut->SetFillStyle(3002);
  mytree->Project("Ev_nueCC_fidcut","nuEnergy","CCint==1 && abs(init_lepID)==11 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 1.E5","");
  Ev_nueCC_fidcut->Draw("same");
  TH1F *Ev_nueCC_timecut = new TH1F("Ev_nueCC_timecut","",35,0.,2.05E4);
  Ev_nueCC_timecut->GetXaxis()->SetTitle("E_{#nu} [MeV]");
  Ev_nueCC_timecut->SetLineWidth(5);
  Ev_nueCC_timecut->SetLineColor(kRed);
  Ev_nueCC_timecut->SetFillColor(kRed);
  Ev_nueCC_timecut->SetFillStyle(3002);
  mytree->Project("Ev_nueCC_timecut","nuEnergy","Tres_RMS<75 && CCint==1 && abs(init_lepID)==11 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 1.E5","");
  Ev_nueCC_timecut->Draw("same");
  TH1F *Ev_bkg1 = new TH1F("Ev_bkg1","",35,0.,2.05E4);
  Ev_bkg1->GetXaxis()->SetTitle("E_{#nu} [MeV]");
  gPad->SetLogy();
  Ev_bkg1->SetLineWidth(5);
  Ev_bkg1->SetLineColor(kGreen+3);
  Ev_bkg1->SetFillColor(kGreen+3);
  Ev_bkg1->SetFillStyle(3002);
  mytree->Project("Ev_bkg1","nuEnergy","Tres_RMS<75 && abs(init_lepID)!=11 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 1.E5","");
  c15->cd();
  Ev_bkg1->Draw("same");
  leg4->AddEntry(Ev_nueCC, "#nu_{e}^{CC}" ,"l");
  leg4->AddEntry(Ev_nueCC_fidcut, "#nu_{e}^{CC} fid." ,"l");
  leg4->AddEntry(Ev_nueCC_timecut, "#nu_{e}^{CC} sel." ,"l");  
  leg4->AddEntry(Ev_bkg1, "res. bkg" ,"l");
  leg4->Draw();
  c15->SaveAs("Plot/Ev_eff_0-20GeV_16volcut_1m_less75nscut.png");
  c15->SaveAs("Plot/Ev_eff_0-20GeV_16volcut_1m_less75nscut.pdf");
  c15->SaveAs("Plot/Ev_eff_0-20GeV_16volcut_1m_less75nscut.C");

  ///////////////////////////////////////////////////////////////////////////////////

  TCanvas *c16 = new TCanvas("c16","",800,600);
  TLegend * leg5 = new TLegend(0.65,0.9,0.9,0.6);
  TH1F *Ev_numuCC = new TH1F("Ev_numuCC","",35,0.,2.05E4);
  Ev_numuCC->GetXaxis()->SetTitle("E_{#nu} [MeV]");
  Ev_numuCC->GetXaxis()->SetTitleSize(0.05);
  Ev_numuCC->GetXaxis()->SetLabelSize(0.04);
  Ev_numuCC->GetYaxis()->SetTitle("entries");
  Ev_numuCC->GetYaxis()->SetLabelSize(0.05);
  Ev_numuCC->GetYaxis()->SetTitleOffset(1.2);
  Ev_numuCC->SetLineWidth(5);
  Ev_numuCC->SetLineColor(kOrange);
  Ev_numuCC->SetFillColor(kOrange);
  Ev_numuCC->SetFillStyle(3002);
  mytree->Project("Ev_numuCC","nuEnergy","CCint==1 && abs(init_lepID)==13","");
  Ev_numuCC->Draw();
  TH1F *Ev_numuCC_fidcut = new TH1F("Ev_numuCC_fidcut","",35,0.,2.05E4);
  Ev_numuCC_fidcut->SetLineWidth(5);
  Ev_numuCC_fidcut->SetLineColor(kAzure+1);
  Ev_numuCC_fidcut->SetFillColor(kAzure+1);
  Ev_numuCC_fidcut->SetFillStyle(3002);
  mytree->Project("Ev_numuCC_fidcut","nuEnergy","CCint==1 && abs(init_lepID)==13 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 5.E5","");
  Ev_numuCC_fidcut->Draw("same");
  TH1F *Ev_numuCC_timecut = new TH1F("Ev_numuCC_timecut","",35,0.,2.05E4);
  Ev_numuCC_timecut->GetXaxis()->SetTitle("E_{#nu} [MeV]");
  Ev_numuCC_timecut->SetLineWidth(5);
  Ev_numuCC_timecut->SetLineColor(kRed);
  Ev_numuCC_timecut->SetFillColor(kRed);
  Ev_numuCC_timecut->SetFillStyle(3002);
  mytree->Project("Ev_numuCC_timecut","nuEnergy","Tres_RMS>95 && CCint==1 && abs(init_lepID)==13 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 5.E5","");
  Ev_numuCC_timecut->Draw("same");
  TH1F *Ev_bkg2 = new TH1F("Ev_bkg2","",35,0.,2.05E4);
  Ev_bkg2->GetXaxis()->SetTitle("E_{#nu} [MeV]");
  gPad->SetLogy();
  Ev_bkg2->SetLineWidth(5);
  Ev_bkg2->SetLineColor(kGreen+3);
  Ev_bkg2->SetFillColor(kGreen+3);
  Ev_bkg2->SetFillStyle(3002);
  mytree->Project("Ev_bkg2","nuEnergy","Tres_RMS>95 && abs(init_lepID)!=13 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 5.E5","");
  c16->cd();
  Ev_bkg2->Draw("same");
  leg5->AddEntry(Ev_numuCC, "#nu_{#mu}^{CC} FC" ,"l");
  leg5->AddEntry(Ev_numuCC_fidcut, "#nu_{#mu}^{CC} FC fid." ,"l");
  leg5->AddEntry(Ev_numuCC_timecut, "#nu_{#mu}^{CC} FC sel." ,"l");
  leg5->AddEntry(Ev_bkg2, "res. bkg" ,"l");
  leg5->Draw();
  c16->SaveAs("Plot/Ev_eff_0-20GeV_16volcut_1m_over95nscut.png");
  c16->SaveAs("Plot/Ev_eff_0-20GeV_16volcut_1m_over95nscut.pdf");
  c16->SaveAs("Plot/Ev_eff_0-20GeV_16volcut_1m_over95nscut.C");

  //////////////////////////////////LOGPLOTS//////////////////////////

  char* filename1= new char[128];
  sprintf(filename1,"output/NPEarray_fromMC_nuE_%i.txt",binsNPE_nuE);
  std::ofstream npearray_MC_e;
  npearray_MC_e.open(filename1);

  TCanvas *c17 = new TCanvas("c17","",800,600);
  TLegend * leg6 = new TLegend(0.7,0.9,0.9,0.7);
  TH1F *logEv_nueCC = new TH1F("logEv_nueCC","",binsE_nuE,lowE_nuE,upE_nuE);
  logEv_nueCC->GetXaxis()->SetTitle("log_{10}(E_{#nu} [MeV])");
  logEv_nueCC->GetXaxis()->SetTitleSize(0.05);
  logEv_nueCC->GetXaxis()->SetLabelSize(0.04);
  logEv_nueCC->GetYaxis()->SetTitle("entries");
  logEv_nueCC->GetYaxis()->SetLabelSize(0.05);
  logEv_nueCC->GetYaxis()->SetTitleOffset(1.2);
  logEv_nueCC->SetLineWidth(5);
  logEv_nueCC->SetLineColor(kOrange);
  logEv_nueCC->SetFillColor(kOrange);
  logEv_nueCC->SetFillStyle(3002);
  mytree->Project("logEv_nueCC","log10(nuEnergy)","CCint==1 && abs(init_lepID)==11","");
  logEv_nueCC->Draw();
  TH1F *logEv_nueCC_fidcut = new TH1F("logEv_nueCC_fidcut","",binsE_nuE,lowE_nuE,upE_nuE);
  logEv_nueCC_fidcut->SetLineWidth(5);
  logEv_nueCC_fidcut->SetLineColor(kAzure+1);
  logEv_nueCC_fidcut->SetFillColor(kAzure+1);
  logEv_nueCC_fidcut->SetFillStyle(3002);
  mytree->Project("logEv_nueCC_fidcut","log10(nuEnergy)","CCint==1 && abs(init_lepID)==11 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 1.E5","");
  logEv_nueCC_fidcut->Draw("same");
  TH1F *logEv_nueCC_timecut = new TH1F("logEv_nueCC_timecut","",binsE_nuE,lowE_nuE,upE_nuE);
  logEv_nueCC_timecut->GetXaxis()->SetTitle("log_{10}(E_{#nu} [MeV])");
  logEv_nueCC_timecut->SetLineWidth(5);
  logEv_nueCC_timecut->SetLineColor(kRed);
  logEv_nueCC_timecut->SetFillColor(kRed);
  logEv_nueCC_timecut->SetFillStyle(3002);
  mytree->Project("logEv_nueCC_timecut","log10(nuEnergy)","Tres_RMS<75 && CCint==1 && abs(init_lepID)==11 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 1.E5","");
  logEv_nueCC_timecut->Draw("same");
  TH1F *logEv_bkg1 = new TH1F("logEv_bkg1","",binsE_nuE,lowE_nuE,upE_nuE);
  logEv_bkg1->GetXaxis()->SetTitle("log_{10}(E_{#nu} [MeV])");
  gPad->SetLogy();
  logEv_bkg1->SetLineWidth(5);
  logEv_bkg1->SetLineColor(kGreen+3);
  logEv_bkg1->SetFillColor(kGreen+3);
  logEv_bkg1->SetFillStyle(3002);
  mytree->Project("logEv_bkg1","log10(nuEnergy)","Tres_RMS<75 && abs(init_lepID)!=11 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 1.E5","");
  c17->cd();
  logEv_bkg1->Draw("same");
  leg6->AddEntry(logEv_nueCC, "#nu_{e}^{CC}" ,"l");
  leg6->AddEntry(logEv_nueCC_fidcut, "#nu_{e}^{CC} fid." ,"l");
  leg6->AddEntry(logEv_nueCC_timecut, "#nu_{e}^{CC} sel." ,"l");  
  leg6->AddEntry(logEv_bkg1, "res. bkg" ,"l");
  leg6->Draw();
  c17->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_less75nscut.png");
  c17->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_less75nscut.pdf");
  c17->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_less75nscut.C");

  TH1F *logEv_allcuts = new TH1F("logEv_allcuts","",binsNPE_nuE,lowNPE_nuE,upNPE_nuE);
  mytree->Project("logEv_allcuts","log10(trueNPE_LPMT_CD)","Tres_RMS<75 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 1.E5","");

  npearray_MC_e << binsNPE_nuE << "\n";
  for(int j=1; j<=binsNPE_nuE; j++) {
    npearray_MC_e << float(logEv_allcuts->GetBinContent(j)) << "\t";
}
  std::cout << filename1 << " created" << std::endl;
  npearray_MC_e.close();


  ///////////////////////////////////////////////////////////////////////////////////

  TCanvas *c18 = new TCanvas("c18","",800,600);
  TLegend * leg7 = new TLegend(0.7,0.9,0.9,0.7);
  TH1F *logEv_numuCC = new TH1F("logEv_numuCC","",binsE_nuMu,lowE_nuMu,upE_nuMu);
  logEv_numuCC->GetXaxis()->SetTitle("log_{10}(E_{#nu} [MeV])");
  logEv_numuCC->GetXaxis()->SetTitleSize(0.05);
  logEv_numuCC->GetXaxis()->SetLabelSize(0.04);
  logEv_numuCC->GetYaxis()->SetTitle("entries");
  logEv_numuCC->GetYaxis()->SetLabelSize(0.05);
  logEv_numuCC->GetYaxis()->SetTitleOffset(1.2);
  logEv_numuCC->SetLineWidth(5);
  logEv_numuCC->SetLineColor(kOrange);
  logEv_numuCC->SetFillColor(kOrange);
  logEv_numuCC->SetFillStyle(3002);
  mytree->Project("logEv_numuCC","log10(nuEnergy)","CCint==1 && abs(init_lepID)==13","");
  logEv_numuCC->Draw();
  TH1F *logEv_numuCC_fidcut = new TH1F("logEv_numuCC_fidcut","",binsE_nuMu,lowE_nuMu,upE_nuMu);
  logEv_numuCC_fidcut->SetLineWidth(5);
  logEv_numuCC_fidcut->SetLineColor(kAzure+1);
  logEv_numuCC_fidcut->SetFillColor(kAzure+1);
  logEv_numuCC_fidcut->SetFillStyle(3002);
  mytree->Project("logEv_numuCC_fidcut","log10(nuEnergy)","CCint==1 && abs(init_lepID)==13 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 5.E5","");
  logEv_numuCC_fidcut->Draw("same");
  TH1F *logEv_numuCC_timecut = new TH1F("logEv_numuCC_timecut","",binsE_nuMu,lowE_nuMu,upE_nuMu);
  logEv_numuCC_timecut->GetXaxis()->SetTitle("log_{10}(E_{#nu} [MeV])");
  logEv_numuCC_timecut->SetLineWidth(5);
  logEv_numuCC_timecut->SetLineColor(kRed);
  logEv_numuCC_timecut->SetFillColor(kRed);
  logEv_numuCC_timecut->SetFillStyle(3002);
  mytree->Project("logEv_numuCC_timecut","log10(nuEnergy)","Tres_RMS>95 && CCint==1 && abs(init_lepID)==13 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 5.E5","");
  logEv_numuCC_timecut->Draw("same");
  TH1F *logEv_bkg2 = new TH1F("logEv_bkg2","",binsE_nuMu,lowE_nuMu,upE_nuMu);
  logEv_bkg2->GetXaxis()->SetTitle("log_{10}(E_{#nu} [MeV])");
  gPad->SetLogy();
  logEv_bkg2->SetLineWidth(5);
  logEv_bkg2->SetLineColor(kGreen+3);
  logEv_bkg2->SetFillColor(kGreen+3);
  logEv_bkg2->SetFillStyle(3002);
  mytree->Project("logEv_bkg2","log10(nuEnergy)","Tres_RMS>95 && abs(init_lepID)!=13 && newVradius<16000 && FC==1 && trueNPE_LPMT_CD > 5.E5","");
  c18->cd();
  logEv_bkg2->Draw("same");
  leg7->AddEntry(logEv_numuCC, "#nu_{#mu}^{CC} FC" ,"l");
  leg7->AddEntry(logEv_numuCC_fidcut, "#nu_{#mu}^{CC} FC fid." ,"l");
  leg7->AddEntry(logEv_numuCC_timecut, "#nu_{#mu}^{CC} FC sel." ,"l");
  leg7->AddEntry(logEv_bkg2, "res. bkg" ,"l");
  leg7->Draw();
  c18->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_over95nscut.png");
  c18->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_over95nscut.pdf");
  c18->SaveAs("Plot/logEv_eff_0-20GeV_16volcut_1m_over95nscut.C");

}
