void makedataplots() {
  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);
  gStyle->SetTitleH(0);
  gStyle->SetPadBottomMargin(0.12);
  gStyle->SetPadLeftMargin(0.085);
  gStyle->SetPadRightMargin(0.05);
    
  TFile *_file0 = TFile::Open("../likelihood/5YRS/output_Nue_osc/Dataplot_7_7.root");
  TH1F *Npe_LPMT_all_nue;
  TH1F *Npe_LPMT_sgn_all_nue;
  TH1F *Npe_LPMT_bkg_all_nue;
  _file0->GetObject("Npe_LPMT_allcuts",Npe_LPMT_all_nue);
  _file0->GetObject("Npe_LPMT_sgn_allcuts",Npe_LPMT_sgn_all_nue);
  _file0->GetObject("Npe_LPMT_bkg_allcuts",Npe_LPMT_bkg_all_nue);
  TFile *_file1 = TFile::Open("../likelihood/5YRS/output_Numu_osc/Dataplot_7_8.root");
  TH1F *Npe_LPMT_all_numu;
  TH1F *Npe_LPMT_sgn_all_numu;
  TH1F *Npe_LPMT_bkg_all_numu;
  _file1->GetObject("Npe_LPMT_allcuts",Npe_LPMT_all_numu);
  _file1->GetObject("Npe_LPMT_sgn_allcuts",Npe_LPMT_sgn_all_numu);
  _file1->GetObject("Npe_LPMT_bkg_allcuts",Npe_LPMT_bkg_all_numu);
  TCanvas *cnue = new TCanvas("cnue","",800,600);
  TCanvas *cnumu = new TCanvas("cmu","",800,600);
  TLegend *lege = new TLegend(0.75,0.63,0.94,0.89);
  TLegend *legmu = new TLegend(0.75,0.63,0.94,0.89);
  lege->SetBorderSize(0);
  legmu->SetBorderSize(0);
  
  cnue->cd();
  Npe_LPMT_all_nue->SetMarkerStyle(20);
  Npe_LPMT_all_nue->SetMarkerSize(1.7);
  Npe_LPMT_all_nue->SetMarkerColor(1);
  Npe_LPMT_all_nue->SetLineColor(1);
  Npe_LPMT_all_nue->Draw("");
  Npe_LPMT_all_nue->GetYaxis()->SetRangeUser(0.,150.);
  Npe_LPMT_all_nue->GetXaxis()->SetTitle("log_{10}(NPE)");
  Npe_LPMT_all_nue->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_all_nue->GetXaxis()->SetLabelSize(0.045);
  Npe_LPMT_all_nue->GetYaxis()->SetTitle("entries");
  Npe_LPMT_all_nue->GetYaxis()->SetTitleOffset(1.0);
  Npe_LPMT_all_nue->GetYaxis()->SetTitleSize(0.045);
  Npe_LPMT_all_nue->GetYaxis()->SetLabelSize(0.045);
  Npe_LPMT_sgn_all_nue->SetLineColor(kBlue-10);
  Npe_LPMT_sgn_all_nue->SetFillColor(kBlue-10);
  Npe_LPMT_sgn_all_nue->SetFillStyle(3000);
  Npe_LPMT_sgn_all_nue->Draw("SAME HISTO");
  Npe_LPMT_bkg_all_nue->SetFillColor(kGreen+3);
  Npe_LPMT_bkg_all_nue->SetFillStyle(3000);
  Npe_LPMT_bkg_all_nue->Draw("SAME HISTO");
  Npe_LPMT_all_nue->Draw("same");
  lege->AddEntry(Npe_LPMT_all_nue,"#nu_{e} sel.","ple");
  lege->AddEntry(Npe_LPMT_sgn_all_nue,"#nu_{e}","f");
  lege->AddEntry(Npe_LPMT_bkg_all_nue,"#nu_{#mu}","f");
  lege->Draw();
  gPad->RedrawAxis();
  cnue->SaveAs("Plot/NPE_LPMT_nuecuts_bins.pdf");
  cnue->SaveAs("Plot/NPE_LPMT_nuecuts_bins.png");
  cnue->SaveAs("Plot/NPE_LPMT_nuecuts_bins.C");
  ///////////////////////////////////////////////////////////////////////
  cnumu->cd();
  Npe_LPMT_all_numu->SetMarkerStyle(20);
  Npe_LPMT_all_numu->SetMarkerSize(1.7);
  Npe_LPMT_all_numu->SetMarkerColor(1);
  Npe_LPMT_all_numu->SetLineColor(1);
  Npe_LPMT_all_numu->GetYaxis()->SetRangeUser(0.,210.);
  Npe_LPMT_all_numu->GetXaxis()->SetTitle("log_{10}(NPE)");
  Npe_LPMT_all_numu->GetXaxis()->SetTitleSize(0.05);
  Npe_LPMT_all_numu->GetXaxis()->SetLabelSize(0.045);
  Npe_LPMT_all_numu->GetYaxis()->SetTitle("entries");
  Npe_LPMT_all_numu->GetYaxis()->SetTitleOffset(1.0);
  Npe_LPMT_all_numu->GetYaxis()->SetTitleSize(0.045);
  Npe_LPMT_all_numu->GetYaxis()->SetLabelSize(0.045);
  Npe_LPMT_all_numu->Draw("");
  Npe_LPMT_sgn_all_numu->SetLineColor(kBlue-10);
  Npe_LPMT_sgn_all_numu->SetFillColor(kBlue-10);
  Npe_LPMT_sgn_all_numu->SetFillStyle(3000);
  Npe_LPMT_sgn_all_numu->Draw("SAME HISTO");
  Npe_LPMT_bkg_all_numu->SetFillColor(kGreen+3);
  Npe_LPMT_bkg_all_numu->SetFillStyle(3000);
  Npe_LPMT_bkg_all_numu->Draw("SAME HISTO");
  Npe_LPMT_all_numu->Draw("same");
  legmu->AddEntry(Npe_LPMT_all_numu,"#nu_{#mu} sel.","ple");
  legmu->AddEntry(Npe_LPMT_sgn_all_numu,"#nu_{#mu}","f");
  legmu->AddEntry(Npe_LPMT_bkg_all_numu,"#nu_{e}","f");
  legmu->Draw();
  gPad->RedrawAxis();
  cnumu->SaveAs("Plot/NPE_LPMT_numucuts_bins.pdf");
  cnumu->SaveAs("Plot/NPE_LPMT_numucuts_bins.png");
  cnumu->SaveAs("Plot/NPE_LPMT_numucuts_bins.C");
  
}
