universe = vanilla
executable = /storage/gpfs_data/juno/junofs/users/zhangjinnan/Atm/CNAF_Atm/Project/Jobs/CNAF_Atm1.sh
Accounting_Group = juno
output = /storage/gpfs_data/juno/junofs/users/zhangjinnan/Atm/CNAF_Atm/Project/Jobs/logs/outputFile.out
error = /storage/gpfs_data/juno/junofs/users/zhangjinnan/Atm/CNAF_Atm/Project/Jobs/logs/errorFile.err
ShouldTransferFiles = YES
WhenToTransferOutput = ON_EXIT
queue 1